export type MessageCatalog = Record<string, string>;

export const enUSCatalog = {
  "common.open": "Open",
  "common.close": "Close",
  "common.retry": "Retry",
  "common.save": "Save",
  "common.loadingCli": "Loading wtfOS CLI...",
  "common.noCommands": "No commands",
  "appWindow.crashedTitle": "{title} - crashed",
  "appWindow.disabledTitle": "{title} - disabled",
  "appWindow.renderErrorTitle": "This app hit a render error.",
  "appWindow.renderErrorBody":
    "The rest of WTF OS is still running. You can retry this window or close it and keep working.",
  "appWindow.adminSettings": "{label} admin settings",
  "appWindow.minimize": "Minimize {title}",
  "appWindow.maximize": "Maximize {title}",
  "appWindow.restore": "Restore {title}",
  "appWindow.close": "Close {title}",
  "appWindow.disabledBody":
    "This app is currently unavailable. Ask an admin to re-enable it or adjust role access before trying again.",
  "appWindow.disabledHeading": "{label} has been disabled by admin.",
  "startMenu.searchLabel": "Find stuff",
  "startMenu.searchPlaceholder": "Find stuff...",
  "startMenu.emptyUser": "No matching stuff. Try Mission, Wallet, Daily, Media, or Admin.",
  "startMenu.emptyGuest":
    "No matching stuff here. Log in for account, daily, wallet, and admin tools.",
  "startMenu.logout": "Log Out",
  "startMenu.login": "Log In",
  "startMenu.hint": "Type to filter. Right-click or Shift-click an app for shortcuts.",
  "startMenu.context.open": "Open",
  "startMenu.context.createShortcut": "Create Desktop Shortcut",
  "startMenu.disabled.casino": "Casino membership card required",
  "startMenu.group.apps": "Apps",
  "startMenu.group.gameshow": "Gameshow",
  "startMenu.group.create": "CREATE!",
  "startMenu.group.social": "Social",
  "startMenu.group.onChain": "On Chain",
  "startMenu.group.gaming": "Gaming",
  "startMenu.group.myMedia": "My Media",
  "startMenu.group.browse": "Browse",
  "startMenu.group.account": "Account",
  "startMenu.group.settings": "Settings",
  "startMenu.group.admin": "Admin",
  "commandPalette.title": "Command Palette",
  "commandPalette.searchLabel": "Search commands",
  "commandPalette.placeholder": "Command",
  "commandPalette.category.wallet": "Wallet",
  "commandPalette.category.reward": "Reward",
  "commandPalette.category.media": "Media",
  "commandPalette.category.system": "System",
  "commandPalette.category.admin": "Admin",
  "commandPalette.category.app": "App",
  "commandPalette.category.route": "Route",
  "commandPalette.command.claimableRewards": "Find Claimable Rewards",
  "commandPalette.command.activeRounds": "Open Active Rounds",
  "commandPalette.command.walletActivity": "Show Wallet Activity",
  "commandPalette.command.fileManager": "Open File Manager",
  "commandPalette.command.prepareIpfs": "Prepare Media for IPFS",
  "commandPalette.command.myVideos": "Open My Videos",
  "commandPalette.command.studioProjects": "Open Studio Projects",
  "commandPalette.command.projectBundles": "Open Project Bundles",
  "commandPalette.command.gameStudioProjects": "Open Game Studio Projects",
  "commandPalette.command.systemChecks": "Show System Checks",
  "commandPalette.command.commandPalette": "Open Command Palette",
  "commandPalette.command.runningChecks": "Review Running Checks",
  "commandPalette.command.recovery": "Open Recovery Mode",
  "commandPalette.command.exportRecovery": "Export Recovery Report",
  "commandPalette.command.restoreBackup": "Restore or Prove Backup",
  "commandPalette.command.backupManager": "Open Backup Manager",
  "commandPalette.command.notificationCenter": "Open Notification Center",
  "commandPalette.command.themeBuilder": "Open Theme Builder",
  "commandPalette.command.systemSettings": "Open System Settings",
  "commandPalette.command.browserBoundaries": "Open Browser Boundaries",
  "commandPalette.command.terminal": "Open Terminal",
  "commandPalette.command.cli": "Open CLI Shell",
  "desktop.context.open": "Open",
  "desktop.context.createShortcut": "Create Shortcut",
  "desktop.context.properties": "Properties",
  "desktop.context.deleteShortcut": "Delete Shortcut",
  "desktop.context.removeFromDesktop": "Remove from Desktop",
  "desktop.context.refresh": "Refresh",
  "desktop.context.resetNativeIcons": "Reset Native Icons",
  "desktop.context.systemAppearance": "System Appearance",
  "taskbar.start": "Stuffs",
  "taskbar.openStart": "Open Stuffs menu",
  "taskbar.windowTitle": "{title} - click to {action}, middle-click to close",
  "taskbar.windowAction.minimize": "minimize",
  "taskbar.windowAction.focus": "focus",
  "taskbar.context.restore": "Restore",
  "taskbar.context.focus": "Focus",
  "taskbar.context.minimize": "Minimize",
  "taskbar.context.close": "Close",
  "taskbar.showDesktop": "Show desktop",
  "taskbar.restoreWindows": "Restore windows",
  "taskbar.petCare": "Pet care",
  "taskbar.weather": "Desktop weather",
  "taskbar.weatherState": "Desktop weather: {rule}",
  "taskbar.wallet": "Wallet",
  "taskbar.walletTrayOpen": "Open wallet tray",
  "taskbar.walletConnectionTrayOpen": "Open wallet connection tray",
  "taskbar.walletConnected": "Connected",
  "taskbar.walletConnectedTitle": "Connected: {address}",
  "taskbar.walletDisconnectedTitle": "Wallet not connected",
  "taskbar.walletDisconnect": "Disconnect Wallet",
  "taskbar.walletNoConnection": "No wallet connected",
  "taskbar.walletConnecting": "Connecting...",
  "taskbar.walletConnect": "Connect Wallet",
  "taskbar.walletTrayClose": "Close wallet tray",
  "taskbar.weatherClose": "Close desktop weather",
  "taskbar.weatherSet": "Set desktop weather to {label}",
  "taskbar.weather.off": "Off",
  "taskbar.weather.gentle": "Gentle",
  "taskbar.weather.stormy": "Stormy",
  "systemSettings.title": "Settings",
  "systemSettings.status.role": "Role",
  "systemSettings.status.visible": "Visible",
  "systemSettings.status.admin": "Admin",
  "systemSettings.status.mode": "Mode",
  "systemSettings.admin.enabled": "enabled",
  "systemSettings.admin.hidden": "hidden",
  "systemSettings.panel.system": "System settings",
  "systemSettings.panel.interface": "Interface",
  "systemSettings.panel.language": "Language & Region",
  "systemSettings.panel.boundary": "Boundary",
  "systemSettings.language.title": "Choose your language",
  "systemSettings.language.detail":
    "System-owned text updates across the OS shell. User posts, chats, project names, token metadata, and profile text stay as authored.",
  "systemSettings.language.label": "Display language",
  "systemSettings.language.regionLabel": "Region",
  "systemSettings.language.pending": "Saving language preference...",
  "systemSettings.language.saved": "Language preference saved.",
  "systemSettings.language.changeAction": "Use {language}",
  "systemSettings.openSetting": "Open {label}",
  "systemSettings.interface.title": "Choose your wtfOS interface",
  "systemSettings.interface.detail":
    "Desktop is the default windowed experience. CLI is the full-screen safe command-line interface powered by the same kernel as Terminal.",
  "systemSettings.interface.desktop": "Use desktop",
  "systemSettings.interface.cli": "Use CLI",
  "systemSettings.boundary.title": "Settings ownership stays with each app",
  "systemSettings.boundary.detail":
    "This hub routes to existing owner surfaces and does not bypass their permissions, wallet preflights, CSRF rules, or admin gates.",
  "systemSettings.boundary.openMissionControl": "Open Mission Control",
  "settingsCard.profile.label": "Account Profile",
  "settingsCard.profile.owner": "Identity",
  "settingsCard.profile.detail": "name, avatar, public profile, social links, password",
  "settingsCard.commands.label": "Command Palette",
  "settingsCard.commands.owner": "Desktop OS",
  "settingsCard.commands.detail": "app launcher, route search, workflow commands",
  "settingsCard.appearance.label": "Theme Builder",
  "settingsCard.appearance.owner": "Desktop OS",
  "settingsCard.appearance.detail": "OS appearance, theme colors, wallpaper, cursor, physics mode",
  "settingsCard.notifications.label": "Notifications",
  "settingsCard.notifications.owner": "Inbox",
  "settingsCard.notifications.detail": "notification preferences, unread items, linked targets",
  "settingsCard.files.label": "Files and Dwellings",
  "settingsCard.files.owner": "File Manager",
  "settingsCard.files.detail": "Desktop, Projects, Media, Vault, Apps, Chain, Archives",
  "settingsCard.wallet.label": "Wallet and Portfolio",
  "settingsCard.wallet.owner": "Cockpit",
  "settingsCard.wallet.detail": "active wallet, holdings, balances, sync state",
  "settingsCard.subdomains.label": "Subdomain Setup",
  "settingsCard.subdomains.owner": "WTF Domains",
  "settingsCard.subdomains.detail": "claim username.wtfos.me and prepare wtf.tez setup",
  "settingsCard.w.label": "W Social",
  "settingsCard.w.owner": "W",
  "settingsCard.w.detail": "scraped X timeline cache and read-only Gameshow chat",
  "settingsCard.terminal.label": "Terminal",
  "settingsCard.terminal.owner": "Desktop OS",
  "settingsCard.terminal.detail": "embedded safe commands, health checks, jobs, access routes",
  "settingsCard.cli.label": "CLI Shell",
  "settingsCard.cli.owner": "Desktop OS",
  "settingsCard.cli.detail": "full-screen CLI/TUI using the same safe command kernel",
  "settingsCard.recovery.label": "Recovery Mode",
  "settingsCard.recovery.owner": "Recovery",
  "settingsCard.recovery.detail": "wallet disconnect, network reset, shell report export",
  "settingsCard.admin.label": "Admin Panel",
  "settingsCard.admin.owner": "Admin",
  "settingsCard.admin.detail": "permissions, app gates, users, logs, content",
  "settingsCard.backup.label": "Backup Manager",
  "settingsCard.backup.owner": "Admin",
  "settingsCard.backup.detail": "restore proof, backup artifact, checksum, target safety",
  "settingsCard.control.label": "Control Board",
  "settingsCard.control.owner": "Gameshow Admin",
  "settingsCard.control.detail": "round operations, host actions, contestant state",
  "themeBuilder.title": "Theme Builder",
  "themeBuilder.section.appearance": "OS appearance",
  "themeBuilder.section.typography": "System typography",
  "themeBuilder.typography.help":
    "Font packs apply instantly across the desktop shell and app windows.",
  "themeBuilder.section.chatDefaults": "Chat defaults",
  "themeBuilder.chatDefaults.help":
    "These presets seed WIM messages and WTF LIVE room chat while keeping each composer inside its own font and size window.",
  "themeBuilder.section.colorSchemes": "Color schemes",
  "themeBuilder.section.desktop": "Desktop",
  "themeBuilder.field.backgroundUrl": "Background image URL",
  "themeBuilder.action.uploadBackground": "Upload background image",
  "themeBuilder.action.upload": "Upload",
  "themeBuilder.action.clear": "Clear",
  "themeBuilder.field.fit": "Fit",
  "themeBuilder.field.backgroundFit": "Background image fit",
  "themeBuilder.upload.help": "Uploads use your media library and accept images up to {size}.",
  "themeBuilder.upload.pending": " Uploading...",
  "themeBuilder.upload.imagesOnly": "Image files only.",
  "themeBuilder.upload.tooLarge": "Pick an image under {size}.",
  "themeBuilder.upload.failed": "Upload failed.",
  "themeBuilder.section.savedImages": "Saved images",
  "themeBuilder.savedImages.loading": "Loading saved media...",
  "themeBuilder.savedImages.error": "Saved media could not load.",
  "themeBuilder.savedImages.empty": "No saved image media yet.",
  "themeBuilder.section.tokenArt": "Owned token art",
  "themeBuilder.tokenArt.loading": "Loading wallet art...",
  "themeBuilder.tokenArt.error": "Wallet art could not load.",
  "themeBuilder.tokenArt.empty": "No image tokens found in your synced wallets.",
  "themeBuilder.section.cursor": "Cursor",
  "themeBuilder.section.physics": "Physics",
  "themeBuilder.color.desktop": "Desktop",
  "themeBuilder.color.window": "Window",
  "themeBuilder.color.activeFrame": "Active frame",
  "themeBuilder.color.inactiveFrame": "Inactive frame",
  "themeBuilder.color.text": "Text",
  "themeBuilder.color.highlight": "Highlight",
  "themeBuilder.colorInput": "{label} color",
  "themeBuilder.field.font": "Font",
  "themeBuilder.field.size": "Size",
  "themeBuilder.field.color": "Color",
  "themeBuilder.chat.wimMessages": "WIM messages",
  "themeBuilder.chat.liveRoomChat": "WTF LIVE room chat",
  "themeBuilder.chat.defaultWimFont": "Default WIM font",
  "themeBuilder.chat.defaultWimFontSize": "Default WIM font size",
  "themeBuilder.chat.defaultWimTextColor": "Default WIM text color",
  "themeBuilder.chat.defaultWimEmphasis": "Default WIM emphasis",
  "themeBuilder.chat.defaultWimBold": "Default WIM bold",
  "themeBuilder.chat.defaultWimItalic": "Default WIM italic",
  "themeBuilder.chat.defaultWimUnderline": "Default WIM underline",
  "themeBuilder.chat.defaultLiveFont": "Default WTF LIVE chat font",
  "themeBuilder.chat.defaultLiveFontSize": "Default WTF LIVE chat font size",
  "themeBuilder.chat.defaultLiveColor": "Default WTF LIVE chat color",
  "themeBuilder.chat.defaultLiveColorChoice": "Default WTF LIVE chat color {color}",
  "themeBuilder.chat.defaultLiveEmphasis": "Default WTF LIVE emphasis",
  "themeBuilder.chat.defaultLiveBold": "Default WTF LIVE bold",
  "themeBuilder.chat.defaultLiveItalic": "Default WTF LIVE italic",
  "themeBuilder.field.physics": "Desktop physics",
  "themeBuilder.field.gravity": "Gravity",
  "themeBuilder.action.resetIcons": "Reset Icons",
  "themeBuilder.section.pet": "Pet",
  "themeBuilder.field.petEnabled": "Desktop pet",
  "themeBuilder.action.savePet": "Save Pet",
  "themeBuilder.pet.name": "Name",
  "themeBuilder.pet.coat": "Coat",
  "themeBuilder.pet.progress": "Lv {level} · {xp} XP · {care} care",
  "themeBuilder.pet.action.adopt": "Adopt",
  "themeBuilder.pet.action.feed": "Feed",
  "themeBuilder.pet.action.water": "Water",
  "themeBuilder.pet.action.play": "Play",
  "themeBuilder.pet.action.pet": "Pet",
  "themeBuilder.pet.action.clean": "Clean",
  "themeBuilder.pet.action.scoop": "Scoop",
  "themeBuilder.pet.action.nap": "Nap",
  "themeBuilder.pet.stat.food": "Food",
  "themeBuilder.pet.stat.water": "Water",
  "themeBuilder.pet.stat.fun": "Fun",
  "themeBuilder.pet.stat.clean": "Clean",
  "themeBuilder.pet.stat.energy": "Energy",
  "themeBuilder.pet.stat.happyIndex": "Happy Index",
  "themeBuilder.pet.stat.trauma": "Trauma",
  "themeBuilder.pet.geneLine": "Gen {generation} · Bond L{bondLevel} · {rarity} · {size}",
  "themeBuilder.pet.noRareTraits": "No rare traits",
  "themeBuilder.pet.gene.metabolism": "Metabolism",
  "themeBuilder.pet.gene.speed": "Speed",
  "themeBuilder.pet.gene.strength": "Strength",
  "themeBuilder.pet.gene.intelligence": "Brains",
  "themeBuilder.pet.gene.stamina": "Stamina",
  "themeBuilder.pet.gene.sociability": "Social",
  "themeBuilder.pet.gene.grit": "Grit",
  "themeBuilder.pet.gene.luck": "Luck",
  "themeBuilder.section.agent": "Agent pairing",
  "themeBuilder.field.mcpEndpoint": "MCP endpoint",
  "themeBuilder.field.tokenName": "Token name",
  "themeBuilder.action.generateToken": "Generate Token",
  "themeBuilder.field.newToken": "New token",
  "themeBuilder.action.copy": "Copy",
  "themeBuilder.agents.loading": "Loading paired agents...",
  "themeBuilder.agents.empty": "No active paired agents.",
  "themeBuilder.agents.created": "{prefix}... · created {date}",
  "themeBuilder.agents.lastUsed": " · last used {date}",
  "themeBuilder.action.revoke": "Revoke",
  "route.gamma.title": "WTFOS Gamma",
  "route.beta.title": "WTFOS Beta",
  "route.missionControl.title": "Mission Control",
  "route.recovery.title": "Recovery Mode",
  "route.fileManager.title": "File Manager",
  "route.settings.title": "Settings",
  "route.browserBoundaries.title": "Browser Boundaries",
  "route.applications.title": "Applications",
  "route.agent.title": "Agent",
  "route.terminal.title": "Terminal",
  "route.cli.title": "CLI",
  "route.backup.title": "Backup Manager",
  "route.dashboard.title": "Dashboard",
  "route.rounds.title": "Rounds",
  "route.challenges.title": "Challenges",
  "route.sideQuests.title": "Side Quests",
  "route.inbox.title": "Inbox",
  "route.notifications.title": "Notification Center",
  "route.diary.title": "Dear Diary",
  "route.market.title": "On Chain Market",
  "route.ratRace.title": "Rat Race",
  "route.mapLab.title": "WTF Map Lab",
  "route.tradeBoards.title": "Trade Boards",
  "route.w.title": "W Feed",
  "route.wChat.title": "W Chat",
  "route.tv.title": "WTF TV",
  "route.dicksword.title": "Dicksword",
  "route.telegram.title": "I Hate Telegram",
  "route.arcade.title": "WTF Arcade",
  "route.casino.title": "WTF Casino",
  "route.console.title": "Game Console",
  "route.gameStudio.title": "Game Studio",
  "route.dedrooms.title": "DedRooms",
  "route.swap.title": "Swap",
  "route.profile.title": "Profile",
  "route.themeBuilder.title": "Theme Builder",
  "route.systemAppearance.title": "System Appearance",
  "route.admin.title": "Admin Panel",
  "route.hoard.title": "Hoard",
  "route.myVideos.title": "My Videos",
  "route.myPhotos.title": "My Photos",
  "route.myMusic.title": "My Music",
  "route.ipfs.title": "IPFS Pinning Manager",
  "route.studio.title": "Studio",
  "route.leaderboard.title": "Leaderboard",
  "route.gallery.title": "Gallery",
  "route.myGallery.title": "My Gallery",
  "route.collekt.title": "colleKT",
  "route.tezosIntel.title": "Tezos Intel",
  "route.domains.title": "WTF Domains",
  "route.links.title": "Links",
  "route.faq.title": "FAQ",
  "route.calendar.title": "Calendar",
  "route.mintPortal.title": "Mint Portal",
  "route.contractFactory.title": "Contract Factory",
  "route.operatorWallet.title": "Operator Wallet",
  "route.controlBoard.title": "Control Board",
  "route.skywire.title": "Skywire",
  "route.live.title": "WTF LIVE",
  "route.tz2at.title": "tz2at",
  "route.crp.title": "CRP Nominations",
  "route.wim.title": "WIM",
  "route.mail.title": "WTF Mail",
  "route.digest.title": "Digest",
  "route.browser.title": "Browser",
  "route.music.title": "TezosBeats",
  "route.taskManager.title": "Task Manager",
  "route.uxLab.title": "UX Lab",
} as const satisfies MessageCatalog;

export type MessageId = keyof typeof enUSCatalog;

export const systemTextMessageIds: Record<string, MessageId> = {
  "WTFOS Gamma": "route.gamma.title",
  "WTFOS Beta": "route.beta.title",
  "Mission Control": "route.missionControl.title",
  "Command Palette": "settingsCard.commands.label",
  "Recovery Mode": "route.recovery.title",
  "File Manager": "route.fileManager.title",
  Settings: "route.settings.title",
  "Browser Boundaries": "route.browserBoundaries.title",
  Applications: "route.applications.title",
  Agent: "route.agent.title",
  Terminal: "route.terminal.title",
  CLI: "route.cli.title",
  "Backup Manager": "route.backup.title",
  Dashboard: "route.dashboard.title",
  Rounds: "route.rounds.title",
  Challenges: "route.challenges.title",
  "Side Quests": "route.sideQuests.title",
  Inbox: "route.inbox.title",
  "Notification Center": "route.notifications.title",
  "Dear Diary": "route.diary.title",
  "On Chain Market": "route.market.title",
  "Rat Race": "route.ratRace.title",
  "WTF Map Lab": "route.mapLab.title",
  "Trade Boards": "route.tradeBoards.title",
  "W Feed": "route.w.title",
  "W Chat": "route.wChat.title",
  "WTF TV": "route.tv.title",
  Dicksword: "route.dicksword.title",
  "I Hate Telegram": "route.telegram.title",
  "WTF Arcade": "route.arcade.title",
  "WTF Casino": "route.casino.title",
  "Game Console": "route.console.title",
  "WTF Console": "route.console.title",
  "Game Studio": "route.gameStudio.title",
  DedRooms: "route.dedrooms.title",
  Swap: "route.swap.title",
  Profile: "route.profile.title",
  "Theme Builder": "route.themeBuilder.title",
  "System Appearance": "route.systemAppearance.title",
  "Admin Panel": "route.admin.title",
  Hoard: "route.hoard.title",
  "My Videos": "route.myVideos.title",
  "My Photos": "route.myPhotos.title",
  "My Music": "route.myMusic.title",
  "IPFS Pinning Manager": "route.ipfs.title",
  "IPFS Pinning": "route.ipfs.title",
  Studio: "route.studio.title",
  Leaderboard: "route.leaderboard.title",
  Gallery: "route.gallery.title",
  "My Gallery": "route.myGallery.title",
  colleKT: "route.collekt.title",
  "Tezos Intel": "route.tezosIntel.title",
  "WTF Domains": "route.domains.title",
  Links: "route.links.title",
  FAQ: "route.faq.title",
  Calendar: "route.calendar.title",
  "Mint Portal": "route.mintPortal.title",
  "Contract Factory": "route.contractFactory.title",
  "Operator Wallet": "route.operatorWallet.title",
  "Control Board": "route.controlBoard.title",
  Skywire: "route.skywire.title",
  "WTF LIVE": "route.live.title",
  tz2at: "route.tz2at.title",
  "CRP Nominations": "route.crp.title",
  CRP: "route.crp.title",
  WIM: "route.wim.title",
  "WTF Mail": "route.mail.title",
  Digest: "route.digest.title",
  Browser: "route.browser.title",
  TezosBeats: "route.music.title",
  "Task Manager": "route.taskManager.title",
  "UX Lab": "route.uxLab.title",
  "Casino membership card required": "startMenu.disabled.casino",
  "Find Claimable Rewards": "commandPalette.command.claimableRewards",
  "Open Active Rounds": "commandPalette.command.activeRounds",
  "Show Wallet Activity": "commandPalette.command.walletActivity",
  "Open File Manager": "commandPalette.command.fileManager",
  "Prepare Media for IPFS": "commandPalette.command.prepareIpfs",
  "Open My Videos": "commandPalette.command.myVideos",
  "Open Studio Projects": "commandPalette.command.studioProjects",
  "Open Project Bundles": "commandPalette.command.projectBundles",
  "Open Game Studio Projects": "commandPalette.command.gameStudioProjects",
  "Show System Checks": "commandPalette.command.systemChecks",
  "Open Command Palette": "commandPalette.command.commandPalette",
  "Review Running Checks": "commandPalette.command.runningChecks",
  "Open Recovery Mode": "commandPalette.command.recovery",
  "Export Recovery Report": "commandPalette.command.exportRecovery",
  "Restore or Prove Backup": "commandPalette.command.restoreBackup",
  "Open Backup Manager": "commandPalette.command.backupManager",
  "Open Notification Center": "commandPalette.command.notificationCenter",
  "Open Theme Builder": "commandPalette.command.themeBuilder",
  "Open System Settings": "commandPalette.command.systemSettings",
  "Open Browser Boundaries": "commandPalette.command.browserBoundaries",
  "Open Terminal": "commandPalette.command.terminal",
  "Open CLI Shell": "commandPalette.command.cli",
};

function pseudoValue(value: string): string {
  return `[!! ${value
    .replace(/[aA]/g, "á")
    .replace(/[eE]/g, "é")
    .replace(/[iI]/g, "í")
    .replace(/[oO]/g, "ó")
    .replace(/[uU]/g, "ú")} !!]`;
}

export const esESCatalog = {
  ...enUSCatalog,
  "common.open": "Abrir",
  "common.close": "Cerrar",
  "common.retry": "Reintentar",
  "common.save": "Guardar",
  "common.loadingCli": "Cargando la CLI de wtfOS...",
  "common.noCommands": "No hay comandos",
  "appWindow.crashedTitle": "{title} - se bloqueó",
  "appWindow.disabledTitle": "{title} - desactivado",
  "appWindow.renderErrorTitle": "Esta app tuvo un error de renderizado.",
  "appWindow.renderErrorBody":
    "El resto de WTF OS sigue funcionando. Puedes reintentar esta ventana o cerrarla y seguir trabajando.",
  "appWindow.adminSettings": "ajustes de administración de {label}",
  "appWindow.minimize": "Minimizar {title}",
  "appWindow.maximize": "Maximizar {title}",
  "appWindow.restore": "Restaurar {title}",
  "appWindow.close": "Cerrar {title}",
  "appWindow.disabledBody":
    "Esta app no está disponible ahora. Pide a un administrador que la active de nuevo o que ajuste el acceso por rol.",
  "appWindow.disabledHeading": "{label} fue desactivada por administración.",
  "startMenu.searchLabel": "Buscar herramientas",
  "startMenu.searchPlaceholder": "Buscar herramientas...",
  "startMenu.emptyUser": "Sin coincidencias. Prueba Misión, Billetera, Diario, Medios o Admin.",
  "startMenu.emptyGuest":
    "Aquí no hay coincidencias. Inicia sesión para ver cuenta, diario, billetera y herramientas de admin.",
  "startMenu.logout": "Cerrar sesión",
  "startMenu.login": "Iniciar sesión",
  "startMenu.hint":
    "Escribe para filtrar. Clic derecho o Mayús-clic en una app para accesos directos.",
  "startMenu.context.open": "Abrir",
  "startMenu.context.createShortcut": "Crear acceso directo de escritorio",
  "startMenu.disabled.casino": "Se requiere tarjeta de membresía del casino",
  "startMenu.group.apps": "Apps",
  "startMenu.group.gameshow": "Concurso",
  "startMenu.group.create": "¡CREAR!",
  "startMenu.group.social": "Social",
  "startMenu.group.onChain": "En cadena",
  "startMenu.group.gaming": "Juegos",
  "startMenu.group.myMedia": "Mis medios",
  "startMenu.group.browse": "Explorar",
  "startMenu.group.account": "Cuenta",
  "startMenu.group.settings": "Ajustes",
  "startMenu.group.admin": "Admin",
  "commandPalette.title": "Paleta de comandos",
  "commandPalette.searchLabel": "Buscar comandos",
  "commandPalette.placeholder": "Comando",
  "commandPalette.category.wallet": "Billetera",
  "commandPalette.category.reward": "Recompensa",
  "commandPalette.category.media": "Medios",
  "commandPalette.category.system": "Sistema",
  "commandPalette.category.admin": "Admin",
  "commandPalette.category.app": "App",
  "commandPalette.category.route": "Ruta",
  "commandPalette.command.claimableRewards": "Buscar recompensas reclamables",
  "commandPalette.command.activeRounds": "Abrir rondas activas",
  "commandPalette.command.walletActivity": "Mostrar actividad de billetera",
  "commandPalette.command.fileManager": "Abrir gestor de archivos",
  "commandPalette.command.prepareIpfs": "Preparar medios para IPFS",
  "commandPalette.command.myVideos": "Abrir mis videos",
  "commandPalette.command.studioProjects": "Abrir proyectos de Studio",
  "commandPalette.command.projectBundles": "Abrir paquetes de proyecto",
  "commandPalette.command.gameStudioProjects": "Abrir proyectos de Game Studio",
  "commandPalette.command.systemChecks": "Mostrar comprobaciones del sistema",
  "commandPalette.command.commandPalette": "Abrir paleta de comandos",
  "commandPalette.command.runningChecks": "Revisar comprobaciones en ejecución",
  "commandPalette.command.recovery": "Abrir modo de recuperación",
  "commandPalette.command.exportRecovery": "Exportar informe de recuperación",
  "commandPalette.command.restoreBackup": "Restaurar o probar una copia",
  "commandPalette.command.backupManager": "Abrir gestor de copias",
  "commandPalette.command.notificationCenter": "Abrir centro de notificaciones",
  "commandPalette.command.themeBuilder": "Abrir constructor de temas",
  "commandPalette.command.systemSettings": "Abrir ajustes del sistema",
  "commandPalette.command.browserBoundaries": "Abrir límites del navegador",
  "commandPalette.command.terminal": "Abrir terminal",
  "commandPalette.command.cli": "Abrir shell CLI",
  "desktop.context.open": "Abrir",
  "desktop.context.createShortcut": "Crear acceso directo",
  "desktop.context.properties": "Propiedades",
  "desktop.context.deleteShortcut": "Eliminar acceso directo",
  "desktop.context.removeFromDesktop": "Quitar del escritorio",
  "desktop.context.refresh": "Actualizar",
  "desktop.context.resetNativeIcons": "Restablecer iconos nativos",
  "desktop.context.systemAppearance": "Apariencia del sistema",
  "taskbar.start": "Cosas",
  "taskbar.openStart": "Abrir menú Cosas",
  "taskbar.windowTitle": "{title} - clic para {action}; clic central para cerrar",
  "taskbar.windowAction.minimize": "minimizar",
  "taskbar.windowAction.focus": "enfocar",
  "taskbar.context.restore": "Restaurar",
  "taskbar.context.focus": "Enfocar",
  "taskbar.context.minimize": "Minimizar",
  "taskbar.context.close": "Cerrar",
  "taskbar.showDesktop": "Mostrar escritorio",
  "taskbar.restoreWindows": "Restaurar ventanas",
  "taskbar.petCare": "Cuidado de mascota",
  "taskbar.weather": "Clima del escritorio",
  "taskbar.weatherState": "Clima del escritorio: {rule}",
  "taskbar.wallet": "Billetera",
  "taskbar.walletTrayOpen": "Abrir bandeja de billetera",
  "taskbar.walletConnectionTrayOpen": "Abrir conexión de billetera",
  "taskbar.walletConnected": "Conectada",
  "taskbar.walletConnectedTitle": "Conectada: {address}",
  "taskbar.walletDisconnectedTitle": "Billetera no conectada",
  "taskbar.walletDisconnect": "Desconectar billetera",
  "taskbar.walletNoConnection": "No hay billetera conectada",
  "taskbar.walletConnecting": "Conectando...",
  "taskbar.walletConnect": "Conectar billetera",
  "taskbar.walletTrayClose": "Cerrar bandeja de billetera",
  "taskbar.weatherClose": "Cerrar clima del escritorio",
  "taskbar.weatherSet": "Definir clima del escritorio como {label}",
  "taskbar.weather.off": "Apagado",
  "taskbar.weather.gentle": "Suave",
  "taskbar.weather.stormy": "Tormenta",
  "systemSettings.title": "Ajustes",
  "systemSettings.status.role": "Rol",
  "systemSettings.status.visible": "Visible",
  "systemSettings.status.admin": "Admin",
  "systemSettings.status.mode": "Modo",
  "systemSettings.admin.enabled": "activo",
  "systemSettings.admin.hidden": "oculto",
  "systemSettings.panel.system": "Ajustes del sistema",
  "systemSettings.panel.interface": "Interfaz",
  "systemSettings.panel.language": "Idioma y región",
  "systemSettings.panel.boundary": "Límite",
  "systemSettings.language.title": "Elige tu idioma",
  "systemSettings.language.detail":
    "El texto del sistema cambia en toda la shell del OS. Publicaciones, chats, proyectos, metadatos de tokens y perfiles quedan como fueron escritos.",
  "systemSettings.language.label": "Idioma de la interfaz",
  "systemSettings.language.regionLabel": "Región",
  "systemSettings.language.pending": "Guardando preferencia de idioma...",
  "systemSettings.language.saved": "Preferencia de idioma guardada.",
  "systemSettings.language.changeAction": "Usar {language}",
  "systemSettings.openSetting": "Abrir {label}",
  "systemSettings.interface.title": "Elige tu interfaz de wtfOS",
  "systemSettings.interface.detail":
    "Escritorio es la experiencia predeterminada con ventanas. CLI es la interfaz segura de línea de comandos a pantalla completa, con el mismo núcleo que Terminal.",
  "systemSettings.interface.desktop": "Usar escritorio",
  "systemSettings.interface.cli": "Usar CLI",
  "systemSettings.boundary.title": "La propiedad de ajustes se queda en cada app",
  "systemSettings.boundary.detail":
    "Este centro abre superficies existentes y no se salta permisos, revisiones de billetera, reglas CSRF ni puertas de administración.",
  "systemSettings.boundary.openMissionControl": "Abrir Control de misión",
  "settingsCard.profile.label": "Perfil de cuenta",
  "settingsCard.profile.owner": "Identidad",
  "settingsCard.profile.detail": "nombre, avatar, perfil público, enlaces sociales, contraseña",
  "settingsCard.appearance.label": "Constructor de temas",
  "settingsCard.notifications.label": "Notificaciones",
  "settingsCard.files.label": "Archivos y moradas",
  "settingsCard.wallet.label": "Billetera y cartera",
  "settingsCard.subdomains.label": "Configurar subdominio",
  "settingsCard.terminal.label": "Terminal",
  "settingsCard.cli.label": "Shell CLI",
  "settingsCard.recovery.label": "Modo de recuperación",
  "settingsCard.admin.label": "Panel de administración",
  "settingsCard.backup.label": "Gestor de copias",
  "settingsCard.control.label": "Panel de control",
  "themeBuilder.title": "Constructor de temas",
  "themeBuilder.section.appearance": "Apariencia del OS",
  "themeBuilder.section.typography": "Tipografía del sistema",
  "themeBuilder.typography.help":
    "Los paquetes de fuentes se aplican al instante en la shell del escritorio y las ventanas de apps.",
  "themeBuilder.section.chatDefaults": "Valores de chat",
  "themeBuilder.chatDefaults.help":
    "Estos ajustes inicializan los mensajes de WIM y el chat de salas WTF LIVE sin sacar cada compositor de su propia ventana de fuente y tamaño.",
  "themeBuilder.section.colorSchemes": "Esquemas de color",
  "themeBuilder.section.desktop": "Escritorio",
  "themeBuilder.field.backgroundUrl": "URL de imagen de fondo",
  "themeBuilder.action.uploadBackground": "Subir imagen de fondo",
  "themeBuilder.action.upload": "Subir",
  "themeBuilder.action.clear": "Limpiar",
  "themeBuilder.field.fit": "Ajuste",
  "themeBuilder.field.backgroundFit": "Ajuste de imagen de fondo",
  "themeBuilder.upload.help":
    "Las subidas usan tu biblioteca de medios y aceptan imágenes de hasta {size}.",
  "themeBuilder.upload.pending": " Subiendo...",
  "themeBuilder.upload.imagesOnly": "Solo archivos de imagen.",
  "themeBuilder.upload.tooLarge": "Elige una imagen de menos de {size}.",
  "themeBuilder.upload.failed": "No se pudo subir.",
  "themeBuilder.section.savedImages": "Imágenes guardadas",
  "themeBuilder.savedImages.loading": "Cargando medios guardados...",
  "themeBuilder.savedImages.error": "No se pudieron cargar los medios guardados.",
  "themeBuilder.savedImages.empty": "Aún no hay medios de imagen guardados.",
  "themeBuilder.section.tokenArt": "Arte de tokens propios",
  "themeBuilder.tokenArt.loading": "Cargando arte de billetera...",
  "themeBuilder.tokenArt.error": "No se pudo cargar el arte de la billetera.",
  "themeBuilder.tokenArt.empty": "No se encontraron tokens de imagen en tus billeteras sincronizadas.",
  "themeBuilder.section.cursor": "Cursor",
  "themeBuilder.section.physics": "Física",
  "themeBuilder.color.desktop": "Escritorio",
  "themeBuilder.color.window": "Ventana",
  "themeBuilder.color.activeFrame": "Marco activo",
  "themeBuilder.color.inactiveFrame": "Marco inactivo",
  "themeBuilder.color.text": "Texto",
  "themeBuilder.color.highlight": "Resaltado",
  "themeBuilder.colorInput": "Color de {label}",
  "themeBuilder.field.font": "Fuente",
  "themeBuilder.field.size": "Tamaño",
  "themeBuilder.field.color": "Color",
  "themeBuilder.chat.wimMessages": "Mensajes WIM",
  "themeBuilder.chat.liveRoomChat": "Chat de sala WTF LIVE",
  "themeBuilder.chat.defaultWimFont": "Fuente predeterminada de WIM",
  "themeBuilder.chat.defaultWimFontSize": "Tamaño predeterminado de WIM",
  "themeBuilder.chat.defaultWimTextColor": "Color predeterminado del texto de WIM",
  "themeBuilder.chat.defaultWimEmphasis": "Énfasis predeterminado de WIM",
  "themeBuilder.chat.defaultWimBold": "Negrita predeterminada de WIM",
  "themeBuilder.chat.defaultWimItalic": "Cursiva predeterminada de WIM",
  "themeBuilder.chat.defaultWimUnderline": "Subrayado predeterminado de WIM",
  "themeBuilder.chat.defaultLiveFont": "Fuente predeterminada del chat WTF LIVE",
  "themeBuilder.chat.defaultLiveFontSize": "Tamaño predeterminado del chat WTF LIVE",
  "themeBuilder.chat.defaultLiveColor": "Color predeterminado del chat WTF LIVE",
  "themeBuilder.chat.defaultLiveColorChoice": "Color predeterminado del chat WTF LIVE: {color}",
  "themeBuilder.chat.defaultLiveEmphasis": "Énfasis predeterminado de WTF LIVE",
  "themeBuilder.chat.defaultLiveBold": "Negrita predeterminada de WTF LIVE",
  "themeBuilder.chat.defaultLiveItalic": "Cursiva predeterminada de WTF LIVE",
  "themeBuilder.field.physics": "Física del escritorio",
  "themeBuilder.field.gravity": "Gravedad",
  "themeBuilder.action.resetIcons": "Restablecer iconos",
  "themeBuilder.section.pet": "Mascota",
  "themeBuilder.field.petEnabled": "Mascota de escritorio",
  "themeBuilder.action.savePet": "Guardar mascota",
  "themeBuilder.pet.name": "Nombre",
  "themeBuilder.pet.coat": "Pelaje",
  "themeBuilder.pet.progress": "Nv {level} · {xp} XP · {care} cuidados",
  "themeBuilder.pet.action.adopt": "Adoptar",
  "themeBuilder.pet.action.feed": "Alimentar",
  "themeBuilder.pet.action.water": "Dar agua",
  "themeBuilder.pet.action.play": "Jugar",
  "themeBuilder.pet.action.pet": "Acariciar",
  "themeBuilder.pet.action.clean": "Limpiar",
  "themeBuilder.pet.action.scoop": "Recoger",
  "themeBuilder.pet.action.nap": "Siesta",
  "themeBuilder.pet.stat.food": "Comida",
  "themeBuilder.pet.stat.water": "Agua",
  "themeBuilder.pet.stat.fun": "Diversión",
  "themeBuilder.pet.stat.clean": "Limpieza",
  "themeBuilder.pet.stat.energy": "Energía",
  "themeBuilder.pet.stat.happyIndex": "Índice feliz",
  "themeBuilder.pet.stat.trauma": "Trauma",
  "themeBuilder.pet.geneLine": "Gen {generation} · Vínculo Nv {bondLevel} · {rarity} · {size}",
  "themeBuilder.pet.noRareTraits": "Sin rasgos raros",
  "themeBuilder.pet.gene.metabolism": "Metabolismo",
  "themeBuilder.pet.gene.speed": "Velocidad",
  "themeBuilder.pet.gene.strength": "Fuerza",
  "themeBuilder.pet.gene.intelligence": "Ingenio",
  "themeBuilder.pet.gene.stamina": "Resistencia",
  "themeBuilder.pet.gene.sociability": "Social",
  "themeBuilder.pet.gene.grit": "Temple",
  "themeBuilder.pet.gene.luck": "Suerte",
  "themeBuilder.section.agent": "Vinculación de agente",
  "themeBuilder.field.mcpEndpoint": "Endpoint MCP",
  "themeBuilder.field.tokenName": "Nombre del token",
  "themeBuilder.action.generateToken": "Generar token",
  "themeBuilder.field.newToken": "Token nuevo",
  "themeBuilder.action.copy": "Copiar",
  "themeBuilder.agents.loading": "Cargando agentes vinculados...",
  "themeBuilder.agents.empty": "No hay agentes vinculados activos.",
  "themeBuilder.agents.created": "{prefix}... · creado el {date}",
  "themeBuilder.agents.lastUsed": " · último uso {date}",
  "themeBuilder.action.revoke": "Revocar",
  "route.missionControl.title": "Control de misión",
  "route.recovery.title": "Modo de recuperación",
  "route.fileManager.title": "Gestor de archivos",
  "route.settings.title": "Ajustes",
  "route.browserBoundaries.title": "Límites del navegador",
  "route.backup.title": "Gestor de copias",
  "route.dashboard.title": "Panel",
  "route.rounds.title": "Rondas",
  "route.challenges.title": "Desafíos",
  "route.sideQuests.title": "Misiones secundarias",
  "route.notifications.title": "Centro de notificaciones",
  "route.diary.title": "Querido diario",
  "route.market.title": "Mercado en cadena",
  "route.ratRace.title": "Carrera de ratas",
  "route.tradeBoards.title": "Tableros de intercambio",
  "route.themeBuilder.title": "Constructor de temas",
  "route.systemAppearance.title": "Apariencia del sistema",
  "route.admin.title": "Panel de administración",
  "route.myVideos.title": "Mis videos",
  "route.myPhotos.title": "Mis fotos",
  "route.myMusic.title": "Mi música",
  "route.ipfs.title": "Gestor de fijación IPFS",
  "route.leaderboard.title": "Clasificación",
  "route.myGallery.title": "Mi galería",
  "route.tezosIntel.title": "Intel Tezos",
  "route.domains.title": "Dominios WTF",
  "route.mintPortal.title": "Portal de mint",
  "route.contractFactory.title": "Fábrica de contratos",
  "route.operatorWallet.title": "Billetera de operador",
  "route.controlBoard.title": "Panel de control",
  "route.live.title": "WTF LIVE",
  "route.crp.title": "Nominaciones CRP",
  "route.mail.title": "Correo WTF",
  "route.taskManager.title": "Gestor de tareas",
} as const satisfies MessageCatalog;

export const arCatalog = {
  ...enUSCatalog,
  "common.open": "فتح",
  "common.close": "إغلاق",
  "common.retry": "إعادة المحاولة",
  "common.save": "حفظ",
  "common.loadingCli": "جار تحميل واجهة wtfOS النصية...",
  "common.noCommands": "لا توجد أوامر",
  "appWindow.crashedTitle": "{title} - تعطل",
  "appWindow.disabledTitle": "{title} - معطل",
  "appWindow.renderErrorTitle": "حدث خطأ في عرض هذا التطبيق.",
  "appWindow.renderErrorBody":
    "بقية WTF OS ما زالت تعمل. يمكنك إعادة محاولة هذه النافذة أو إغلاقها ومتابعة العمل.",
  "appWindow.adminSettings": "إعدادات إدارة {label}",
  "appWindow.minimize": "تصغير {title}",
  "appWindow.maximize": "تكبير {title}",
  "appWindow.restore": "استعادة {title}",
  "appWindow.close": "إغلاق {title}",
  "startMenu.searchLabel": "البحث في الأدوات",
  "startMenu.searchPlaceholder": "ابحث في الأدوات...",
  "startMenu.emptyUser": "لا توجد نتائج. جرّب المهمة أو المحفظة أو اليوميات أو الوسائط أو الإدارة.",
  "startMenu.emptyGuest": "لا توجد نتائج هنا. سجّل الدخول لأدوات الحساب واليوميات والمحفظة والإدارة.",
  "startMenu.logout": "تسجيل الخروج",
  "startMenu.login": "تسجيل الدخول",
  "startMenu.hint": "اكتب للتصفية. انقر بزر الماوس الأيمن أو Shift-نقر لاختصارات التطبيقات.",
  "startMenu.context.open": "فتح",
  "startMenu.context.createShortcut": "إنشاء اختصار سطح المكتب",
  "startMenu.group.apps": "التطبيقات",
  "startMenu.group.gameshow": "المسابقة",
  "startMenu.group.create": "إنشاء!",
  "startMenu.group.social": "اجتماعي",
  "startMenu.group.onChain": "على السلسلة",
  "startMenu.group.gaming": "الألعاب",
  "startMenu.group.myMedia": "وسائطي",
  "startMenu.group.browse": "تصفح",
  "startMenu.group.account": "الحساب",
  "startMenu.group.settings": "الإعدادات",
  "startMenu.group.admin": "الإدارة",
  "commandPalette.title": "لوحة الأوامر",
  "commandPalette.searchLabel": "البحث في الأوامر",
  "commandPalette.placeholder": "أمر",
  "commandPalette.category.wallet": "المحفظة",
  "commandPalette.category.reward": "مكافأة",
  "commandPalette.category.media": "وسائط",
  "commandPalette.category.system": "النظام",
  "commandPalette.category.admin": "إدارة",
  "commandPalette.category.app": "تطبيق",
  "commandPalette.category.route": "مسار",
  "taskbar.start": "الأشياء",
  "taskbar.openStart": "فتح قائمة الأشياء",
  "taskbar.context.restore": "استعادة",
  "taskbar.context.focus": "تركيز",
  "taskbar.context.minimize": "تصغير",
  "taskbar.context.close": "إغلاق",
  "taskbar.showDesktop": "إظهار سطح المكتب",
  "taskbar.restoreWindows": "استعادة النوافذ",
  "taskbar.petCare": "رعاية الحيوان الأليف",
  "taskbar.weather": "طقس سطح المكتب",
  "taskbar.wallet": "المحفظة",
  "taskbar.walletConnected": "متصل",
  "taskbar.walletDisconnect": "فصل المحفظة",
  "taskbar.walletNoConnection": "لا توجد محفظة متصلة",
  "taskbar.walletConnecting": "جار الاتصال...",
  "taskbar.walletConnect": "ربط المحفظة",
  "systemSettings.title": "الإعدادات",
  "systemSettings.status.role": "الدور",
  "systemSettings.status.visible": "مرئي",
  "systemSettings.status.admin": "إدارة",
  "systemSettings.status.mode": "الوضع",
  "systemSettings.admin.enabled": "مفعّل",
  "systemSettings.admin.hidden": "مخفي",
  "systemSettings.panel.system": "إعدادات النظام",
  "systemSettings.panel.interface": "الواجهة",
  "systemSettings.panel.language": "اللغة والمنطقة",
  "systemSettings.panel.boundary": "الحدود",
  "systemSettings.language.title": "اختر لغتك",
  "systemSettings.language.detail":
    "يتغير النص المملوك للنظام في واجهة نظام التشغيل. تبقى منشورات المستخدمين والدردشات وأسماء المشاريع وبيانات الرموز ونصوص الملفات كما كُتبت.",
  "systemSettings.language.label": "لغة العرض",
  "systemSettings.language.regionLabel": "المنطقة",
  "systemSettings.language.pending": "جار حفظ تفضيل اللغة...",
  "systemSettings.language.saved": "تم حفظ تفضيل اللغة.",
  "systemSettings.openSetting": "فتح {label}",
  "systemSettings.interface.title": "اختر واجهة wtfOS",
  "systemSettings.interface.detail":
    "سطح المكتب هو تجربة النوافذ الافتراضية. CLI واجهة أوامر آمنة بملء الشاشة وتستخدم النواة نفسها مثل Terminal.",
  "systemSettings.interface.desktop": "استخدم سطح المكتب",
  "systemSettings.interface.cli": "استخدم CLI",
  "systemSettings.boundary.title": "تبقى ملكية الإعدادات داخل كل تطبيق",
  "systemSettings.boundary.detail":
    "هذا المركز يوجّه إلى واجهات التطبيقات الموجودة ولا يتجاوز الأذونات أو فحوصات المحفظة أو قواعد CSRF أو بوابات الإدارة.",
  "systemSettings.boundary.openMissionControl": "فتح Mission Control",
  "themeBuilder.title": "منشئ السمات",
  "themeBuilder.section.appearance": "مظهر النظام",
  "themeBuilder.section.typography": "خطوط النظام",
  "themeBuilder.typography.help": "تُطبّق حزم الخطوط فورًا على واجهة سطح المكتب ونوافذ التطبيقات.",
  "themeBuilder.section.chatDefaults": "إعدادات الدردشة",
  "themeBuilder.chatDefaults.help":
    "تضبط هذه القوالب رسائل WIM ودردشة غرف WTF LIVE مع بقاء كل محرر داخل نافذة الخط والحجم الخاصة به.",
  "themeBuilder.section.colorSchemes": "مخططات الألوان",
  "themeBuilder.section.desktop": "سطح المكتب",
  "themeBuilder.field.backgroundUrl": "رابط صورة الخلفية",
  "themeBuilder.action.uploadBackground": "رفع صورة خلفية",
  "themeBuilder.action.upload": "رفع",
  "themeBuilder.action.clear": "مسح",
  "themeBuilder.field.fit": "الملاءمة",
  "themeBuilder.field.backgroundFit": "ملاءمة صورة الخلفية",
  "themeBuilder.upload.help": "تستخدم عمليات الرفع مكتبة الوسائط وتقبل صورًا حتى {size}.",
  "themeBuilder.upload.pending": " جار الرفع...",
  "themeBuilder.upload.imagesOnly": "ملفات الصور فقط.",
  "themeBuilder.upload.tooLarge": "اختر صورة أصغر من {size}.",
  "themeBuilder.upload.failed": "فشل الرفع.",
  "themeBuilder.section.savedImages": "الصور المحفوظة",
  "themeBuilder.savedImages.loading": "جار تحميل الوسائط المحفوظة...",
  "themeBuilder.savedImages.error": "تعذر تحميل الوسائط المحفوظة.",
  "themeBuilder.savedImages.empty": "لا توجد وسائط صور محفوظة بعد.",
  "themeBuilder.section.tokenArt": "صور الرموز المملوكة",
  "themeBuilder.tokenArt.loading": "جار تحميل صور المحفظة...",
  "themeBuilder.tokenArt.error": "تعذر تحميل صور المحفظة.",
  "themeBuilder.tokenArt.empty": "لم يتم العثور على رموز صور في محافظك المتزامنة.",
  "themeBuilder.section.cursor": "المؤشر",
  "themeBuilder.section.physics": "الفيزياء",
  "themeBuilder.color.desktop": "سطح المكتب",
  "themeBuilder.color.window": "النافذة",
  "themeBuilder.color.activeFrame": "الإطار النشط",
  "themeBuilder.color.inactiveFrame": "الإطار غير النشط",
  "themeBuilder.color.text": "النص",
  "themeBuilder.color.highlight": "التمييز",
  "themeBuilder.colorInput": "لون {label}",
  "themeBuilder.field.font": "الخط",
  "themeBuilder.field.size": "الحجم",
  "themeBuilder.field.color": "اللون",
  "themeBuilder.chat.wimMessages": "رسائل WIM",
  "themeBuilder.chat.liveRoomChat": "دردشة غرفة WTF LIVE",
  "themeBuilder.chat.defaultWimFont": "خط WIM الافتراضي",
  "themeBuilder.chat.defaultWimFontSize": "حجم خط WIM الافتراضي",
  "themeBuilder.chat.defaultWimTextColor": "لون نص WIM الافتراضي",
  "themeBuilder.chat.defaultWimEmphasis": "تنسيق WIM الافتراضي",
  "themeBuilder.chat.defaultWimBold": "WIM غامق افتراضي",
  "themeBuilder.chat.defaultWimItalic": "WIM مائل افتراضي",
  "themeBuilder.chat.defaultWimUnderline": "WIM مسطر افتراضي",
  "themeBuilder.chat.defaultLiveFont": "خط دردشة WTF LIVE الافتراضي",
  "themeBuilder.chat.defaultLiveFontSize": "حجم دردشة WTF LIVE الافتراضي",
  "themeBuilder.chat.defaultLiveColor": "لون دردشة WTF LIVE الافتراضي",
  "themeBuilder.chat.defaultLiveColorChoice": "لون دردشة WTF LIVE الافتراضي {color}",
  "themeBuilder.chat.defaultLiveEmphasis": "تنسيق WTF LIVE الافتراضي",
  "themeBuilder.chat.defaultLiveBold": "WTF LIVE غامق افتراضي",
  "themeBuilder.chat.defaultLiveItalic": "WTF LIVE مائل افتراضي",
  "themeBuilder.field.physics": "فيزياء سطح المكتب",
  "themeBuilder.field.gravity": "الجاذبية",
  "themeBuilder.action.resetIcons": "إعادة ضبط الأيقونات",
  "themeBuilder.section.pet": "الحيوان الأليف",
  "themeBuilder.field.petEnabled": "حيوان أليف على سطح المكتب",
  "themeBuilder.action.savePet": "حفظ الحيوان الأليف",
  "themeBuilder.pet.name": "الاسم",
  "themeBuilder.pet.coat": "الفرو",
  "themeBuilder.pet.progress": "مستوى {level} · {xp} XP · رعاية {care}",
  "themeBuilder.pet.action.adopt": "تبنّي",
  "themeBuilder.pet.action.feed": "إطعام",
  "themeBuilder.pet.action.water": "ماء",
  "themeBuilder.pet.action.play": "لعب",
  "themeBuilder.pet.action.pet": "مداعبة",
  "themeBuilder.pet.action.clean": "تنظيف",
  "themeBuilder.pet.action.scoop": "تنظيف الفضلات",
  "themeBuilder.pet.action.nap": "قيلولة",
  "themeBuilder.pet.stat.food": "طعام",
  "themeBuilder.pet.stat.water": "ماء",
  "themeBuilder.pet.stat.fun": "مرح",
  "themeBuilder.pet.stat.clean": "نظافة",
  "themeBuilder.pet.stat.energy": "طاقة",
  "themeBuilder.pet.stat.happyIndex": "مؤشر السعادة",
  "themeBuilder.pet.stat.trauma": "صدمة",
  "themeBuilder.pet.geneLine": "جيل {generation} · رابطة م{bondLevel} · {rarity} · {size}",
  "themeBuilder.pet.noRareTraits": "لا توجد سمات نادرة",
  "themeBuilder.pet.gene.metabolism": "الأيض",
  "themeBuilder.pet.gene.speed": "السرعة",
  "themeBuilder.pet.gene.strength": "القوة",
  "themeBuilder.pet.gene.intelligence": "الذكاء",
  "themeBuilder.pet.gene.stamina": "التحمل",
  "themeBuilder.pet.gene.sociability": "اجتماعي",
  "themeBuilder.pet.gene.grit": "العزيمة",
  "themeBuilder.pet.gene.luck": "الحظ",
  "themeBuilder.section.agent": "ربط الوكيل",
  "themeBuilder.field.mcpEndpoint": "نقطة MCP",
  "themeBuilder.field.tokenName": "اسم الرمز",
  "themeBuilder.action.generateToken": "إنشاء رمز",
  "themeBuilder.field.newToken": "رمز جديد",
  "themeBuilder.action.copy": "نسخ",
  "themeBuilder.agents.loading": "جار تحميل الوكلاء المرتبطين...",
  "themeBuilder.agents.empty": "لا يوجد وكلاء مرتبطون نشطون.",
  "themeBuilder.agents.created": "{prefix}... · أُنشئ في {date}",
  "themeBuilder.agents.lastUsed": " · آخر استخدام {date}",
  "themeBuilder.action.revoke": "إبطال",
  "route.settings.title": "الإعدادات",
  "route.themeBuilder.title": "منشئ السمات",
  "route.systemAppearance.title": "مظهر النظام",
  "route.missionControl.title": "Mission Control",
  "route.recovery.title": "وضع الاسترداد",
  "route.fileManager.title": "مدير الملفات",
  "route.dashboard.title": "لوحة المعلومات",
} as const satisfies MessageCatalog;

export const pseudoCatalog = Object.fromEntries(
  Object.entries(enUSCatalog).map(([key, value]) => [key, pseudoValue(value)])
) as MessageCatalog;

export const catalogs = {
  "en-US": enUSCatalog,
  "es-ES": esESCatalog,
  ar: arCatalog,
  "en-XA": pseudoCatalog,
} as const satisfies Record<string, MessageCatalog>;
