export type AdminRiskLevel = "read-only" | "controlled-write" | "sensitive" | "irreversible";

export type AdminSectionCatalogEntry = {
  value: number;
  slug: string;
  title: string;
  label: string;
  description: string;
  group: string;
  accent: string;
  keywords: string[];
  tasks: string[];
  inspect: string[];
  change: string[];
  risk: AdminRiskLevel;
  permissionKeys: string[];
  apiRoutes: string[];
  automationHandles: string[];
};

export const ADMIN_SECTION_CATALOG_VERSION = "2026-07-15.1";

export const ADMIN_SECTION_CATALOG: AdminSectionCatalogEntry[] = [
  {
    value: 20,
    slug: "overview",
    title: "Overview",
    label: "Start Here",
    description: "Task routing and live inventory",
    group: "Command",
    accent: "#67e8f9",
    keywords: ["home", "start", "dashboard", "triage", "where do i go", "operator"],
    tasks: ["Route a complaint to the right admin tool", "Review current platform inventory", "Find common operator workflows"],
    inspect: ["Live entity counts", "Admin suite task map", "Common resolution paths"],
    change: [],
    risk: "read-only",
    permissionKeys: ["access_admin_panel"],
    apiRoutes: ["GET /api/admin/stats"],
    automationHandles: ["admin.overview.viewed"],
  },
  {
    value: 0,
    slug: "users",
    title: "Users",
    label: "Users",
    description: "Role review and WTF Passports",
    group: "Identity & Access",
    accent: "#86efac",
    keywords: ["account", "passport", "login", "username", "email", "xp", "exp", "wallet", "social", "password", "complaint"],
    tasks: ["Compare every user’s highest role and level", "Open a user’s WTF Passport", "Resolve identity, access, settings, wallet, social, or recovery complaints"],
    inspect: ["Identity and account health", "Assigned roles and curses", "Effective permissions and wtfOS access", "Desktop settings", "Wallets, domains, and recent EXP"],
    change: ["Identity", "Roles", "Curses", "EXP", "Desktop settings", "Social connections", "Temporary password", "Account deletion"],
    risk: "sensitive",
    permissionKeys: ["manage_users", "award_xp"],
    apiRoutes: ["GET /api/admin/users", "GET /api/admin/users/:id/passport", "PUT /api/admin/users/:id/passport/desktop-settings"],
    automationHandles: ["admin.user.passport.viewed", "admin.user.desktop_settings.updated"],
  },
  {
    value: 11,
    slug: "roles",
    title: "Roles",
    label: "Roles",
    description: "Levels, permissions, surfaces, users",
    group: "Identity & Access",
    accent: "#facc15",
    keywords: ["role", "level", "permission", "access", "visibility", "app", "route", "surface", "assigned users"],
    tasks: ["Compare role levels and assigned users", "Design a role", "Grant permissions", "Control wtfOS surfaces and routes"],
    inspect: ["Role catalog", "Assigned users", "Permission matrix", "Surface, route, native setting, and automation access"],
    change: ["Role metadata and level", "Permission grants", "Surface access overrides"],
    risk: "sensitive",
    permissionKeys: ["manage_roles"],
    apiRoutes: ["GET /api/admin/roles", "GET /api/admin/permissions", "GET /api/admin/role-access"],
    automationHandles: ["admin.role.updated", "admin.role_access.updated"],
  },
  {
    value: 21,
    slug: "curses",
    title: "Curses",
    label: "Curses",
    description: "Effects and user assignments",
    group: "Identity & Access",
    accent: "#fb7185",
    keywords: ["curse", "green lens", "click flip", "liability waiver", "reward embargo", "blangs", "user effect"],
    tasks: ["Compare curse assignment counts", "Find affected users", "Apply or lift a specific curse"],
    inspect: ["Canonical curse definitions", "User-visible effects", "Assignment reasons and timestamps", "Affected users"],
    change: ["User curse assignments"],
    risk: "sensitive",
    permissionKeys: ["manage_users"],
    apiRoutes: ["PUT /api/admin/users/:id/curses/:curseKey"],
    automationHandles: ["admin.user.curse.updated"],
  },
  {
    value: 17,
    slug: "os-surfaces",
    title: "OS Admin",
    label: "OS Surfaces",
    description: "Registry, native controls, agent handles",
    group: "Identity & Access",
    accent: "#38bdf8",
    keywords: ["wtfos", "surface", "registry", "native adm", "route", "automation", "desktop item"],
    tasks: ["Audit every registered wtfOS surface", "Find native ADM controls", "Inspect automation and route ownership"],
    inspect: ["Surface registry", "Native settings", "Routes", "Desktop apps", "Automation handles"],
    change: ["Role surface access", "Linked desktop app posture"],
    risk: "sensitive",
    permissionKeys: ["manage_roles", "manage_desktop_apps"],
    apiRoutes: ["GET /api/admin/role-access", "GET /api/admin/apps/desktop"],
    automationHandles: ["admin.role_access.updated"],
  },
  {
    value: 9,
    slug: "desktop-apps",
    title: "Desktop and Start Menu Apps",
    label: "App Gates",
    description: "Launchers, docs, install keys",
    group: "Identity & Access",
    accent: "#fda4af",
    keywords: ["desktop app", "start menu", "launcher", "visibility", "install", "docs", "gate"],
    tasks: ["Find an app’s launch gate", "Change desktop or Start Menu visibility", "Review install and documentation posture"],
    inspect: ["Desktop app catalog", "Availability and documentation state", "Install keys"],
    change: ["Desktop app visibility and gate metadata"],
    risk: "controlled-write",
    permissionKeys: ["manage_desktop_apps"],
    apiRoutes: ["GET /api/admin/apps/desktop", "PUT /api/admin/apps/desktop/:appKey"],
    automationHandles: ["admin.desktop_app.updated"],
  },
  {
    value: 1,
    slug: "seasons",
    title: "Seasons",
    label: "Seasons",
    description: "Season structure",
    group: "Gameshow Ops",
    accent: "#fda4af",
    keywords: ["season", "structure", "schedule", "media", "status"],
    tasks: ["Create or edit a season", "Review season status and media", "Delete obsolete season records"],
    inspect: ["Season number, status, description, and media"],
    change: ["Season records"],
    risk: "controlled-write",
    permissionKeys: ["manage_seasons"],
    apiRoutes: ["GET /api/seasons", "POST /api/seasons", "PUT /api/seasons/:id", "DELETE /api/seasons/:id"],
    automationHandles: ["gameshow.season.updated"],
  },
  {
    value: 2,
    slug: "rounds",
    title: "Rounds",
    label: "Rounds",
    description: "Rounds and active windows",
    group: "Gameshow Ops",
    accent: "#fdba74",
    keywords: ["round", "window", "calendar", "contestant", "active", "start", "end"],
    tasks: ["Create or edit a round", "Correct active windows", "Review season ownership"],
    inspect: ["Round timing, status, season, rules, and contestants"],
    change: ["Round records and windows"],
    risk: "controlled-write",
    permissionKeys: ["manage_seasons", "manage_gameshow"],
    apiRoutes: ["GET /api/rounds", "POST /api/rounds", "PUT /api/rounds/:id", "DELETE /api/rounds/:id"],
    automationHandles: ["gameshow.round.joined"],
  },
  {
    value: 3,
    slug: "challenges",
    title: "Challenges",
    label: "Tasks",
    description: "Challenges, submissions, grading",
    group: "Gameshow Ops",
    accent: "#a7f3d0",
    keywords: ["challenge", "task", "submission", "grade", "condition", "reward", "trigger"],
    tasks: ["Build a challenge", "Inspect submissions", "Grade work and record rewards"],
    inspect: ["Challenge rules, conditions, submissions, grading, and reward state"],
    change: ["Challenge definitions", "Grades", "Submission reward state"],
    risk: "controlled-write",
    permissionKeys: ["manage_challenges"],
    apiRoutes: ["GET /api/challenges", "POST /api/challenges", "PUT /api/challenges/:id"],
    automationHandles: ["challenge.completed", "challenge.graded"],
  },
  {
    value: 4,
    slug: "side-quests",
    title: "Side Quests",
    label: "Quests",
    description: "Daily and social quests",
    group: "Gameshow Ops",
    accent: "#fde68a",
    keywords: ["side quest", "quest", "daily", "social", "completion", "approve"],
    tasks: ["Create or edit a quest", "Review user completions", "Approve completion evidence"],
    inspect: ["Quest cadence, verifier, reward, and completion records"],
    change: ["Quest definitions", "Completion approval"],
    risk: "controlled-write",
    permissionKeys: ["manage_side_quests"],
    apiRoutes: ["GET /api/side-quests", "POST /api/side-quests", "PUT /api/side-quests/:id"],
    automationHandles: ["side_quest.completed"],
  },
  {
    value: 18,
    slug: "automation",
    title: "Automation",
    label: "Automation",
    description: "Triggers, conditions, rewards",
    group: "Gameshow Ops",
    accent: "#c4b5fd",
    keywords: ["automation", "trigger", "condition", "reward action", "system event", "handle", "agent"],
    tasks: ["Find an event trigger", "Build condition and reward actions", "Audit normalized handles"],
    inspect: ["Trigger catalog", "Conditions", "Reward actions", "System event handles"],
    change: ["Challenge automation definitions"],
    risk: "sensitive",
    permissionKeys: ["manage_challenges", "manage_rewards"],
    apiRoutes: ["GET /api/admin/challenge-automation"],
    automationHandles: ["app.interaction.tracked", "xp.awarded", "wtf.awarded"],
  },
  {
    value: 8,
    slug: "rewards",
    title: "Rewards",
    label: "Rewards",
    description: "Ledger and payout settlement",
    group: "Economy",
    accent: "#bbf7d0",
    keywords: ["reward", "payout", "ledger", "paid", "unpaid", "operation hash", "op hash"],
    tasks: ["Find unpaid rewards", "Mark a payout settled", "Batch-settle ledger entries"],
    inspect: ["Reward recipient, amount, source, payout, and operation hash"],
    change: ["Reward payment state"],
    risk: "irreversible",
    permissionKeys: ["manage_rewards"],
    apiRoutes: ["GET /api/admin/reward-ledger", "PUT /api/admin/reward-ledger/:id/pay"],
    automationHandles: ["wtf.awarded", "admin.reward.paid"],
  },
  {
    value: 7,
    slug: "xp-log",
    title: "XP Log",
    label: "EXP",
    description: "Experience audit trail",
    group: "Economy",
    accent: "#bae6fd",
    keywords: ["xp", "exp", "experience", "award", "reason", "audit", "tier"],
    tasks: ["Audit EXP changes", "Find the source of a tier complaint", "Review manual adjustments"],
    inspect: ["EXP event amount, reason, user, operator, and timestamp"],
    change: [],
    risk: "read-only",
    permissionKeys: ["award_xp"],
    apiRoutes: ["GET /api/admin/xp/events"],
    automationHandles: ["xp.awarded"],
  },
  {
    value: 10,
    slug: "contract-ledger",
    title: "Contract Ledger",
    label: "Ledger",
    description: "On-chain activity and failures",
    group: "Economy",
    accent: "#fecaca",
    keywords: ["contract", "ledger", "transaction", "operation", "wallet", "chain", "failure", "op hash"],
    tasks: ["Find a failed contract operation", "Search by wallet or operation hash", "Review execution attempts"],
    inspect: ["Contract action, status, wallet, chain, operation hash, and error"],
    change: [],
    risk: "read-only",
    permissionKeys: ["view_contract_ledger"],
    apiRoutes: ["GET /api/admin/contract-activity"],
    automationHandles: ["contract.execution.attempted", "contract.execution.failed"],
  },
  {
    value: 15,
    slug: "in-app-market",
    title: "In-App Market",
    label: "Market",
    description: "Catalog, sales, stock, pricing",
    group: "Economy",
    accent: "#bef264",
    keywords: ["market", "item", "sku", "price", "sale", "stock", "catalog", "reprice"],
    tasks: ["Find a market item", "Correct price or stock", "Create and manage sales"],
    inspect: ["Catalog metadata, pricing drift, stock, sales, and chain listing"],
    change: ["Market items", "Pricing", "Stock", "Sales"],
    risk: "sensitive",
    permissionKeys: ["manage_settings"],
    apiRoutes: ["GET /api/admin/in-app-market/items", "PATCH /api/admin/in-app-market/items/:id"],
    automationHandles: ["market.item.updated"],
  },
  {
    value: 14,
    slug: "wtf-domains",
    title: "WTF Tez",
    label: "Domains",
    description: "Subdomain grants and registrar state",
    group: "Platform Apps",
    accent: "#93c5fd",
    keywords: ["domain", "subdomain", "tez", "dns", "registrar", "grant", "wallet"],
    tasks: ["Find a user’s WTF domain", "Grant a subdomain", "Correct registrar or grant status"],
    inspect: ["Grant owner, label, wallet, status, notes, and registrar readiness"],
    change: ["Subdomain grants and status"],
    risk: "sensitive",
    permissionKeys: ["manage_users"],
    apiRoutes: ["GET /api/admin/wtf-subdomains", "POST /api/admin/users/:id/wtf-subdomains"],
    automationHandles: ["wtf_subdomain.granted"],
  },
  {
    value: 12,
    slug: "wtf-tv",
    title: "WTF TV",
    label: "TV",
    description: "Channels, sources, programming",
    group: "Platform Apps",
    accent: "#f0abfc",
    keywords: ["tv", "channel", "playlist", "source", "bumper", "refresh", "programming"],
    tasks: ["Correct global TV source mode", "Refresh programming", "Manage bumpers and playlist limits"],
    inspect: ["TV source, selected users or wallets, playlist, bumper, and refresh configuration"],
    change: ["Global WTF TV configuration"],
    risk: "sensitive",
    permissionKeys: ["manage_tv"],
    apiRoutes: ["GET /api/admin/wtf-tv", "PUT /api/admin/wtf-tv"],
    automationHandles: ["wtf_tv.config.updated"],
  },
  {
    value: 13,
    slug: "studio",
    title: "Studio",
    label: "Studio",
    description: "Drive storage and operator connection",
    group: "Platform Apps",
    accent: "#5eead4",
    keywords: ["studio", "drive", "storage", "quota", "root folder", "disconnect", "google"],
    tasks: ["Check Drive connection", "Refresh storage quota", "Correct root folder or reconnect"],
    inspect: ["Operator Drive connection, quota, account, and root folder"],
    change: ["Drive authorization and root folder"],
    risk: "sensitive",
    permissionKeys: ["manage_studio"],
    apiRoutes: ["GET /api/studio/admin/drive/status", "POST /api/studio/admin/drive/start"],
    automationHandles: ["studio.drive.updated"],
  },
  {
    value: 16,
    slug: "arcade",
    title: "Arcade",
    label: "Arcade",
    description: "Games, moderation, reports, credits",
    group: "Platform Apps",
    accent: "#fdba74",
    keywords: ["arcade", "console", "game", "moderation", "report", "credit", "approve", "reject"],
    tasks: ["Moderate a submitted game", "Resolve reports", "Correct arcade credit rules", "Audit operator actions"],
    inspect: ["Games, versions, reports, moderation state, credits, and audit events"],
    change: ["Game moderation", "Report resolution", "Credit rules", "Source imports"],
    risk: "sensitive",
    permissionKeys: ["manage_settings"],
    apiRoutes: ["GET /api/arcade/admin/games", "GET /api/arcade/admin/reports", "GET /api/arcade/admin/audit"],
    automationHandles: ["arcade.game.moderated", "arcade.report.resolved"],
  },
  {
    value: 19,
    slug: "w-digest",
    title: "W Digest",
    label: "W Digest",
    description: "Digest handles and publication flow",
    group: "Platform Apps",
    accent: "#d8b4fe",
    keywords: ["w digest", "digest", "handle", "publication", "feed"],
    tasks: ["Audit digest handles", "Find publication integration state"],
    inspect: ["Digest event and automation handles"],
    change: [],
    risk: "read-only",
    permissionKeys: ["manage_content"],
    apiRoutes: [],
    automationHandles: ["digest.viewed"],
  },
  {
    value: 5,
    slug: "board",
    title: "Board",
    label: "Board",
    description: "Threads, locks, pins, moderation",
    group: "Content",
    accent: "#f9a8d4",
    keywords: ["board", "thread", "post", "pin", "lock", "expire", "moderation", "delete"],
    tasks: ["Find a reported thread", "Pin, lock, expire, or restore a thread", "Remove abusive content"],
    inspect: ["Thread author, replies, status, and moderation signals"],
    change: ["Thread moderation state", "Thread deletion"],
    risk: "sensitive",
    permissionKeys: ["pin_threads", "lock_threads", "delete_any_post"],
    apiRoutes: ["GET /api/messages/threads", "PATCH /api/admin/message-board/threads/:id"],
    automationHandles: ["board.thread.moderated"],
  },
  {
    value: 6,
    slug: "content",
    title: "Content",
    label: "Content",
    description: "Links and FAQ",
    group: "Content",
    accent: "#cbd5e1",
    keywords: ["content", "link", "faq", "question", "answer", "url", "category"],
    tasks: ["Create or correct a resource link", "Create or correct FAQ guidance", "Manage display order"],
    inspect: ["Links, URLs, FAQ answers, categories, and display order"],
    change: ["Link and FAQ records"],
    risk: "controlled-write",
    permissionKeys: ["manage_content"],
    apiRoutes: ["GET /api/links", "GET /api/faq"],
    automationHandles: ["content.updated"],
  },
  {
    value: 22,
    slug: "help",
    title: "Admin Help",
    label: "Help Index",
    description: "Search every surface and control",
    group: "Support",
    accent: "#a5b4fc",
    keywords: ["help", "search", "index", "guide", "agent", "api", "where", "how"],
    tasks: ["Describe an issue in plain language", "Find the exact admin destination", "Inspect stable agent handles and API routes"],
    inspect: ["Every central section, registered surface, permission, curse, route, setting, and automation handle"],
    change: [],
    risk: "read-only",
    permissionKeys: ["access_admin_panel"],
    apiRoutes: ["GET /api/admin/help-index"],
    automationHandles: ["admin.help.searched", "admin.help.topic.opened"],
  },
];

export function findAdminSectionByValue(value: number) {
  return ADMIN_SECTION_CATALOG.find((section) => section.value === value) ?? null;
}

export function findAdminSectionBySlug(slug: string | null | undefined) {
  return ADMIN_SECTION_CATALOG.find((section) => section.slug === slug) ?? null;
}

const ADMIN_PANEL_SECTION_ALIASES: Record<string, string> = {
  "desktop apps": "desktop-apps",
  "media storage": "studio",
  "os admin": "os-surfaces",
  "role control": "roles",
  "system logs": "os-surfaces",
  "wtf tez": "wtf-domains",
  commerce: "in-app-market",
  console: "arcade",
  social: "users",
};

export function findAdminSectionForPanelLabel(label: string | null | undefined) {
  const normalized = String(label ?? "").trim().toLocaleLowerCase();
  const alias = ADMIN_PANEL_SECTION_ALIASES[normalized];
  if (alias) return findAdminSectionBySlug(alias);
  return ADMIN_SECTION_CATALOG.find(
    (section) =>
      section.label.toLocaleLowerCase() === normalized ||
      section.title.toLocaleLowerCase() === normalized
  ) ?? null;
}

export function adminSectionHrefForPanelLabel(label: string | null | undefined) {
  const section = findAdminSectionForPanelLabel(label) ?? findAdminSectionBySlug("help");
  return section ? `/admin?section=${encodeURIComponent(section.slug)}` : "/admin";
}
