import type { LucideIcon } from "lucide-react";
import {
  Activity,
  Archive,
  BadgeCheck,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Box,
  Cable,
  CircuitBoard,
  ClipboardCheck,
  Command,
  Compass,
  Database,
  FileKey,
  Film,
  Fingerprint,
  Flame,
  GalleryHorizontalEnd,
  Gauge,
  GitBranch,
  Globe2,
  Hammer,
  HeartPulse,
  Home,
  KeyRound,
  Layers3,
  LayoutGrid,
  Link2,
  LockKeyhole,
  Map,
  MessageCircle,
  MonitorUp,
  MousePointer2,
  Network,
  Palette,
  PanelsTopLeft,
  Podcast,
  Radio,
  RadioTower,
  ReceiptText,
  Rocket,
  Route,
  Search,
  Send,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Smartphone,
  Store,
  TerminalSquare,
  TimerReset,
  Tv,
  WalletCards,
  Waypoints,
  Wrench,
  Zap,
} from "lucide-react";

export type ConceptFamily = "pro" | "indie" | "mobile" | "ops";
export type ShellMode = "habitat" | "atlas" | "foundry" | "zine" | "station" | "stack" | "pocket" | "lens" | "cards" | "intent" | "recovery" | "runbook";
export type DomainLane = "identity" | "social" | "media" | "chain" | "ops" | "play";

export interface ShellConcept {
  id: string;
  family: ConceptFamily;
  mode: ShellMode;
  name: string;
  shortName: string;
  thesis: string;
  audience: string;
  shellIdea: string;
  whyBetter: string;
  migrationPath: string;
  weirdness: string;
  risk: string;
  primaryAction: string;
  secondaryAction: string;
  accent: string;
  accent2: string;
  surface: string;
  ink: string;
  canvas: string;
  modules: string[];
  flow: string[];
  pitch: string;
}

export interface ShellModule {
  id: string;
  label: string;
  lane: DomainLane;
  status: "ready" | "watch" | "blocked" | "running";
  count: string;
  job: string;
  icon: LucideIcon;
}

export const familyLabels: Record<ConceptFamily, string> = {
  pro: "Pitch-grade systems",
  indie: "Indie web worlds",
  mobile: "Mobile-native shells",
  ops: "Operation-first shells",
};

export const shellConstraints = [
  {
    title: "React is the real binding",
    body: "wtfOS can move beyond React95 as long as the shell remains React-owned and route, state, auth, wallet, and app lifecycle contracts stay explicit.",
  },
  {
    title: "Shell primitives need adapters",
    body: "The future shell should define window, panel, menu, command, dock, sheet, toast, dialog, and status primitives so old React95 screens can migrate gradually.",
  },
  {
    title: "Routes stay governed",
    body: "Any promoted concept must still honor PAGE_DEFS, shared route access, desktop app gates, inventory, behavior assertions, and E2E coverage.",
  },
  {
    title: "Weirdness must be legible",
    body: "The larger habitat can be stranger than React95, but every wallet, publish, admin, recovery, and live action needs plain object and consequence copy.",
  },
  {
    title: "Mobile is not a tiny desktop",
    body: "Phone shells should use decks, sheets, command search, big touch targets, and handoff states instead of draggable desktop windows.",
  },
  {
    title: "Trust states are sacred",
    body: "Mainnet, Shadownet, Tezos L1, Etherlink, wallet account, fee, RPC, pinning, and publishing states need hard visual grammar in every skin.",
  },
  {
    title: "Boot remains light",
    body: "The shell should load fast, then hydrate heavy editors, wallet SDKs, graph canvases, and live rooms only when launched or focused.",
  },
  {
    title: "Old bowl can stay during migration",
    body: "React95 can become a compatibility skin inside the new shell while new apps use modern primitives from day one.",
  },
];

export const shellModules: ShellModule[] = [
  {
    id: "mission",
    label: "Mission",
    lane: "ops",
    status: "ready",
    count: "12",
    job: "Next actions, health, recovery, rewards",
    icon: Gauge,
  },
  {
    id: "intent",
    label: "Intent Command",
    lane: "ops",
    status: "running",
    count: "84",
    job: "Search routes, objects, actions, agents",
    icon: Command,
  },
  {
    id: "identity",
    label: "Identity",
    lane: "identity",
    status: "ready",
    count: "4",
    job: "Profile, handles, domains, proof state",
    icon: Fingerprint,
  },
  {
    id: "skywire",
    label: "Skywire",
    lane: "social",
    status: "watch",
    count: "2",
    job: "AT Protocol, OAuth, signals, vault",
    icon: RadioTower,
  },
  {
    id: "w",
    label: "W Social",
    lane: "social",
    status: "running",
    count: "24",
    job: "Feed, DMs, group chat, digest",
    icon: MessageCircle,
  },
  {
    id: "live",
    label: "WTF LIVE",
    lane: "social",
    status: "watch",
    count: "2",
    job: "Rooms, stage, camera, screen, chat",
    icon: Radio,
  },
  {
    id: "studio",
    label: "Studio",
    lane: "media",
    status: "ready",
    count: "6",
    job: "Projects, annotation, collaboration",
    icon: Palette,
  },
  {
    id: "macaroni",
    label: "Macaroni",
    lane: "media",
    status: "running",
    count: "3",
    job: "Drop setup, mint pages, contracts",
    icon: Box,
  },
  {
    id: "pinning",
    label: "Pinning",
    lane: "media",
    status: "ready",
    count: "97",
    job: "IPFS manifests, PDS pointers, sites",
    icon: Database,
  },
  {
    id: "wallet",
    label: "Wallets",
    lane: "chain",
    status: "watch",
    count: "1",
    job: "Tezos, Etherlink, chain guard, fees",
    icon: WalletCards,
  },
  {
    id: "market",
    label: "Market",
    lane: "chain",
    status: "ready",
    count: "38",
    job: "Listings, swaps, trade boards, dues",
    icon: Store,
  },
  {
    id: "domains",
    label: "Domains",
    lane: "chain",
    status: "ready",
    count: "1",
    job: "username.wtfos.me and wtf.tez",
    icon: Globe2,
  },
  {
    id: "map",
    label: "Map Lab",
    lane: "ops",
    status: "ready",
    count: "42",
    job: "Workflow graph, ports, routes, docs",
    icon: Waypoints,
  },
  {
    id: "arcade",
    label: "Arcade",
    lane: "play",
    status: "ready",
    count: "11",
    job: "Games, console, casino, side quests",
    icon: Sparkles,
  },
  {
    id: "mcp",
    label: "MCP Agents",
    lane: "ops",
    status: "blocked",
    count: "2",
    job: "Scoped tokens, automation, access",
    icon: Bot,
  },
  {
    id: "recovery",
    label: "Recovery",
    lane: "ops",
    status: "ready",
    count: "0",
    job: "Wallet reset, reports, degraded state",
    icon: HeartPulse,
  },
];

export const shellConcepts: ShellConcept[] = [
  {
    id: "protocol-habitat",
    family: "pro",
    mode: "habitat",
    name: "Protocol Habitat",
    shortName: "Habitat",
    thesis: "A serious protocol work environment where apps are living system objects, not isolated novelty windows.",
    audience: "Protocol teams, partner engineers, creator operations",
    shellIdea: "Spatial lanes for identity, social, media, chain, ops, and play. The command spine opens object cards, not random windows.",
    whyBetter: "It scales beyond the desktop metaphor while keeping every wtfOS domain visible as part of one operating habitat.",
    migrationPath: "Wrap current routes in object cards first, then replace React95 chrome per app as new primitives mature.",
    weirdness: "The OS feels like a live map of the platform, with strange names preserved as landmarks and plain task copy attached.",
    risk: "Needs disciplined information architecture or the habitat becomes a decorative map.",
    primaryAction: "Open system object",
    secondaryAction: "Trace dependency",
    accent: "#1b6b73",
    accent2: "#d39a36",
    surface: "#edf2ef",
    ink: "#101b1d",
    canvas: "#d8e2dc",
    modules: ["mission", "identity", "skywire", "studio", "wallet", "domains", "map", "mcp"],
    flow: ["Search intent", "Choose object", "Inspect trust state", "Open focused workspace"],
    pitch: "Best Trilitech-facing concept for showing wtfOS as a protocol operating layer rather than a retro web app.",
  },
  {
    id: "chainroom",
    family: "pro",
    mode: "atlas",
    name: "Chainroom",
    shortName: "Chainroom",
    thesis: "A boardroom-grade operations console for wallet, chain, publishing, and live product readiness.",
    audience: "Executive demos, chain ops, launch control, support leadership",
    shellIdea: "A quiet topographic cockpit: left object rail, center readiness board, right evidence drawer.",
    whyBetter: "It turns scary state into calm proof: account, network, RPC, fee, route, event, and recovery are all first-class.",
    migrationPath: "Start with wallet, Macaroni, domains, IPFS, and admin surfaces where trust clarity matters most.",
    weirdness: "The strangeness is in the system labels and artifacts, not in hiding what a chain action will do.",
    risk: "May feel too corporate if creator and play surfaces do not retain enough texture.",
    primaryAction: "Run readiness check",
    secondaryAction: "Open evidence drawer",
    accent: "#2e5574",
    accent2: "#a95c32",
    surface: "#eef1f4",
    ink: "#101822",
    canvas: "#d9e0e6",
    modules: ["wallet", "macaroni", "pinning", "domains", "market", "admin", "recovery", "mission"],
    flow: ["Select launch", "Review chain state", "Resolve blockers", "Publish with receipt"],
    pitch: "Most sale-ready if the buyer cares about reliability, support load, and mainnet trust.",
  },
  {
    id: "creator-foundry",
    family: "pro",
    mode: "foundry",
    name: "Creator Foundry",
    shortName: "Foundry",
    thesis: "A creator operating suite where art, drops, live rooms, sites, and market actions become one production line.",
    audience: "Creator platforms, marketplaces, launch partners, studios",
    shellIdea: "Work orders move through Studio, pinning, contract, publish, announce, and market rooms.",
    whyBetter: "It makes wtfOS feel like a product that can sell creator launch capacity, not just collect tools.",
    migrationPath: "Unify Studio, Macaroni, IPFS Pinning, Domains, W, and WTF LIVE around a shared release object.",
    weirdness: "Production line stages can be named like wtfOS rituals while each stage shows practical inputs and outputs.",
    risk: "Requires a strong shared release model or it becomes another dashboard.",
    primaryAction: "Start release order",
    secondaryAction: "Inspect launch proof",
    accent: "#8b3f2f",
    accent2: "#35746c",
    surface: "#f1ece4",
    ink: "#201713",
    canvas: "#dfd4c8",
    modules: ["studio", "macaroni", "pinning", "domains", "live", "w", "market", "wallet"],
    flow: ["Gather assets", "Build drop", "Preflight chain", "Publish and announce"],
    pitch: "Most commercial if wtfOS wants to be sold as creator infrastructure.",
  },
  {
    id: "neighborhood-net",
    family: "indie",
    mode: "zine",
    name: "Neighborhood Net",
    shortName: "Net",
    thesis: "An indie community shell where pages, posts, rooms, channels, and games feel like a lived-in local web.",
    audience: "Indie webmasters, art communities, small collectives",
    shellIdea: "Public rooms, bulletin strips, site patches, and channel shelves share one approachable community board.",
    whyBetter: "It makes wtfOS social and publishing features feel emotionally obvious without becoming a generic social app.",
    migrationPath: "Start from public profile, user sites, W, WTF LIVE, Skywire, Arcade, and message board.",
    weirdness: "The OS can be messy and handmade while keeping public/session/admin boundaries visually separate.",
    risk: "Needs hard access separation so public charm never blurs creator or admin controls.",
    primaryAction: "Post to the board",
    secondaryAction: "Open site patch",
    accent: "#c53d57",
    accent2: "#00806f",
    surface: "#f7f0dc",
    ink: "#181512",
    canvas: "#e5dabc",
    modules: ["w", "skywire", "live", "domains", "pinning", "arcade", "studio", "identity"],
    flow: ["Read board", "Open room", "Patch site", "Share signal"],
    pitch: "Best for making indie webmasters feel the platform has soul without losing function.",
  },
  {
    id: "public-access-station",
    family: "indie",
    mode: "station",
    name: "Public Access Station",
    shortName: "Station",
    thesis: "A local broadcast desk for channels, rooms, call-ins, clips, guestbook posts, and show pages.",
    audience: "Streamers, web radio hosts, event crews, community media",
    shellIdea: "The home view is a station board with live signal, queue, callers, clips, and post-show publishing.",
    whyBetter: "It connects WTF TV, WTF LIVE, W, Studio, and user sites into one expressive media loop.",
    migrationPath: "Prototype as a shell around TV, LIVE, W, Studio, Macaroni pages, and Skywire signals.",
    weirdness: "The station can feel like underground public access while every live/publish state is unmistakable.",
    risk: "Realtime media permissions and moderation need extremely clear controls.",
    primaryAction: "Open station board",
    secondaryAction: "Publish show page",
    accent: "#006d77",
    accent2: "#e0a640",
    surface: "#efe8d2",
    ink: "#151712",
    canvas: "#d8ceb0",
    modules: ["live", "w", "studio", "pinning", "domains", "skywire", "arcade", "admin"],
    flow: ["Queue media", "Go live", "Moderate signal", "Publish recap"],
    pitch: "Best indie live-media option: it gives wtfOS a reason to be open during events.",
  },
  {
    id: "hyperstack-garden",
    family: "indie",
    mode: "stack",
    name: "Hyperstack Garden",
    shortName: "Stack",
    thesis: "A card-stack shell where wtfOS objects can be linked, remixed, published, and revisited like living hypermedia.",
    audience: "Writers, toolmakers, personal-site builders, knowledge gardeners",
    shellIdea: "Everything is a card with backlinks, status, owner app, and publish actions.",
    whyBetter: "It explains wtfOS sprawl as a linked object system instead of a pile of app icons.",
    migrationPath: "Model cards for profile, posts, media, maps, drops, domains, and runbooks before replacing app internals.",
    weirdness: "The shell can be playful and poetic because each card still carries route, owner, access, and side-effect data.",
    risk: "Card systems can become vague unless object types and owner apps stay visible.",
    primaryAction: "Create linked card",
    secondaryAction: "Publish stack",
    accent: "#5d4b9a",
    accent2: "#b9552d",
    surface: "#f1eef7",
    ink: "#1a1726",
    canvas: "#dad2e9",
    modules: ["identity", "studio", "domains", "map", "pinning", "w", "arcade", "recovery"],
    flow: ["Capture object", "Link context", "Preview stack", "Publish or hand off"],
    pitch: "Best poetic shell: it makes wtfOS feel like a personal web instrument.",
  },
  {
    id: "pocket-dock",
    family: "mobile",
    mode: "pocket",
    name: "Pocket Dock",
    shortName: "Dock",
    thesis: "A mobile command dock for the next useful action, not a cramped desktop replica.",
    audience: "Users checking messages, wallets, live rooms, and incidents on the move",
    shellIdea: "Bottom dock, object deck, one-task cards, and handoff to desktop for heavy editors.",
    whyBetter: "It admits that mobile wtfOS should be triage, approval, capture, and communication.",
    migrationPath: "Wrap existing routes as mobile cards while keeping heavy creation tools desktop-first.",
    weirdness: "Mobile can still feel like wtfOS through object labels, badges, and rituals, not tiny draggable windows.",
    risk: "Some desktop tools must clearly say when mobile is view-only or handoff-only.",
    primaryAction: "Handle next action",
    secondaryAction: "Send to desktop",
    accent: "#08728a",
    accent2: "#d2523c",
    surface: "#eef6f7",
    ink: "#0d1b20",
    canvas: "#d1e4e8",
    modules: ["mission", "intent", "w", "wallet", "live", "domains", "recovery", "identity"],
    flow: ["See next task", "Approve or defer", "Reply quickly", "Handoff heavy work"],
    pitch: "Best everyday mobile shell because it gives wtfOS a useful pocket shape.",
  },
  {
    id: "live-lens",
    family: "mobile",
    mode: "lens",
    name: "Live Lens",
    shortName: "Lens",
    thesis: "A creator phone shell for rooms, camera state, clips, chat, and post-show publishing.",
    audience: "Hosts, cohosts, mobile creators, event staff",
    shellIdea: "Stage lens on top, chat pulse below, source and audience controls pinned to the thumb zone.",
    whyBetter: "It separates media capture from desktop windowing and makes live state impossible to miss.",
    migrationPath: "Begin with WTF LIVE public rooms, Studio uploads, W recaps, and Skywire live-status signals.",
    weirdness: "The live surface can be expressive, but media source, room, audience, and recording state stay plain.",
    risk: "Camera/screen permissions and moderation controls must be tested on real devices.",
    primaryAction: "Check stage",
    secondaryAction: "Publish recap",
    accent: "#9b2f45",
    accent2: "#2a756d",
    surface: "#f6eef1",
    ink: "#241116",
    canvas: "#e3cbd1",
    modules: ["live", "studio", "w", "skywire", "pinning", "identity", "admin", "recovery"],
    flow: ["Check source", "Open room", "Host signal", "Save recap"],
    pitch: "Best event shell: it turns wtfOS into a live production companion.",
  },
  {
    id: "wallet-deck",
    family: "mobile",
    mode: "cards",
    name: "Wallet Deck",
    shortName: "Deck",
    thesis: "A mobile trust deck for chain identity, balances, mints, domains, and safe approvals.",
    audience: "Collectors, creators, traders, support",
    shellIdea: "Swipeable proof cards with hard network/account boundaries and visible receipt history.",
    whyBetter: "It keeps wallet work focused without pretending the phone should run the whole OS.",
    migrationPath: "Start with wallet, Tezos Intel, marketplace, Macaroni approve steps, and domain registration.",
    weirdness: "The deck can show strange wtfOS artifacts, but every card names the network and consequence.",
    risk: "Must not become a generic wallet clone; it should stay anchored to wtfOS actions.",
    primaryAction: "Verify chain state",
    secondaryAction: "Open receipt",
    accent: "#315da8",
    accent2: "#9a6528",
    surface: "#eef2f8",
    ink: "#101a2d",
    canvas: "#d5dce9",
    modules: ["wallet", "market", "domains", "macaroni", "pinning", "identity", "recovery", "intent"],
    flow: ["Review account", "Check network", "Approve action", "Save receipt"],
    pitch: "Best mobile trust shell for reducing wallet mistakes and support confusion.",
  },
  {
    id: "intent-os",
    family: "ops",
    mode: "intent",
    name: "Intent OS",
    shortName: "Intent",
    thesis: "A command-first shell where the user says what they intend, and wtfOS assembles the correct app, role, and state.",
    audience: "Power users, admins, support, paired-agent users",
    shellIdea: "A permanent intent bar creates task packets with route gate, owner app, object state, and side-effect preview.",
    whyBetter: "It reduces app hunting and makes the OS feel intelligent without hiding authority.",
    migrationPath: "Layer intent search on top of the existing route registry and command palette, then promote object actions.",
    weirdness: "The weird names become discoverable aliases; the actual action stays plain.",
    risk: "Needs excellent empty states and strict access explanations.",
    primaryAction: "Run intent",
    secondaryAction: "Inspect gate",
    accent: "#2f5073",
    accent2: "#b06935",
    surface: "#eef0f2",
    ink: "#101720",
    canvas: "#d5dbe1",
    modules: ["intent", "mission", "terminal", "map", "mcp", "admin", "recovery", "desktop"],
    flow: ["Type intent", "Preview authority", "Run action", "Open owner object"],
    pitch: "Best operation-first shell for experienced users and agents.",
  },
  {
    id: "recovery-harbor",
    family: "ops",
    mode: "recovery",
    name: "Recovery Harbor",
    shortName: "Harbor",
    thesis: "A calm recovery-first shell that makes degraded states, repairs, reports, and safe exits the first-class experience.",
    audience: "New users, support staff, admins, anyone facing broken wallet or publishing state",
    shellIdea: "The shell surfaces health, likely cause, safe fix, side effect, and return path before decorative app chrome.",
    whyBetter: "It lowers support burden by making repair and confidence part of the OS, not a hidden app.",
    migrationPath: "Upgrade Recovery Mode, Mission Control, wallet status, IPFS pinning, and app crash boundaries first.",
    weirdness: "The harbor metaphor can soften scary failures while keeping diagnosis and action names plain.",
    risk: "If always visible, recovery can make the product feel broken even when healthy.",
    primaryAction: "Fix top issue",
    secondaryAction: "Export report",
    accent: "#4b7340",
    accent2: "#b34739",
    surface: "#eff4ec",
    ink: "#111d12",
    canvas: "#d9e5d4",
    modules: ["recovery", "mission", "wallet", "pinning", "desktop", "admin", "intent", "mcp"],
    flow: ["Read diagnosis", "Run safe fix", "Confirm restored", "Return to task"],
    pitch: "Best ease-first shell for onboarding and support quality.",
  },
  {
    id: "role-runbook",
    family: "ops",
    mode: "runbook",
    name: "Role Runbook",
    shortName: "Runbook",
    thesis: "A role-aware task shell that builds the GUI around creator, collector, host, admin, or agent work.",
    audience: "Teams, events, support desks, hosted creator programs",
    shellIdea: "Role lanes generate next steps, owner app handoffs, side-effect proof, and completion receipts.",
    whyBetter: "It turns wtfOS from an app collection into a guided operating system for real work.",
    migrationPath: "Start with creator drop launch, host live room, admin incident, collector wallet, and paired-agent flows.",
    weirdness: "The runbook can use wtfOS rituals as progress moments while staying practical about side effects.",
    risk: "Runbooks need product ownership or they drift from actual feature behavior.",
    primaryAction: "Continue runbook",
    secondaryAction: "Open proof",
    accent: "#5b5475",
    accent2: "#4c7c55",
    surface: "#f1eff4",
    ink: "#1b1723",
    canvas: "#dbd6e4",
    modules: ["mission", "studio", "macaroni", "live", "wallet", "domains", "admin", "recovery"],
    flow: ["Choose role", "Follow step", "Verify side effect", "Hand off owner app"],
    pitch: "Best team shell because it makes wtfOS usable by people who do not know the topology yet.",
  },
];

export const objectActions = [
  { label: "Home", icon: Home },
  { label: "Search", icon: Search },
  { label: "Command", icon: Command },
  { label: "Routes", icon: Route },
  { label: "Signals", icon: Podcast },
  { label: "Wallet", icon: WalletCards },
  { label: "Publish", icon: Send },
  { label: "Proofs", icon: FileKey },
  { label: "Archive", icon: Archive },
  { label: "Settings", icon: SlidersHorizontal },
  { label: "Repair", icon: Wrench },
  { label: "Agents", icon: Bot },
];

export const laneMeta: Record<DomainLane, { label: string; icon: LucideIcon }> = {
  identity: { label: "Identity", icon: KeyRound },
  social: { label: "Social", icon: Link2 },
  media: { label: "Media", icon: Film },
  chain: { label: "Chain", icon: CircuitBoard },
  ops: { label: "Ops", icon: ShieldCheck },
  play: { label: "Play", icon: Flame },
};

export const statusMeta: Record<ShellModule["status"], { label: string; icon: LucideIcon }> = {
  ready: { label: "Ready", icon: BadgeCheck },
  watch: { label: "Watch", icon: Bell },
  blocked: { label: "Blocked", icon: LockKeyhole },
  running: { label: "Running", icon: Activity },
};

export const shellPrinciples = [
  { label: "Object first", icon: Blocks },
  { label: "Intent before app hunting", icon: MousePointer2 },
  { label: "Trust visible", icon: ShieldCheck },
  { label: "Mobile has its own grammar", icon: Smartphone },
  { label: "Compatibility skin supported", icon: PanelsTopLeft },
  { label: "Heavy tools hydrate late", icon: TimerReset },
  { label: "Graph and docs are native", icon: GitBranch },
  { label: "Receipts after risky actions", icon: ReceiptText },
  { label: "Agents obey same gates", icon: Network },
  { label: "Delight carries task meaning", icon: Rocket },
  { label: "Publishing has proof", icon: MonitorUp },
  { label: "Maps are navigable, not mandatory", icon: Compass },
  { label: "Galleries become workspaces", icon: GalleryHorizontalEnd },
  { label: "Terminals stay safe", icon: TerminalSquare },
  { label: "Data has ownership", icon: Database },
  { label: "Layers can be inspected", icon: Layers3 },
  { label: "Dashboards answer next action", icon: ClipboardCheck },
  { label: "Views adapt by role", icon: LayoutGrid },
  { label: "Cables show dependencies", icon: Cable },
  { label: "Docs sit beside work", icon: BookOpen },
  { label: "Broadcast state is plain", icon: Tv },
  { label: "Waypoints replace clutter", icon: Map },
  { label: "Chain calls show cost", icon: Hammer },
  { label: "Urgency is explicit", icon: Zap },
];
