import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

const appSource = readFileSync("client/src/App.tsx", "utf8");
const gammaSource = readFileSync("client/src/pages/GammaWtfos.tsx", "utf8");
const loginSource = readFileSync("client/src/pages/Login.tsx", "utf8");
const registerSource = readFileSync("client/src/pages/Register.tsx", "utf8");
const presentationShellSource = readFileSync("client/src/lib/presentation-shell.tsx", "utf8");
const react95PresentationSource = readFileSync("client/src/lib/react95-presentation.tsx", "utf8");
const viteSource = readFileSync("vite.config.ts", "utf8");

test("App routes production Gamma hostnames through the Gamma shell", () => {
  assert.match(appSource, /function isGammaHost\(\): boolean/);
  assert.match(appSource, /window\.location\.hostname === "gamma\.wtfos\.app"/);
  assert.match(appSource, /if \(isGammaHost\(\)\) return true/);
  assert.match(appSource, /const gammaShellMatch = isGammaShellLocation\(location\) \? matchPage\("\/gamma"\) : null/);
  assert.match(appSource, /if \(gammaShellMatch\) \{\s*return <FullscreenRouteRenderer match=\{gammaShellMatch\} \/>;\s*\}/);
});

test("Gamma navigation separates production hostname routes from local harness-prefixed routes", () => {
  assert.match(gammaSource, /function gammaNavigationTarget\(route: string, currentLocation: string\): string/);
  assert.match(gammaSource, /if \(isGammaHost\(\)\) return routeLocation/);
  assert.match(gammaSource, /if \(!isGammaHarnessLocation\(currentLocation\)\) return routeLocation/);
  assert.match(gammaSource, /return `\/gamma\$\{routeLocation\}`/);
  assert.match(gammaSource, /function gammaRouteFromLocation\(location: string\): string/);
  assert.match(gammaSource, /parts\.pathname\.slice\("\/gamma"\.length\)/);
});

test("Gamma interface switching preserves the selected route while allowing explicit exits", () => {
  assert.match(gammaSource, /function interfaceHref\(host: "classic" \| "beta" \| "gamma", routeLocation: string\): string/);
  assert.match(gammaSource, /https:\/\/wtfos\.app/);
  assert.match(gammaSource, /https:\/\/beta\.wtfos\.app/);
  assert.match(gammaSource, /https:\/\/gamma\.wtfos\.app/);
  assert.match(gammaSource, /data-gamma-ux-switcher/);
  assert.match(gammaSource, /data-gamma-interface-switch="true"/);
  assert.match(gammaSource, /if \(anchor\.closest\("\[data-gamma-interface-switch='true'\]"\)\) return null/);
});

test("Gamma home exposes a standard OS boot desk and start menu without new app logic", () => {
  assert.match(gammaSource, /function GammaBootDesk\(/);
  assert.match(gammaSource, /data-gamma-boot-desk/);
  assert.match(gammaSource, /data-gamma-session-state/);
  assert.match(gammaSource, /data-gamma-boot-account/);
  assert.match(gammaSource, /data-gamma-boot-account-state=\{sessionState\}/);
  assert.match(gammaSource, /data-gamma-boot-resume-target=\{resumeTargetRoute\}/);
  assert.match(gammaSource, /Log in to restore Dashboard/);
  assert.match(gammaSource, /data-gamma-boot-search/);
  assert.match(gammaSource, /data-gamma-boot-command-search/);
  assert.match(gammaSource, /data-gamma-session-checklist/);
  assert.match(gammaSource, /data-gamma-session-check=\{check\.key\}/);
  assert.match(gammaSource, /data-gamma-start-menu/);
  assert.match(gammaSource, /data-gamma-start-action="continue"/);
  assert.match(gammaSource, /function GammaSessionConsole\(/);
  assert.match(gammaSource, /data-gamma-session-console/);
  assert.match(gammaSource, /data-gamma-session-shortcut=\{shortcut\.key\}/);
  assert.match(gammaSource, /data-gamma-session-mount/);
  assert.match(gammaSource, /data-gamma-session-mount-state=\{mountState\}/);
  assert.match(gammaSource, /data-gamma-session-mount-workspace=\{workspaceTargetRoute\}/);
  assert.match(gammaSource, /data-gamma-session-mount-row=\{row\.key\}/);
  assert.match(gammaSource, /Workspace mounted/);
  assert.match(gammaSource, /data-gamma-session-resume-action=\{recent\.key\}/);
  assert.match(gammaSource, /data-gamma-session-dock/);
  assert.match(gammaSource, /data-gamma-session-recents-state=\{hasStoredRecents \? "stored" : "fallback"\}/);
  assert.match(gammaSource, /data-gamma-session-dock-state=\{hasStoredRecents \? "open" : "pinned"\}/);
  assert.match(gammaSource, /data-gamma-session-dock-keyboard-target=\{sessionDockKeyboardRoute \?\? undefined\}/);
  assert.match(gammaSource, /data-gamma-session-dock-route=\{recent\.route\}/);
  assert.match(gammaSource, /data-gamma-session-dock-front=\{hasStoredRecents && index === 0 \? "true" : "false"\}/);
  assert.match(gammaSource, /data-gamma-session-recent-route=\{recent\.route\}/);
  assert.match(gammaSource, /data-gamma-session-recent-fallback=\{recent\.fallback \? "true" : "false"\}/);
  assert.match(gammaSource, /const sessionDockKeyboardRoute = firstStoredRecent\?\.route \?\? null/);
  assert.match(gammaSource, /const handleGammaSessionDockShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /onLaunch\(sessionDockKeyboardRoute\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaSessionDockShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaSessionDockShortcut\)/);
  assert.match(gammaSource, /type GammaWakeQueueItem =/);
  assert.match(gammaSource, /function buildGammaWakeQueue\(/);
  assert.match(gammaSource, /function GammaWakeQueue\(/);
  assert.match(gammaSource, /data-gamma-wake-queue/);
  assert.match(gammaSource, /data-gamma-wake-state=\{wakeState\}/);
  assert.match(gammaSource, /data-gamma-wake-action=\{item\.key\}/);
  assert.match(gammaSource, /data-gamma-wake-rank=\{index \+ 1\}/);
  assert.match(gammaSource, /const resumeRoute = user/);
  assert.match(gammaSource, /firstStoredRecent\?\.route \?\? GAMMA_DEFAULT_POST_LOGIN_ROUTE/);
  assert.match(gammaSource, /function GammaSystemTray\(/);
  assert.match(gammaSource, /type GammaSystemState = "checking" \| "online" \| "degraded"/);
  assert.match(gammaSource, /type GammaNotificationState = "guest" \| "checking" \| "clear" \| "unread" \| "degraded"/);
  assert.match(gammaSource, /type GammaNotificationSummary =/);
  assert.match(gammaSource, /type GammaClockSnapshot =/);
  assert.match(gammaSource, /GAMMA_CLOCK_ROUTE = "\/calendar"/);
  assert.match(gammaSource, /function buildGammaClockSnapshot\(now: Date\): GammaClockSnapshot/);
  assert.match(gammaSource, /function useGammaClockSnapshot\(\): GammaClockSnapshot/);
  assert.match(gammaSource, /window\.setInterval\(\(\) => setNow\(new Date\(\)\), 30_000\)/);
  assert.match(gammaSource, /window\.clearInterval\(intervalId\)/);
  assert.match(gammaSource, /api\.get<GammaNotificationSummary>\("\/api\/notifications\?limit=6"\)/);
  assert.match(gammaSource, /enabled: Boolean\(user\)/);
  assert.match(gammaSource, /const notificationState: GammaNotificationState = !user/);
  assert.match(gammaSource, /data-gamma-system-tray/);
  assert.match(gammaSource, /data-gamma-system-state=\{systemState\}/);
  assert.match(gammaSource, /data-gamma-tray-status=\{systemState\}/);
  assert.match(gammaSource, /data-gamma-tray-action=\{action\.key\}/);
  assert.match(gammaSource, /data-gamma-tray-action-state=\{action\.state \?\? undefined\}/);
  assert.match(gammaSource, /data-gamma-system-clock=\{action\.clock \? "tray" : undefined\}/);
  assert.match(gammaSource, /data-gamma-clock-iso=\{action\.clock \? clock\.iso : undefined\}/);
  assert.match(gammaSource, /data-gamma-clock-time=\{action\.clock \? clock\.timeLabel : undefined\}/);
  assert.match(gammaSource, /data-gamma-clock-date=\{action\.clock \? clock\.dateLabel : undefined\}/);
  assert.match(gammaSource, /data-gamma-tray-unread-count=/);
  assert.match(gammaSource, /data-gamma-power-menu/);
  assert.match(gammaSource, /data-gamma-power-state=\{user \? "signed-in" : "guest"\}/);
  assert.match(gammaSource, /data-gamma-power-action=\{action\.key\}/);
  assert.match(gammaSource, /data-gamma-power-session=\{action\.key === "lock" \? "retained" : undefined\}/);
  assert.match(gammaSource, /data-gamma-power-action=\{user \? "signout" : "login"\}/);
  assert.match(gammaSource, /data-gamma-power-pending=\{isSigningOut \? "true" : "false"\}/);
  assert.match(gammaSource, /key: "lock"[\s\S]*label: "Lock"[\s\S]*detail: "Keep session"[\s\S]*route: "\/"/);
  assert.match(gammaSource, /icon: LockKeyhole/);
  assert.match(gammaSource, /const handleGammaLock = \(\) =>/);
  assert.match(gammaSource, /const handleGammaLockShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /!event\.ctrlKey \|\| !event\.altKey \|\| event\.metaKey \|\| event\.shiftKey/);
  assert.match(gammaSource, /event\.key\.toLowerCase\(\) !== "l"/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaLockShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaLockShortcut\)/);
  assert.match(gammaSource, /await logout\(\)/);
  assert.match(gammaSource, /Gamma session degraded/);
  assert.match(gammaSource, /key: "network"[\s\S]*label: networkLabel/);
  assert.match(gammaSource, /xpQuery\.isError \|\| desktopAppsQuery\.isError/);
  assert.match(gammaSource, /systemState=\{gammaSystemState\}/);
  assert.match(gammaSource, /key: "signals"[\s\S]*label: "Signals"[\s\S]*detail: notificationDetail[\s\S]*state: notificationState[\s\S]*unreadCount: notificationUnreadCount/);
  assert.match(gammaSource, /key: "clock"[\s\S]*label: clock\.timeLabel[\s\S]*detail: clock\.dateLabel[\s\S]*route: GAMMA_CLOCK_ROUTE[\s\S]*icon: CalendarDays[\s\S]*clock: true/);
  assert.match(gammaSource, /data-gamma-launch="\/wtfiam\?category=apps"/);
  assert.match(gammaSource, /\/side-quests/);
  assert.match(gammaSource, /function GammaDailyReturnStrip\(/);
  assert.match(gammaSource, /data-gamma-daily-return/);
  assert.match(gammaSource, /data-gamma-daily-action=\{action\.key\}/);
  assert.match(gammaSource, /Return for a small proof, a visible person, or a live signal/);
  assert.match(gammaSource, /\{ label: "Start", stations: START_STATIONS \}/);
  assert.match(gammaSource, /onLaunch\(`\/gallery\?search=\$\{encodeURIComponent\(query\)\}`\)/);
});

test("Gamma command search opens registered routes before falling back to Gallery search", () => {
  assert.match(gammaSource, /import \{ PAGE_DEFS, getPageAccessState, matchPage \}/);
  assert.match(gammaSource, /type GammaCommandEntry =/);
  assert.match(gammaSource, /function buildGammaCommandEntries\(/);
  assert.match(gammaSource, /function staticRouteFromPattern\(pattern: string\): string \| null/);
  assert.match(gammaSource, /function getGammaCommandMatches\(/);
  assert.match(gammaSource, /PAGE_DEFS/);
  assert.match(gammaSource, /data-gamma-command-results/);
  assert.match(gammaSource, /data-gamma-command-route=\{command\.route\}/);
  assert.match(gammaSource, /data-gamma-command-locked=\{command\.locked \? "true" : "false"\}/);
  assert.match(gammaSource, /onLaunch\(command\.route\)/);
  assert.match(gammaSource, /data-gamma-command-result="gallery-search"/);
  assert.match(gammaSource, /data-gamma-route-command-search/);
  assert.match(gammaSource, /data-gamma-command-input="true"/);
  assert.match(gammaSource, /placeholder="Search apps, tools, routes"/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma command search is reachable as an OS keyboard command", () => {
  assert.match(gammaSource, /function focusGammaCommandInput\(\)/);
  assert.match(gammaSource, /querySelector\("\[data-gamma-wtfos\]"\)/);
  assert.match(gammaSource, /querySelectorAll<HTMLInputElement>\('input\[data-gamma-command-input="true"\]'\)/);
  assert.match(gammaSource, /candidate\.getClientRects\(\)\.length > 0/);
  assert.match(gammaSource, /input\.focus\(\{ preventScroll: false \}\)/);
  assert.match(gammaSource, /input\.select\(\)/);
  assert.match(gammaSource, /const handleGammaCommandShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaCommandShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaCommandShortcut\)/);
  assert.match(gammaSource, /event\.key\.toLowerCase\(\) !== "k"/);
  assert.match(gammaSource, /!event\.metaKey && !event\.ctrlKey/);
  assert.match(gammaSource, /event\.preventDefault\(\)/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma command search can be dismissed from the keyboard", () => {
  assert.match(gammaSource, /function handleGammaCommandInputKeyDown\(/);
  assert.match(gammaSource, /event\.key !== "Escape"/);
  assert.match(gammaSource, /setQuery\(""\)/);
  assert.match(gammaSource, /HTMLInputElement\.prototype\.blur\.call\(event\.currentTarget\)/);
  assert.match(gammaSource, /event\.preventDefault\(\)/);
  assert.match(gammaSource, /event\.stopPropagation\(\)/);
  assert.match(gammaSource, /onKeyDown=\{\(event\) => handleGammaCommandInputKeyDown\(event, searchText, setSearchText\)\}/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma command results support keyboard focus movement", () => {
  assert.match(gammaSource, /data-gamma-command-surface/);
  assert.match(gammaSource, /function visibleGammaCommandButtons\(surface: Element \| null\)/);
  assert.match(gammaSource, /querySelectorAll<HTMLButtonElement>\("\[data-gamma-command-results\] button"\)/);
  assert.match(gammaSource, /function focusGammaCommandInputForSurface\(surface: Element \| null\)/);
  assert.match(gammaSource, /querySelector<HTMLInputElement>\('input\[data-gamma-command-input="true"\]'\)/);
  assert.match(gammaSource, /input\.focus\(\{ preventScroll: false \}\)/);
  assert.match(gammaSource, /input\.select\(\)/);
  assert.match(gammaSource, /function moveGammaCommandResultFocus\(/);
  assert.match(gammaSource, /direction: "first" \| "previous" \| "next"/);
  assert.match(gammaSource, /event\.currentTarget\.closest\("\[data-gamma-command-surface\]"\)/);
  assert.match(gammaSource, /buttons\[targetIndex\]\?\.focus\(\{ preventScroll: false \}\)/);
  assert.match(gammaSource, /event\.key === "ArrowDown"/);
  assert.match(gammaSource, /event\.key === "ArrowUp"/);
  assert.match(gammaSource, /event\.key === "Escape"/);
  assert.match(gammaSource, /const didFocusInput = focusGammaCommandInputForSurface\(/);
  assert.match(gammaSource, /onKeyDown=\{handleGammaCommandResultKeyDown\}/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma app routes expose a keyboard return-to-desk command", () => {
  assert.match(gammaSource, /function isGammaEditableShortcutTarget\(target: EventTarget \| null\)/);
  assert.match(gammaSource, /target instanceof HTMLElement/);
  assert.match(gammaSource, /target\.isContentEditable/);
  assert.match(gammaSource, /tagName === "input" \|\| tagName === "textarea" \|\| tagName === "select"/);
  assert.match(gammaSource, /const handleGammaDeskShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /!event\.altKey \|\| event\.metaKey \|\| event\.ctrlKey \|\| event\.shiftKey/);
  assert.match(gammaSource, /event\.key !== "Home"/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /routePathname === "\/" \|\| routePathname === "\/gamma"/);
  assert.match(gammaSource, /navigate\(gammaNavigationTarget\("\/", location\)\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaDeskShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaDeskShortcut\)/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma app routes expose in-shell route history controls", () => {
  assert.match(gammaSource, /type GammaNavigationHistory =/);
  assert.match(gammaSource, /GAMMA_HISTORY_LIMIT = 12/);
  assert.match(gammaSource, /function normalizeGammaHistoryRoute\(routeLocation: string\): string \| null/);
  assert.match(gammaSource, /if \(pathname === "\/gamma"\) return "\/"/);
  assert.match(gammaSource, /if \(pathname\.startsWith\("\/api\/"\)\) return null/);
  assert.match(gammaSource, /return matchPage\(normalized\) \? normalized : null/);
  assert.match(gammaSource, /function createGammaHistoryState\(routeLocation: string\): GammaNavigationHistory/);
  assert.match(gammaSource, /function mergeGammaHistoryRoute\(/);
  assert.match(gammaSource, /history\.routes\[previousIndex\] === normalized/);
  assert.match(gammaSource, /history\.routes\[nextIndex\] === normalized/);
  assert.match(gammaSource, /\.slice\(-GAMMA_HISTORY_LIMIT\)/);
  assert.match(gammaSource, /function gammaHistoryRouteAt\(history: GammaNavigationHistory, offset: -1 \| 1\): string \| null/);
  assert.match(gammaSource, /useState<GammaNavigationHistory>\(\(\) =>\s*createGammaHistoryState\(routeLocation\)/);
  assert.match(gammaSource, /setGammaHistory\(\(currentHistory\) => mergeGammaHistoryRoute\(currentHistory, routeLocation\)\)/);
  assert.match(gammaSource, /const handleGammaHistoryBack = \(\) => navigateGammaHistoryRoute\(gammaHistoryBackRoute, -1\)/);
  assert.match(gammaSource, /const handleGammaHistoryForward = \(\) => navigateGammaHistoryRoute\(gammaHistoryForwardRoute, 1\)/);
  assert.match(gammaSource, /const handleGammaHistoryShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /event\.key === "ArrowLeft" \? -1 : event\.key === "ArrowRight" \? 1 : null/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /navigateGammaHistoryRoute\(targetRoute, direction\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaHistoryShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaHistoryShortcut\)/);
  assert.match(gammaSource, /data-gamma-history-controls/);
  assert.match(gammaSource, /data-gamma-history-back-target=\{historyBackRoute \?\? undefined\}/);
  assert.match(gammaSource, /data-gamma-history-forward-target=\{historyForwardRoute \?\? undefined\}/);
  assert.match(gammaSource, /data-gamma-history-action="back"/);
  assert.match(gammaSource, /data-gamma-history-action="forward"/);
  assert.match(gammaSource, /data-gamma-history-action="desk"/);
  assert.match(gammaSource, /aria-label="Gamma route history"/);
  assert.doesNotMatch(gammaSource, /window\.history\.back\(/);
  assert.doesNotMatch(gammaSource, /window\.history\.forward\(/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma app routes focus the active app frame after route activation", () => {
  assert.match(gammaSource, /function focusGammaRouteFrame\(\)/);
  assert.match(gammaSource, /document\.querySelector<HTMLElement>\('\[data-gamma-route-focus-target="active-app"\]'\)/);
  assert.match(gammaSource, /target\.focus\(\{ preventScroll: true \}\)/);
  assert.match(gammaSource, /const shouldFocusRouteFrame = Boolean\(!AuthComp && routeMatch && Comp && accessState\?\.allowed\)/);
  assert.match(gammaSource, /if \(!shouldFocusRouteFrame\) return/);
  assert.match(gammaSource, /window\.requestAnimationFrame\(\(\) => \{\s*focusGammaRouteFrame\(\);/);
  assert.match(gammaSource, /window\.cancelAnimationFrame\(frameId\)/);
  assert.match(gammaSource, /data-gamma-route-focus-target=\{shouldFocusRouteFrame \? "active-app" : undefined\}/);
  assert.match(gammaSource, /tabIndex=\{shouldFocusRouteFrame \? -1 : undefined\}/);
  assert.match(gammaSource, /role=\{shouldFocusRouteFrame \? "group" : undefined\}/);
  assert.match(gammaSource, /aria-label=\{shouldFocusRouteFrame \? `Active Gamma app: \$\{title\} at \$\{routePathname\}` : undefined\}/);
  assert.match(gammaSource, /&\[data-gamma-route-focus-target="active-app"\]:focus/);
  assert.match(gammaSource, /outline-color: var\(--gamma-cyan\)/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma home accepts Enter as a primary boot action only when the desk owns focus", () => {
  assert.match(gammaSource, /function isGammaInteractiveShortcutTarget\(target: EventTarget \| null\)/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(target\)/);
  assert.match(gammaSource, /target\.closest\("button, a, \[role='button'\], \[role='link'\], \[role='menuitem'\]"\)/);
  assert.match(gammaSource, /GAMMA_DEFAULT_POST_LOGIN_ROUTE = "\/dashboard"/);
  assert.match(gammaSource, /GAMMA_DEFAULT_LOGIN_ROUTE = `\/login\?return=\$\{encodeURIComponent\(GAMMA_DEFAULT_POST_LOGIN_ROUTE\)\}`/);
  assert.match(gammaSource, /autoFocus\s+data-gamma-primary-boot-action=\{continueRoute\}/);
  assert.match(gammaSource, /data-gamma-primary-boot-action=\{continueRoute\}/);
  assert.match(gammaSource, /const gammaPrimaryBootRoute = isLoading/);
  assert.match(gammaSource, /recentEntries\.find\(\(entry\) => !entry\.fallback\)\?\.route \?\? GAMMA_DEFAULT_POST_LOGIN_ROUTE/);
  assert.match(gammaSource, /: GAMMA_DEFAULT_LOGIN_ROUTE/);
  assert.match(gammaSource, /const handleGammaHomeEnterShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /event\.key !== "Enter"/);
  assert.match(gammaSource, /event\.metaKey \|\| event\.ctrlKey \|\| event\.altKey \|\| event\.shiftKey/);
  assert.match(gammaSource, /routePathname !== "\/" && routePathname !== "\/gamma"/);
  assert.match(gammaSource, /!gammaPrimaryBootRoute/);
  assert.match(gammaSource, /isGammaInteractiveShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /navigate\(gammaNavigationTarget\(gammaPrimaryBootRoute, location\)\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaHomeEnterShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaHomeEnterShortcut\)/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma stores recent routes as presentation-only session restore state", () => {
  assert.match(gammaSource, /GAMMA_RECENT_ROUTES_STORAGE_KEY = "wtfos\.gamma\.recentRoutes"/);
  assert.match(gammaSource, /function normalizeGammaRecentRoute\(routeLocation: string\): string \| null/);
  assert.match(gammaSource, /pathname === "\/" \|\|/);
  assert.match(gammaSource, /pathname === "\/login"/);
  assert.match(gammaSource, /pathname\.startsWith\("\/api\/"\)/);
  assert.match(gammaSource, /return matchPage\(normalized\) \? normalized : null/);
  assert.match(gammaSource, /function readGammaRecentRoutes\(\): string\[\]/);
  assert.match(gammaSource, /window\.localStorage\.getItem\(GAMMA_RECENT_ROUTES_STORAGE_KEY\)/);
  assert.match(gammaSource, /function writeGammaRecentRoutes\(routes: string\[\]\)/);
  assert.match(gammaSource, /window\.localStorage\.setItem\(GAMMA_RECENT_ROUTES_STORAGE_KEY, JSON\.stringify\(routes\)\)/);
  assert.match(gammaSource, /function mergeGammaRecentRoute\(routes: string\[\], routeLocation: string\): string\[\]/);
  assert.match(gammaSource, /function buildGammaRecentEntries\(routes: string\[\]\): GammaRecentEntry\[\]/);
  assert.match(gammaSource, /useState<string\[\]>\(readGammaRecentRoutes\)/);
  assert.match(gammaSource, /writeGammaRecentRoutes\(nextRoutes\)/);
  assert.match(gammaSource, /recentEntries=\{recentEntries\}/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma home explains access, EXP, app unlocks, and Count review through existing routes", () => {
  assert.match(gammaSource, /function GammaAccessPassport\(/);
  assert.match(gammaSource, /WTFOS_APP_CATALOG_ENTRIES/);
  assert.match(gammaSource, /formatRoleLabel/);
  assert.match(gammaSource, /data-gamma-access-passport/);
  assert.match(gammaSource, /data-gamma-passport-role/);
  assert.match(gammaSource, /data-gamma-passport-exp/);
  assert.match(gammaSource, /data-gamma-passport-action=\{action\.key\}/);
  assert.match(gammaSource, /data-gamma-passport-app-count/);
  assert.match(gammaSource, /data-gamma-passport-role-gate/);
  assert.match(gammaSource, /data-gamma-count-admin-lane/);
  assert.match(gammaSource, /EXP does not grant power by itself/);
  assert.match(gammaSource, /Use existing admin surfaces/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("Gamma locked app routes explain app installation and route to WTFIAM Apps", () => {
  assert.match(gammaSource, /const isLockedApp = reason === "app-disabled"/);
  assert.match(gammaSource, /data-gamma-route-gate-app=\{appKey \|\| undefined\}/);
  assert.match(gammaSource, /is not installed for this session/);
  assert.match(gammaSource, /data-gamma-locked-app-action="apps"/);
  assert.match(gammaSource, /data-gamma-launch="\/wtfiam\?category=apps"/);
});

test("Gamma auth routes preserve return targets inside the shell", () => {
  assert.match(gammaSource, /returnRoute=\{routeLocation\}/);
  assert.match(gammaSource, /\/login\?return=\$\{encodeURIComponent\(returnRoute\)\}/);
  assert.match(gammaSource, /autoFocus/);
  assert.match(gammaSource, /data-gamma-auth-primary-action="enter-return"/);
  assert.match(gammaSource, /data-gamma-auth-return=\{returnRoute \|\| undefined\}/);
  assert.match(gammaSource, /Enter and return/);
  assert.match(loginSource, /usePresentationShell/);
  assert.match(loginSource, /safeGammaAuthReturn/);
  assert.match(loginSource, /presentation\.host === "gamma"/);
  assert.match(loginSource, /GAMMA_DEFAULT_POST_AUTH_ROUTE = "\/dashboard"/);
  assert.match(loginSource, /presentationRouteHref\(gammaReturnRoute \?\? GAMMA_DEFAULT_POST_AUTH_ROUTE, "gamma"\)/);
  assert.match(loginSource, /gammaReturnRoute === GAMMA_DEFAULT_POST_AUTH_ROUTE/);
  assert.match(loginSource, /"Gamma dashboard"/);
  assert.match(loginSource, /setLocation\(postAuthRoute, \{ replace: true \}\)/);
  assert.match(registerSource, /usePresentationShell/);
  assert.match(registerSource, /safeGammaAuthReturn/);
  assert.match(registerSource, /GAMMA_DEFAULT_POST_AUTH_ROUTE = "\/dashboard"/);
  assert.match(registerSource, /presentationRouteHref\(gammaReturnRoute \?\? GAMMA_DEFAULT_POST_AUTH_ROUTE, "gamma"\)/);
  assert.match(registerSource, /gammaReturnRoute === GAMMA_DEFAULT_POST_AUTH_ROUTE/);
  assert.match(registerSource, /"Gamma dashboard"/);
  assert.match(registerSource, /setLocation\(postAuthRoute, \{ replace: true \}\)/);
  assert.doesNotMatch(loginSource, /\/api\/gamma/i);
  assert.doesNotMatch(registerSource, /\/api\/gamma/i);
});

test("Gamma intercepts only shared route navigation and keeps APIs external", () => {
  assert.match(gammaSource, /function routeFromInterceptableLink\(anchor: HTMLAnchorElement\): string \| null/);
  assert.match(gammaSource, /\["wtfos\.app", "beta\.wtfos\.app", "gamma\.wtfos\.app"\]\.includes\(url\.hostname\)/);
  assert.match(gammaSource, /if \(routePath\.startsWith\("\/api\/"\)\) return null/);
  assert.match(gammaSource, /return matchPage\(normalizedRoute\) \? normalizedRoute : null/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
  assert.doesNotMatch(presentationShellSource, /\/api\/gamma/i);
});

test("Gamma route content is hosted by the presentation provider, not the Classic desktop", () => {
  assert.match(gammaSource, /<PresentationShellProvider host="gamma">/);
  assert.match(gammaSource, /<GammaSystemTray/);
  assert.match(gammaSource, /data-gamma-history-controls/);
  assert.match(gammaSource, /data-gamma-app-taskbar/);
  assert.match(gammaSource, /data-gamma-taskbar-current-app/);
  assert.match(gammaSource, /data-gamma-taskbar-action=\{action\.key\}/);
  assert.match(gammaSource, /data-gamma-taskbar-switcher/);
  assert.match(gammaSource, /data-gamma-taskbar-switcher-state=\{hasStoredSwitchEntries \? "stored" : "fallback"\}/);
  assert.match(gammaSource, /data-gamma-taskbar-keyboard-switch=\{keyboardSwitchRoute \?\? undefined\}/);
  assert.match(gammaSource, /data-gamma-taskbar-switch-route=\{entry\.route\}/);
  assert.match(gammaSource, /data-gamma-taskbar-switch-fallback=\{entry\.fallback \? "true" : "false"\}/);
  assert.match(gammaSource, /\{ key: "close", label: "Close app", route: "\/"/);
  assert.match(gammaSource, /\{ key: "inbox", label: "Inbox", route: "\/messages"/);
  assert.match(gammaSource, /\{ key: "daily", label: "Daily", route: "\/side-quests"/);
  assert.match(gammaSource, /<GammaApplicationContent data-gamma-application-content>/);
  assert.match(gammaSource, /<WindowManagerProvider navigate=\{onLaunch\} currentLocation=\{routeLocation\}>/);
  assert.match(gammaSource, /data-gamma-wtfos/);
  assert.doesNotMatch(gammaSource, /<Desktop\b/);
  assert.doesNotMatch(gammaSource, /data-wtf-desktop/);
});

test("Gamma app routes expose a recent-app task switcher from presentation state", () => {
  assert.match(gammaSource, /recentEntries: GammaRecentEntry\[\]/);
  assert.match(gammaSource, /storedSwitchEntries = recentEntries/);
  assert.match(gammaSource, /\.filter\(\(entry\) => !entry\.fallback && cleanPathname\(entry\.route\) !== routePathname\)/);
  assert.match(gammaSource, /GAMMA_FALLBACK_RECENTS\.filter\(\(entry\) => cleanPathname\(entry\.route\) !== routePathname\)/);
  assert.match(gammaSource, /const keyboardSwitchRoute = taskbarSwitchEntries\[0\]\?\.route \?\? null/);
  assert.match(gammaSource, /aria-label="Switch recent Gamma apps"/);
  assert.match(gammaSource, /const handleGammaAppSwitchShortcut = \(event: KeyboardEvent\)/);
  assert.match(gammaSource, /isGammaEditableShortcutTarget\(event\.target\)/);
  assert.match(gammaSource, /event\.key === "Tab" && \(event\.ctrlKey \|\| event\.metaKey\) && !event\.altKey/);
  assert.match(gammaSource, /event\.key === "PageDown" && event\.altKey/);
  assert.match(gammaSource, /onLaunch\(keyboardSwitchRoute\)/);
  assert.match(gammaSource, /window\.addEventListener\("keydown", handleGammaAppSwitchShortcut\)/);
  assert.match(gammaSource, /window\.removeEventListener\("keydown", handleGammaAppSwitchShortcut\)/);
  assert.match(gammaSource, /recentEntries=\{recentEntries\}/);
  assert.doesNotMatch(gammaSource, /\/api\/gamma/i);
});

test("React95 imports resolve through the presentation adapter for Gamma", () => {
  assert.match(viteSource, /find:\s*\/\^react95\$\/,/);
  assert.match(viteSource, /client\/src\/lib\/react95-presentation\.tsx/);
  assert.match(react95PresentationSource, /import \* as React95 from "react95\/dist\/index\.mjs"/);
  assert.match(react95PresentationSource, /return usePresentationShell\(\)\.host === "gamma"/);
  assert.match(react95PresentationSource, /function isPresentationShell\(\)/);
  assert.match(react95PresentationSource, /presentation\.host === "beta" \|\| presentation\.host === "gamma"/);
  assert.match(react95PresentationSource, /if \(!isPresentationShell\(\)\) return <Original\.Button/);
  assert.match(react95PresentationSource, /if \(!isPresentationShell\(\)\) return <Original\.Window/);
  assert.match(react95PresentationSource, /data-gamma-ui="button"/);
  assert.match(react95PresentationSource, /data-gamma-ui="window"/);
  assert.match(react95PresentationSource, /data-gamma-ui="table"/);
  assert.match(react95PresentationSource, /data-gamma-ui="tabs"/);
});
