import type { LucideIcon } from "lucide-react";
import {
  Activity,
  BarChart3,
  Bell,
  Brush,
  CheckCircle2,
  ClipboardList,
  Command,
  Database,
  FileText,
  Gauge,
  Globe,
  Home,
  Image,
  Layers,
  Lock,
  Map,
  MessageSquare,
  Monitor,
  Palette,
  Play,
  Radio,
  RefreshCw,
  Rocket,
  Search,
  Settings,
  Shield,
  Smartphone,
  Terminal,
  Video,
  Wallet,
  Wrench,
  Zap,
} from "lucide-react";

export type DemoCategory = "pro" | "indie" | "mobile" | "ops";
export type DemoMood =
  | "signal"
  | "atlas"
  | "market"
  | "zine"
  | "bodega"
  | "orchard"
  | "pocket"
  | "broadcast"
  | "wallet"
  | "command"
  | "recovery"
  | "runbook";

export interface WtfFeature {
  id: string;
  label: string;
  plain: string;
  status: "ready" | "syncing" | "attention" | "offline";
  metric: string;
  icon: LucideIcon;
  lane: "core" | "social" | "media" | "chain" | "ops";
}

export interface DemoVariant {
  id: string;
  category: DemoCategory;
  mood: DemoMood;
  name: string;
  shortName: string;
  pitch: string;
  audience: string;
  signature: string;
  react95Binding: string;
  usabilityRule: string;
  risk: string;
  primaryAction: string;
  secondaryAction: string;
  accent: string;
  accent2: string;
  ink: string;
  paper: string;
  chrome: string;
  features: string[];
  workflow: string[];
  saleNote: string;
}

export const categoryLabels: Record<DemoCategory, string> = {
  pro: "Pitch-grade product",
  indie: "Indie webmaster joy",
  mobile: "Mobile-first",
  ops: "Operation-first",
};

export const featureCatalog: WtfFeature[] = [
  {
    id: "mission",
    label: "Mission Control",
    plain: "User status, rewards, jobs, health, next action",
    status: "ready",
    metric: "12 open tasks",
    icon: Gauge,
    lane: "core",
  },
  {
    id: "desktop",
    label: "Desktop Shell",
    plain: "Windows, Start Menu, taskbar, shortcuts, recovery",
    status: "ready",
    metric: "9 windows",
    icon: Monitor,
    lane: "core",
  },
  {
    id: "command",
    label: "Command Palette",
    plain: "Search routes, apps, jobs, wallets, and admin tools",
    status: "ready",
    metric: "84 handles",
    icon: Command,
    lane: "core",
  },
  {
    id: "w",
    label: "W Feed",
    plain: "Social timeline, posts, links, DMs, digest",
    status: "syncing",
    metric: "24 new",
    icon: MessageSquare,
    lane: "social",
  },
  {
    id: "skywire",
    label: "Skywire",
    plain: "AT Protocol bridge, OAuth, Bluesky identity",
    status: "ready",
    metric: "connected",
    icon: Radio,
    lane: "social",
  },
  {
    id: "live",
    label: "WTF LIVE",
    plain: "Rooms, stage, camera, screen share, chat",
    status: "attention",
    metric: "2 live",
    icon: Video,
    lane: "social",
  },
  {
    id: "studio",
    label: "Studio",
    plain: "Projects, media library, annotations, collaboration",
    status: "ready",
    metric: "6 drafts",
    icon: Brush,
    lane: "media",
  },
  {
    id: "macaroni",
    label: "Macaroni",
    plain: "Blind drops, contracts, generated mint pages",
    status: "syncing",
    metric: "pinning",
    icon: Image,
    lane: "media",
  },
  {
    id: "pinning",
    label: "IPFS Pinning",
    plain: "Pin policy, manifests, user-site publishing",
    status: "ready",
    metric: "97 pins",
    icon: Database,
    lane: "media",
  },
  {
    id: "wallet",
    label: "Wallets",
    plain: "Tezos, Etherlink, chain guard, balances, proofs",
    status: "attention",
    metric: "1 mismatch",
    icon: Wallet,
    lane: "chain",
  },
  {
    id: "market",
    label: "Market Desk",
    plain: "Marketplace, swaps, trade boards, dues, portfolio",
    status: "ready",
    metric: "38 listings",
    icon: BarChart3,
    lane: "chain",
  },
  {
    id: "domains",
    label: "WTF Domains",
    plain: "username.wtfos.me, wtf.tez, public site proof",
    status: "ready",
    metric: "host active",
    icon: Globe,
    lane: "chain",
  },
  {
    id: "arcade",
    label: "Arcade + Casino",
    plain: "Games, console catalog, casino tables, side quests",
    status: "ready",
    metric: "11 tables",
    icon: Play,
    lane: "core",
  },
  {
    id: "map",
    label: "Map Lab",
    plain: "Workflow graph, ports, routes, roadmap maps",
    status: "ready",
    metric: "42 nodes",
    icon: Map,
    lane: "core",
  },
  {
    id: "admin",
    label: "Admin + Ops",
    plain: "App gates, health, role access, runbooks, incidents",
    status: "attention",
    metric: "3 warnings",
    icon: Shield,
    lane: "ops",
  },
  {
    id: "recovery",
    label: "Recovery Mode",
    plain: "Fix wallet sessions, network overrides, crashed windows",
    status: "ready",
    metric: "all clear",
    icon: Wrench,
    lane: "ops",
  },
  {
    id: "mcp",
    label: "MCP Pairing",
    plain: "Scoped agent tokens, route access, automation tools",
    status: "offline",
    metric: "2 idle",
    icon: Lock,
    lane: "ops",
  },
];

export const restrictions = [
  {
    title: "Local-only boundary",
    body: "These demos are isolated from PAGE_DEFS, BROWSER_ROUTE_META, Start Menu gates, desktop app packages, and production build paths.",
  },
  {
    title: "React95 is a binding, not a costume",
    body: "Windows, panels, buttons, tabs, inputs, app bars, and titlebar grammar should come from React95; modern layout CSS can wrap them for density and mobile safety.",
  },
  {
    title: "Promotion requires registry work",
    body: "A real wtfOS route must update page defs, shared route metadata, access policy, the interaction inventory, route fixtures, and inventory coverage in one pass.",
  },
  {
    title: "Weird labels need plain task anchors",
    body: "Every strange surface name needs a direct verb-object action nearby so the joke never hides wallet, publishing, admin, or recovery work.",
  },
  {
    title: "Wallets and chains are high-trust surfaces",
    body: "Network, account, RPC, fee, and operation states need explicit copy. A playful skin cannot blur mainnet versus Shadownet, Tezos L1 versus Etherlink, or pending versus confirmed.",
  },
  {
    title: "Desktop and mobile are different operating modes",
    body: "Resizable windows, taskbar, drag, hover, and context menus do not map cleanly to touch. Mobile concepts need bottom navigation, large targets, and fewer simultaneous panes.",
  },
  {
    title: "Accessibility is a product constraint",
    body: "WCAG AA contrast, keyboard reachability, visible focus, non-color-only state, status regions, and readable text sizes have to survive the retro aesthetic.",
  },
  {
    title: "Boot cost must stay boring",
    body: "Heavy wallet SDKs, media editors, maps, live video, and chain queries should lazy-load at launch or focus, not at desktop boot.",
  },
];

export const demoVariants: DemoVariant[] = [
  {
    id: "trilitech-signal-office",
    category: "pro",
    mood: "signal",
    name: "Signal Office",
    shortName: "Signal",
    pitch: "A protocol-operator desktop that makes wtfOS feel like a serious control room with a strange heart.",
    audience: "Enterprise buyers, protocol teams, operator desks",
    signature: "Quiet chrome, strong status grammar, one command shelf for every domain.",
    react95Binding: "React95 windows stay visible as a desktop contract while panels use modern enterprise density.",
    usabilityRule: "Plain task labels first; lore labels appear as secondary flavor.",
    risk: "Could become too sober if the weirdness is only decorative.",
    primaryAction: "Open chain readiness",
    secondaryAction: "Review live incidents",
    accent: "#1d5f91",
    accent2: "#d9a441",
    ink: "#101820",
    paper: "#e8edf0",
    chrome: "#c9d0d4",
    features: ["mission", "admin", "wallet", "domains", "skywire", "pinning", "recovery", "mcp"],
    workflow: ["Scan command shelf", "Resolve warnings", "Open owner app", "Verify route and event handles"],
    saleNote: "This is the strongest pitch-grade option for a Trilitech-style buyer because it turns wtfOS into a legible protocol operations surface.",
  },
  {
    id: "protocol-atlas-suite",
    category: "pro",
    mood: "atlas",
    name: "Protocol Atlas",
    shortName: "Atlas",
    pitch: "A polished map-and-document OS where routes, wallets, agents, sites, and media flows become inspectable system objects.",
    audience: "Developer relations, partner engineering, technical artists",
    signature: "Map Lab is the home screen; windows act like inspectors attached to graph objects.",
    react95Binding: "React95 titlebars and group boxes frame the graph, inspector, route table, and status windows.",
    usabilityRule: "The map is navigational, but every node has a normal table/detail fallback.",
    risk: "Graph-first interfaces can feel obscure unless search and breadcrumbs are excellent.",
    primaryAction: "Trace a workflow",
    secondaryAction: "Open object dossier",
    accent: "#315c52",
    accent2: "#c4573b",
    ink: "#17211f",
    paper: "#eef1ea",
    chrome: "#cdd8d1",
    features: ["map", "command", "studio", "pinning", "domains", "mcp", "admin", "wallet"],
    workflow: ["Search object", "Follow route ports", "Open inspector", "Run graph check"],
    saleNote: "This is the best option when selling wtfOS as a protocol workbench rather than a novelty desktop.",
  },
  {
    id: "creator-market-terminal",
    category: "pro",
    mood: "market",
    name: "Creator Market Terminal",
    shortName: "Market",
    pitch: "A market-grade creator console where drops, wallets, pinning, listings, and live promotion are one trading-desk workflow.",
    audience: "Creator platforms, marketplaces, launch partners",
    signature: "Dense left object rail, central deal/draft stage, right trust and chain preflight column.",
    react95Binding: "React95 tables, panels, and controls become a terminal cockpit instead of a nostalgic desktop toy.",
    usabilityRule: "Every signing or publishing step shows network, wallet, cost, status, and recovery.",
    risk: "Too much density could intimidate casual creators without setup presets.",
    primaryAction: "Prepare drop launch",
    secondaryAction: "Audit wallet preflight",
    accent: "#7b3f26",
    accent2: "#2f7d6f",
    ink: "#1e1612",
    paper: "#f0ece2",
    chrome: "#d4c8b8",
    features: ["macaroni", "studio", "market", "wallet", "pinning", "live", "domains", "recovery"],
    workflow: ["Choose drop", "Check assets", "Preflight wallet", "Publish and monitor"],
    saleNote: "This could be pitched as a revenue product: creator launch ops with chain-safe preflight and weird wtfOS energy.",
  },
  {
    id: "zineyard-95",
    category: "indie",
    mood: "zine",
    name: "Zineyard 95",
    shortName: "Zineyard",
    pitch: "A web-zine operating system: crunchy, handmade, and still clear enough to run real media, social, and wallet work.",
    audience: "Indie webmasters, net-art communities, personal-site makers",
    signature: "Sticker-like app tiles, split-screen guestbook, visible site/pin pipeline.",
    react95Binding: "React95 windows become handmade zine pages without losing buttons, tabs, and focus rules.",
    usabilityRule: "Every collage object is also a normal button with a plain accessible name.",
    risk: "Maximal collage can crush scannability if panel hierarchy is weak.",
    primaryAction: "Publish page scrap",
    secondaryAction: "Open guestbook",
    accent: "#da2f4f",
    accent2: "#1a8f85",
    ink: "#151515",
    paper: "#f5f0df",
    chrome: "#ded7c6",
    features: ["domains", "pinning", "w", "studio", "message", "arcade", "skywire", "map"],
    workflow: ["Grab a scrap", "Pin media", "Write site page", "Post to W"],
    saleNote: "Indie joy option: it makes publishing feel like running a living web desk, not filling out a CMS.",
  },
  {
    id: "public-access-bodega",
    category: "indie",
    mood: "bodega",
    name: "Public Access Bodega",
    shortName: "Bodega",
    pitch: "A warm public-access kiosk where TV, radio, chat, arcade, and links feel like a neighborhood internet counter.",
    audience: "Small communities, art collectives, streamers, web-radio makers",
    signature: "Channel shelf, bulletin ticker, call-in room, and a tiny admin hatch.",
    react95Binding: "React95 app bars and menu lists make the kiosk feel instantly operable despite the maximal personality.",
    usabilityRule: "Public actions are separated from signed-in creator/admin controls.",
    risk: "Public/creator/admin boundaries must stay unmistakable.",
    primaryAction: "Go live locally",
    secondaryAction: "Queue channel item",
    accent: "#006b5b",
    accent2: "#e2b13c",
    ink: "#16140e",
    paper: "#f3ecd6",
    chrome: "#cfc4a4",
    features: ["live", "w", "arcade", "studio", "message", "skywire", "domains", "admin"],
    workflow: ["Pick channel", "Queue media", "Open call-in room", "Moderate bulletin"],
    saleNote: "This makes the indie web feel communal again while keeping wtfOS route/access discipline visible.",
  },
  {
    id: "hypercard-orchard",
    category: "indie",
    mood: "orchard",
    name: "Hypercard Orchard",
    shortName: "Orchard",
    pitch: "A stack-card wtfOS where every app is a card, every card can link, publish, remix, or become a site object.",
    audience: "Hypermedia authors, toolmakers, zine publishers",
    signature: "Card stacks, backlinks, stamps, and publish-ready bundles.",
    react95Binding: "React95 tabs, group boxes, and windows create the classic card-stack structure with modern React state.",
    usabilityRule: "Cards are expressive views over real app objects, not a second secret navigation system.",
    risk: "Needs strong object naming to avoid lost-in-a-stack syndrome.",
    primaryAction: "Create linked card",
    secondaryAction: "Bundle for site",
    accent: "#5a4aa3",
    accent2: "#bc5b30",
    ink: "#191827",
    paper: "#f0edf6",
    chrome: "#cfc9df",
    features: ["studio", "domains", "map", "pinning", "w", "command", "arcade", "recovery"],
    workflow: ["Choose stack", "Link object", "Preview backlinks", "Publish bundle"],
    saleNote: "This is the poetic option: the OS becomes a weird but usable personal knowledge and publishing machine.",
  },
  {
    id: "pocket-mission-control",
    category: "mobile",
    mood: "pocket",
    name: "Pocket Mission Control",
    shortName: "Pocket",
    pitch: "A thumb-first wtfOS that treats mobile as command triage, not a shrunken desktop.",
    audience: "Users checking status, messages, wallets, and jobs on the move",
    signature: "Bottom action rail, swipeable app stacks, urgent state cards.",
    react95Binding: "React95 panels and buttons remain, but windows collapse into stacked mobile task cards.",
    usabilityRule: "One primary action per screen; no hover-only desktop affordances.",
    risk: "Some desktop creativity tools need handoff to larger workspaces.",
    primaryAction: "Handle next task",
    secondaryAction: "Open desktop handoff",
    accent: "#0a6d8f",
    accent2: "#d94f38",
    ink: "#0f1a1f",
    paper: "#edf4f5",
    chrome: "#c6d8de",
    features: ["mission", "message", "wallet", "live", "w", "recovery", "command", "domains"],
    workflow: ["See next task", "Approve or defer", "Send quick reply", "Handoff heavy work"],
    saleNote: "The mobile option that keeps wtfOS useful day-to-day without pretending phones are desktops.",
  },
  {
    id: "live-pocket-studio",
    category: "mobile",
    mood: "broadcast",
    name: "Live Pocket Studio",
    shortName: "Live",
    pitch: "Mobile-first live rooms, short updates, stage status, media capture, and post-show publishing in one phone surface.",
    audience: "Hosts, cohosts, mobile creators, event staff",
    signature: "Stage card, chat strip, camera/source preflight, publish recap stack.",
    react95Binding: "React95 buttons and panels provide deliberate capture controls instead of glossy social-app ambiguity.",
    usabilityRule: "Media state is always explicit: source, audience, room, permission, and recording status.",
    risk: "Needs strict sandbox and permission copy before real camera/wallet operations.",
    primaryAction: "Start room check",
    secondaryAction: "Publish recap",
    accent: "#9c243e",
    accent2: "#266a63",
    ink: "#211115",
    paper: "#f5eef0",
    chrome: "#dcc9ce",
    features: ["live", "studio", "w", "skywire", "pinning", "message", "mission", "admin"],
    workflow: ["Check room", "Pick media source", "Host stage", "Publish recap"],
    saleNote: "This makes wtfOS feel like a live operations tool for creators, not only a desktop toy.",
  },
  {
    id: "chain-wallet-deck",
    category: "mobile",
    mood: "wallet",
    name: "Chain Wallet Deck",
    shortName: "Wallet",
    pitch: "A mobile deck for wallet identity, balances, listings, domain proofs, and safe chain actions.",
    audience: "Collectors, traders, creators approving work away from desktop",
    signature: "Swipeable proof cards with hard network and account boundaries.",
    react95Binding: "React95 cards and controls give the deck chunky, readable confirmation surfaces.",
    usabilityRule: "No chain action hides network, account, cost, target, or recovery state.",
    risk: "Must resist turning into a generic wallet clone.",
    primaryAction: "Verify wallet state",
    secondaryAction: "Open market card",
    accent: "#315ca8",
    accent2: "#a45b21",
    ink: "#111b2c",
    paper: "#eef1f7",
    chrome: "#cbd2e1",
    features: ["wallet", "market", "domains", "macaroni", "pinning", "tezos", "recovery", "command"],
    workflow: ["Review identity", "Check network", "Approve safe action", "Save proof"],
    saleNote: "This is the mobile trust option: fewer toys, more confidence.",
  },
  {
    id: "command-rail-os",
    category: "ops",
    mood: "command",
    name: "Command Rail OS",
    shortName: "Command",
    pitch: "An operation-first interface where search, commands, breadcrumbs, and object status drive the GUI.",
    audience: "Power users, admins, support, paired-agent operators",
    signature: "Permanent command rail with object-aware results and route-safe launch.",
    react95Binding: "React95 windows become results and inspectors; the command rail is the OS spine.",
    usabilityRule: "Search never bypasses access gates and every result says why it is available.",
    risk: "Needs excellent keyboard and empty-state behavior to feel humane.",
    primaryAction: "Run safe command",
    secondaryAction: "Inspect object",
    accent: "#2d4c73",
    accent2: "#b8672b",
    ink: "#0f1720",
    paper: "#eef0f2",
    chrome: "#ccd1d7",
    features: ["command", "mission", "terminal", "admin", "recovery", "mcp", "map", "desktop"],
    workflow: ["Search", "Inspect gate", "Run command", "Open owner window"],
    saleNote: "This is the strongest ease-first design for people who already know what they want to do.",
  },
  {
    id: "recovery-console-first",
    category: "ops",
    mood: "recovery",
    name: "Recovery Console First",
    shortName: "Recovery",
    pitch: "A wtfOS that starts from health, repair, and safe recovery paths before showing decorative desktop personality.",
    audience: "New users, support staff, anyone recovering wallet/media/session issues",
    signature: "Status matrix, repair buttons, recent failure lane, plain-language diagnosis.",
    react95Binding: "React95 group boxes and controls make repair actions feel concrete and reversible.",
    usabilityRule: "When degraded, repair paths outrank navigation and novelty.",
    risk: "Can feel clinical if success states do not restore delight.",
    primaryAction: "Fix highest-risk issue",
    secondaryAction: "Export report",
    accent: "#4a6f3a",
    accent2: "#b84436",
    ink: "#131b12",
    paper: "#eff3eb",
    chrome: "#cdd8c8",
    features: ["recovery", "wallet", "pinning", "desktop", "mission", "admin", "command", "mcp"],
    workflow: ["Read diagnosis", "Run safe fix", "Confirm restored", "Return to task"],
    saleNote: "This is the most humane option for reducing support burden and onboarding anxiety.",
  },
  {
    id: "role-runbook-workspace",
    category: "ops",
    mood: "runbook",
    name: "Role Runbook Workspace",
    shortName: "Runbook",
    pitch: "A role-aware task board where wtfOS assembles the right UI for creator, collector, admin, host, or agent work.",
    audience: "Mixed teams, events, support desks, hosted creator programs",
    signature: "Role switcher, runbook lane, durable side-effect checklist, owner app handoffs.",
    react95Binding: "React95 windows and tabs frame procedural work without hiding the OS underneath.",
    usabilityRule: "The GUI follows the runbook instead of forcing users to remember app topology.",
    risk: "Runbooks need maintenance or they drift from real feature behavior.",
    primaryAction: "Continue role runbook",
    secondaryAction: "Open owner app",
    accent: "#5a5474",
    accent2: "#4b7b55",
    ink: "#1a1721",
    paper: "#f0eef4",
    chrome: "#d2cfdb",
    features: ["mission", "admin", "studio", "macaroni", "live", "wallet", "domains", "recovery"],
    workflow: ["Choose role", "Follow next step", "Verify side effect", "Hand off owner app"],
    saleNote: "This is the easiest wtfOS for teams because it turns app sprawl into guided work.",
  },
];

export const utilityShortcuts = [
  { label: "Search routes", icon: Search },
  { label: "Open Home", icon: Home },
  { label: "Settings", icon: Settings },
  { label: "Notifications", icon: Bell },
  { label: "Refresh status", icon: RefreshCw },
  { label: "Launch lab", icon: Rocket },
  { label: "Review logs", icon: ClipboardList },
  { label: "Check automation", icon: Zap },
  { label: "Read docs", icon: FileText },
  { label: "Theme surface", icon: Palette },
  { label: "Mobile proof", icon: Smartphone },
  { label: "System layers", icon: Layers },
];

export const statusIcon: Record<WtfFeature["status"], LucideIcon> = {
  ready: CheckCircle2,
  syncing: Activity,
  attention: Shield,
  offline: Lock,
};
