export {
  ARTIFACT_ICON_SIZE,
  CURSOR_TOOL_TRAY_SIZE,
  FAN_SIZE,
  JUKEBOX_H,
  JUKEBOX_W,
  LIGHT_SIZE,
  MAX_DESKTOP_ITEMS,
  MOP_SIZE,
  PAPER_SHREDDER_H,
  PAPER_SHREDDER_W,
  PORTAL_GUN_H,
  PORTAL_GUN_W,
  PORTAL_H,
  PORTAL_W,
  STICKY_NOTE_H,
  STICKY_NOTE_W,
  TRAIN_CAR_H,
  TRAIN_CAR_W,
  TRAIN_ENGINE_H,
  TRAIN_ENGINE_W,
  TRAIN_KIT_H,
  TRAIN_KIT_W,
  TRAIN_TRACK_H,
  TRAIN_TRACK_W,
  VACUUM_SIZE,
  getDesktopItemCenter,
  getDesktopItemMaterial,
  getDesktopItemRect,
  getDesktopItemScale,
  getDesktopItemSize,
  getScaledDesktopItemSize,
  getSunDesktopPosition,
  isDesktopPlacementTool,
  itemKindForTool,
  lightVariantForTool,
  type CursorToolTrayItem,
  type DesktopItemKind,
  type DesktopItemState,
  type DesktopLightVariant,
  type GenericDesktopArtifactItem,
  type HangingLightItem,
  type JukeboxItem,
  type MopItem,
  type PaperShredderItem,
  type PortalGunItem,
  type PortalItem,
  type StickyNoteItem,
  type StickyNoteMark,
  type StickyNoteStroke,
  type TinyFanItem,
  type TrainCarItem,
  type TrainCarVariant,
  type TrainEngineItem,
  type TrainEngineVariant,
  type TrainKitBoxItem,
  type TrainTrackPieceItem,
  type TrainTrackShape,
  type VacuumItem,
} from "./model";
export { normalizeDesktopItems } from "./storage";
export { DesktopItemActors } from "./ItemActors";
export {
  createGenericDesktopArtifact,
  createDesktopArtifactItem,
  createDesktopItemForTool,
  useDesktopItemActions,
  type DesktopArtifactItemKind,
  type DesktopArtifactTool,
} from "./useDesktopItemActions";
export { useDesktopArtifacts } from "./useDesktopArtifacts";
export { useDesktopItemSimulation } from "./useDesktopItemSimulation";
