import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "fs";

test("Skywire routes strip OAuth secrets from account responses", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  assert.match(route, /export function safeAtprotoAccount/);
  assert.match(route, /hasEncryptedTokens/);
  assert.doesNotMatch(route, /encryptedAccessToken:\s*account\.encryptedAccessToken/);
  assert.doesNotMatch(route, /encryptedRefreshToken:\s*account\.encryptedRefreshToken/);
  assert.doesNotMatch(route, /encryptedDpopKey:\s*account\.encryptedDpopKey/);
});

test("well-known DID lookup only serves verified WTF-hosted handle claims", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  assert.match(route, /"\/\.well-known\/atproto-did"/);
  assert.match(route, /eq\(atprotoHandleClaims\.verificationStatus,\s*"verified"\)/);
  assert.match(route, /eq\(atprotoHandleClaims\.verificationMethod,\s*"wtf_hosted_subdomain"\)/);
  assert.match(route, /res\.type\("text\/plain"\)\.send\(claim\.did\)/);
});

test("Skywire post claims verify actor DID and emit idempotent challenge events", () => {
  const route = readFileSync("server/routes/skywire.ts", "utf8");
  assert.match(route, /post\.author\.did !== account\.did/);
  assert.match(route, /skywireEventId\("atproto\.post\.claimed"/);
  assert.match(route, /eventType:\s*"atproto\.post\.claimed"/);
});

test("Skywire can register new AT Protocol identities without leaking credentials", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  const oauth = readFileSync("server/features/atproto/oauth.ts", "utf8");
  const canonicalDomain = readFileSync("server/lib/canonical-domain.ts", "utf8");
  assert.match(route, /"\/api\/atproto\/registration\/options"/);
  assert.match(route, /"\/api\/atproto\/permissions\/options"/);
  assert.match(route, /"\/api\/atproto\/register\/phone-verification"/);
  assert.match(route, /"\/api\/atproto\/register"/);
  assert.match(route, /"\/api\/atproto\/oauth\/start"/);
  assert.match(route, /pendingAtprotoOAuthStates/);
  assert.match(route, /await rememberAtprotoOAuthState\(oauthState\)/);
  assert.match(route, /await atprotoOAuthStateForCallback\(req,\s*callbackState\)/);
  assert.match(route, /const callbackState = params\.get\("state"\)/);
  assert.match(route, /atprotoOAuthAppStateKeyForCallback\(callbackState\)/);
  assert.match(route, /loadAtprotoOAuthPendingState<AtprotoOAuthPendingState>\(appStateKey\)/);
  assert.match(route, /rememberAtprotoOAuthPendingState\(value\.state,\s*value,\s*value\.startedAt\)/);
  assert.match(route, /deleteAtprotoOAuthStateFamily\(state\)/);
  assert.match(route, /popupCompletionPage/);
  assert.match(route, /BroadcastChannel/);
  assert.match(route, /postMessage\(message/);
  assert.match(route, /chatEnabled:\s*Boolean\(payload\.chatEnabled\)/);
  assert.match(route, /verifiedParams\.set\("requestedScope"/);
  assert.match(route, /returnPathWithQuery\(returnTo,\s*parsed\)/);
  assert.match(route, /allowed\.includes\(parsed\.pathname\)/);
  assert.match(route, /origin\?:\s*string/);
  assert.match(route, /const origin = requestOrigin\(req\)/);
  assert.match(route, /origin,\s*\n\s*startedAt: Date\.now\(\)/);
  assert.match(route, /const returnOrigin = safeOAuthReturnOrigin\(sessionState\.origin,\s*req\)/);
  assert.match(route, /callbackOrigin === returnOrigin/);
  assert.match(route, /originUrl\(returnOrigin,\s*returnPathWithQuery\(returnTo,\s*parsed\)\)/);
  assert.match(route, /originUrl\(origin,\s*returnPathWithQuery\(returnTo,\s*query\)\)/);
  assert.match(route, /requestedHandle:\s*handle/);
  assert.match(route, /platformActor:\s*z\.string\(\)\.optional\(\)/);
  assert.match(route, /platformActorIntent:\s*boolean/);
  assert.match(route, /const platformActorIntent = parsed\.data\.platformActor === "1" \|\| parsed\.data\.platformActor === "true"/);
  assert.match(route, /isReservedSkywirePlatformHandle\(handle\) && !platformActorIntent/);
  assert.match(route, /platformActorIntent:\s*appName === "skywire" && platformActorIntent/);
  assert.match(route, /isReservedSkywirePlatformHandle\(returnedHandle\) && !sessionState\.platformActorIntent/);
  assert.match(route, /resolveAtprotoHandleViaPublicResolver\(handle\)/);
  assert.match(route, /atproto_handle_not_found/);
  assert.match(route, /atproto_platform_actor_confirmation_required/);
  assert.match(route, /atproto_chat_account_required/);
  assert.match(route, /atproto_chat_account_mismatch/);
  assert.match(route, /const account = await linkedAccountForUser\(user\.id\)/);
  assert.match(route, /resolveCanonicalPublicOrigin/);
  assert.match(oauth, /resolveCanonicalPublicOrigin/);
  assert.match(oauth, /canonicalizePlatformUrl\(process\.env\.ATPROTO_CLIENT_ID_URL\)/);
  assert.doesNotMatch(oauth, /process\.env\.ATPROTO_PUBLIC_BASE_URL\s*\|\|\s*\n\s*process\.env\.PUBLIC_SITE_URL/);
  assert.match(canonicalDomain, /WTFOS_GAMESHOW_DOMAIN/);
  assert.match(canonicalDomain, /resolveCanonicalPublicOrigin/);
  assert.match(canonicalDomain, /canonicalDomainRedirectMiddleware/);
  assert.doesNotMatch(route, /const account = linkedAccount && !isReservedSkywirePlatformHandle\(linkedAccount\.handle\) \? linkedAccount : null/);
  assert.doesNotMatch(route, /publicBaseUrl\(\)\}\$\{returnPathWithQuery\(returnTo,\s*parsed\)\}/);
  assert.doesNotMatch(route, /publicBaseUrl\(\)\}\$\{returnTo\}\?error=atproto_oauth_start/);
  assert.match(route, /issues:\s*parsed\.error\.issues\.map/);
  assert.match(route, /normalizeRegistrationHandle/);
  assert.match(route, /atproto_oauth_start/);
  assert.match(route, /requestPhoneVerification/);
  assert.match(route, /verificationPhone/);
  assert.match(route, /verificationCode/);
  assert.match(route, /externalSignupUrlForPds/);
  assert.match(route, /phoneVerificationModeForPds/);
  assert.match(route, /external_signup_required/);
  assert.match(route, /phone verification not enabled/);
  assert.match(route, /maskedPhone/);
  assert.match(route, /new AtpAgent\(\{ service: pdsUrl \}\)/);
  assert.match(route, /agent\.createAccount\(/);
  assert.match(route, /pdsRegistrationErrorResponse/);
  assert.match(route, /InvalidPhoneVerification/i);
  assert.match(route, /PDS registration failed/);
  assert.match(route, /\[skywire\] PDS registration rejected/);
  assert.match(route, /persistCredentialSessionForDid/);
  assert.match(route, /takePendingOAuthSessionForDid/);
  assert.match(route, /requestedScope/);
  assert.match(route, /eventType:\s*"atproto\.permission_tier\.selected"/);
  assert.match(route, /eventType:\s*"atproto\.chat_permission\.toggled"/);
  assert.match(route, /oauthRequestedScopes/);
  assert.match(route, /oauthPermissionTier/);
  assert.match(route, /oauthChatEnabled/);
  assert.match(route, /resolvedChatEnabled/);
  assert.match(route, /requestedActor = String\(sessionState\.requestedHandle \|\| ""\)\.trim\(\)/);
  assert.match(route, /requestedHandle = isAtprotoDid\(requestedActor\) \? "" : normalizeAtHandle\(requestedActor\)/);
  assert.match(route, /returnedHandle = normalizeAtHandle\(profile\.data\.handle \|\| ""\)/);
  assert.match(route, /requestedActor !== session\.did/);
  assert.match(route, /requestedHandle && returnedHandle && requestedHandle !== returnedHandle/);
  assert.match(route, /existingForUser\.did !== session\.did/);
  assert.match(route, /refused chat OAuth upgrade for non-canonical account/);
  assert.match(route, /linkedAccountForUserDid\(resolvedUserId,\s*session\.did\)/);
  assert.match(route, /oauthChatEnabled:\s*resolvedChatEnabled/);
  assert.match(route, /resolveAtprotoOAuthGrantState/);
  assert.match(route, /oauthScopes:\s*grantedScope/);
  assert.match(route, /if \(!storedSession\)/);
  assert.match(route, /missing the SDK saved session/);
  assert.match(route, /persistOAuthSessionForDid\(session\.did,\s*storedSession,\s*\{/);
  assert.doesNotMatch(route, /storedSession \?\? \(session as any\)/);
  assert.doesNotMatch(route, /if \(!req\.isAuthenticated\?\.\(\) \|\| !sessionState\?\.userId\)/);
  assert.match(route, /buildSkywireAtprotoScope/);
  assert.match(route, /normalizeSkywirePermissionTier/);
  assert.match(route, /new Agent\(session\)/);
  assert.match(route, /eventType:\s*"atproto\.account\.registered"/);
  assert.match(oauth, /persistCredentialSessionForDid/);
  assert.match(oauth, /ATPROTO_MAX_SCOPE/);
  assert.match(oauth, /buildSkywireAtprotoMaxScope/);
  assert.match(oauth, /atprotoAccountCapabilities/);
  assert.match(oauth, /accountHasAtprotoCapability/);
  assert.match(oauth, /if \(account\?\.oauthChatEnabled\) capabilities\.add\("chat"\)/);
  assert.match(oauth, /resolveAtprotoOAuthGrantState/);
  assert.match(oauth, /ATPROTO_CHAT_SCOPE/);
  assert.match(oauth, /atprotoOauthStates/);
  assert.match(oauth, /ATPROTO_OAUTH_STATE_TTL_MS/);
  assert.match(oauth, /rememberAtprotoOAuthSdkState/);
  assert.match(oauth, /loadAtprotoOAuthSdkState/);
  assert.match(oauth, /atprotoOAuthAppStateKeyForCallback/);
  assert.match(oauth, /appStateKey,\s*\n\s*payload: value/);
  assert.match(oauth, /stateStore:\s*\{\s*async get\(key: string\)\s*\{\s*return loadAtprotoOAuthSdkState\(key\);/);
  assert.match(oauth, /pendingOAuthSessions/);
  assert.match(oauth, /pendingOAuthSessions\.get\(key\)/);
  assert.match(oauth, /didBelongsToReservedSkywirePlatformActor/);
  assert.match(oauth, /options\.accountId == null && options\.userId == null/);
  assert.match(oauth, /const sdkStoreWrite = options\.accountId == null && options\.userId == null/);
  assert.match(oauth, /else if \(sdkStoreWrite\)/);
  assert.match(oauth, /assertPersistableOAuthSession/);
  assert.match(oauth, /oauth_session_persistence_material_missing/);
  assert.match(oauth, /takePendingOAuthSessionForDid/);
  assert.match(oauth, /iss:\s*oauthIssuerForRow\(row\)/);
  assert.match(oauth, /sub:\s*row\.did/);
  assert.match(oauth, /aud:\s*oauthResourceForRow\(row\)/);
  assert.match(oauth, /authMethod:\s*\{\s*method:\s*"none"\s*\}/);
  assert.match(oauth, /tokenSet\.expires_at\s*=\s*new Date\(row\.tokenExpiresAt\)\.toISOString\(\)/);
  assert.match(oauth, /atprotoAccountSessionSummary/);
  assert.match(oauth, /AtprotoSessionUnavailableError/);
  assert.match(oauth, /oauthAudience/);
  assert.match(oauth, /\.\.\.\(fields\.oauthAudience \? \{ pdsUrl:\s*fields\.oauthAudience \} : \{\}\)/);
  assert.match(oauth, /keeping DB tokens until explicit unlink/);
  assert.doesNotMatch(oauth, /encryptedAccessToken:\s*null,[\s\S]*encryptedRefreshToken:\s*null,[\s\S]*encryptedDpopKey:\s*null/);
  assert.match(oauth, /credentialAgent\.resumeSession/);
  assert.match(oauth, /return new Agent\(session\)/);
  assert.doesNotMatch(oauth, /session\.fetchHandler\.bind\(session\)/);
  assert.doesNotMatch(route, /sessionGetter\.getStored/);
});

test("Skywire imports Bluesky trending topics as a read-only hot lane", () => {
  const route = readFileSync("server/routes/skywire.ts", "utf8");
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  const nav = readFileSync("client/src/features/skywire/skywire-nav.ts", "utf8");
  const permissions = readFileSync("shared/atproto-permissions.ts", "utf8");

  assert.match(route, /"\/api\/skywire\/trending-topics"/);
  assert.match(route, /getTrendingTopics/);
  assert.match(route, /source:\s*"app\.bsky\.unspecced\.getTrendingTopics"/);
  assert.match(route, /personalizesWithViewer:\s*Boolean\(viewer\)/);
  assert.match(route, /"skywire\.trending_topics\.viewed"/);
  assert.match(page, /function HotPanel/);
  assert.match(page, /data-skywire-hot-topic="true"/);
  assert.match(page, /feedType="search"/);
  assert.match(nav, /\|\s*"hot"/);
  assert.match(nav, /\{ id: "hot", label: "Hot"/);
  assert.match(permissions, /app\.bsky\.unspecced\.getTrendingTopics/);
});

test("Skywire registration UI only offers official signup handoff", () => {
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  const shell = readFileSync("client/src/features/skywire/SkywireShell.tsx", "utf8");
  assert.match(page, /Create a Bluesky account in the official app/);
  assert.match(page, /Choose Skywire permissions/);
  assert.match(page, /Be Safe/);
  assert.match(page, /Be Social/);
  assert.match(page, /Be Heard/);
  assert.match(page, /Be Bold/);
  assert.match(page, /Bluesky Chat \/ DMs/);
  assert.match(page, /Enable Chat Add-on/);
  assert.match(page, /skywire-permission-tier/);
  assert.match(page, /skywire-chat-permission/);
  assert.match(page, /buildSkywireAtprotoScope/);
  assert.match(page, /Change permissions & reconnect/);
  assert.match(shell, /Welcome to Skywire/);
  assert.match(page, /connectHandle/);
  assert.match(page, /returnTo:\s*"\/skywire\?tab=account"/);
  assert.match(page, /skywire:atproto-oauth-pending/);
  assert.match(page, /skywireOAuthCompletionPayload/);
  assert.match(page, /SKYWIRE_OAUTH_CHANNEL\s*=\s*"skywire:atproto-oauth"/);
  assert.match(page, /BroadcastChannel\(SKYWIRE_OAUTH_CHANNEL\)/);
  assert.match(page, /shareSkywireOAuthCompletion\(completion\);\s*\n\s*try/);
  assert.doesNotMatch(page, /if \(isOAuthPopupWindow \|\| window\.opener\)\s*\{\s*shareSkywireOAuthCompletion\(completion\);/);
  assert.match(page, /refetchQueries\(\{\s*queryKey:\s*\["skywire",\s*"me"\]/);
  assert.match(page, /fetchCanonicalAtprotoAccount/);
  assert.match(page, /Skywire has not received the durable chat permission yet/);
  assert.match(page, /durableOAuthCompletionKeysRef/);
  assert.match(page, /replaceSkywireTabUrl/);
  assert.match(page, /if \(!event\.newValue\) return/);
  assert.match(page, /window\.location\.assign\(url\)/);
  assert.match(page, /SKYWIRE_RESERVED_PLATFORM_HANDLES/);
  assert.match(page, /skywire-platform-actor-confirmation/);
  assert.match(page, /platformActorIntent/);
  assert.match(page, /params\.set\("platformActor",\s*"1"\)/);
  assert.match(page, /isReservedSkywirePlatformHandle\(connectHandle\) && !platformActorIntent/);
  assert.match(page, /Confirm the platform actor connection before continuing to Bluesky OAuth/);
  assert.doesNotMatch(page, /Skywire will not connect the shared WTF Gameshow Bluesky actor\. Enter your own Bluesky handle/);
  assert.match(page, /Enable the Chat Add-on only after your own Bluesky account is connected here/);
  assert.doesNotMatch(page, /window\.open\("about:blank",\s*SKYWIRE_OAUTH_POPUP_NAME/);
  assert.doesNotMatch(page, /popup:\s*"1"/);
  assert.doesNotMatch(page, /popup\.opener\s*=\s*null/);
  assert.match(page, /skywire:atproto-linked/);
  assert.match(page, /skywire:atproto-error/);
  assert.match(page, /atproto_oauth_start/);
  assert.match(page, /atproto_handle_not_found/);
  assert.match(page, /Open Bluesky signup/);
  assert.match(page, /window\.open\(externalSignupUrl/);
  assert.doesNotMatch(page, /Register New AT Identity/);
  assert.doesNotMatch(page, /Register AT Identity/);
  assert.doesNotMatch(page, /skywire-registration-email/);
  assert.doesNotMatch(page, /skywire-registration-password/);
  assert.doesNotMatch(page, /skywire-registration-phone/);
  assert.doesNotMatch(page, /Send Phone Code/);
});

test("Skywire exposes a standalone OVOID-style AT login surface", () => {
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  const app = readFileSync("client/src/App.tsx", "utf8");
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  const passport = readFileSync("server/auth/passport.ts", "utf8");
  const pageDefs = readFileSync("client/src/routes/page-defs.ts", "utf8");
  const browserRoutes = readFileSync("shared/wtf-browser-routes.ts", "utf8");
  const access = readFileSync("server/lib/wtf-access.ts", "utf8");
  const caddy = readFileSync("Caddyfile", "utf8");

  assert.match(page, /data-skywire-standalone-login="true"/);
  assert.match(page, /Handle or DID/);
  assert.match(page, /standalone:\s*"1"/);
  assert.match(page, /skywireStandaloneReturnTo/);
  assert.match(page, /enabled:\s*Boolean\(user\)/);
  assert.match(app, /skywire\.wtfos\.app/);
  assert.match(route, /standalone\s*=\s*appName === "skywire"/);
  assert.match(route, /findOrCreateSkywireStandaloneUser/);
  assert.match(route, /role:\s*"test_subject"/);
  assert.match(route, /loginRequestUser/);
  assert.match(route, /"https:\/\/skywire\.wtfos\.app"/);
  assert.match(passport, /WTFOS_SESSION_COOKIE_DOMAIN/);
  assert.match(passport, /`\.\$\{WTFOS_PLATFORM_DOMAIN\}`/);
  assert.match(pageDefs, /pattern:\s*"\/skywire"[\s\S]*auth:\s*false/);
  assert.match(browserRoutes, /\{\s*pattern:\s*"\/skywire",\s*auth:\s*false/);
  assert.match(access, /Standalone AT Protocol login surface/);
  assert.match(caddy, /wtfos\.app,[^{]*skywire\.wtfos\.app,[^{]*dues\.wtfgameshow\.app\s*\{/);
});

test("Skywire bridge exposes preferred Tezos identity and detected .tez domains", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  const helper = readFileSync("server/lib/user-tezos-identity.ts", "utf8");
  const wallets = readFileSync("server/routes/wallets.ts", "utf8");
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  assert.match(route, /resolveUserTezosIdentity/);
  assert.match(route, /tezosIdentity/);
  assert.match(helper, /reverseTezosDomain/);
  assert.match(helper, /ownedTezosDomains/);
  assert.match(helper, /preferredTezosDomain/);
  assert.match(wallets, /"\/api\/wallets\/:id\/tezos-domain"/);
  assert.match(wallets, /resolveTezosDomainsIdentity/);
  assert.match(wallets, /ownedTezosDomains/);
  assert.match(page, /Preferred Tezos identity/);
  assert.match(page, /Use preferred \.tez/);
});

test("Skywire exposes app-grade actor discovery and WTF-native AT repo signals", () => {
  const route = readFileSync("server/routes/skywire.ts", "utf8");
  const oauth = readFileSync("server/features/atproto/oauth.ts", "utf8");
  const events = readFileSync("server/features/atproto/events.ts", "utf8");
  const permissions = readFileSync("shared/atproto-permissions.ts", "utf8");
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  assert.match(route, /feedType:\s*z\.enum\(\["home",\s*"following"/);
  assert.match(route, /"market"/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.getTimeline"/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.searchPosts"/);
  assert.match(route, /SKYWIRE_MARKET_FEED_DOMAINS/);
  assert.match(route, /SKYWIRE_MARKET_FEED_SEARCH_TERMS/);
  assert.match(route, /getSearchAtprotoAgent/);
  assert.match(route, /domain,\s*\n\s*sort:\s*"latest"/);
  assert.match(route, /Skywire Market Feed search is unavailable right now/);
  assert.match(route, /upstreamAvailable:\s*false/);
  assert.match(route, /richTextFacetLinkUris/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.getAuthorFeed"/);
  assert.match(route, /officialTezosAtprotoActors/);
  assert.match(route, /source:\s*"skywire\.curatedTezosAuthorFeeds"/);
  assert.match(route, /"tezos\.com"/);
  assert.match(route, /"objkt\.com"/);
  assert.match(route, /"tezoscommons\.org"/);
  assert.match(route, /"thetezoscommunity\.bsky\.social"/);
  assert.match(route, /"\/api\/skywire\/token-link"/);
  assert.match(route, /resolveSkywireTokenMarket/);
  assert.match(route, /"\/api\/skywire\/tezos-vault"/);
  assert.match(route, /fetchObjktCreatedTokens/);
  assert.match(route, /embedTitle/);
  assert.match(route, /embedThumbUrl/);
  assert.match(route, /uploadSkywireExternalThumb/);
  assert.match(route, /fetchSafeHttp/);
  assert.match(route, /agent\.uploadBlob/);
  assert.match(route, /\$type:\s*"app\.bsky\.embed\.external"/);
  assert.match(route, /"\/api\/skywire\/events"/);
  assert.match(route, /skywire\.token_link\.resolved/);
  assert.match(route, /skywire\.token_listing\.buy_requested/);
  assert.match(route, /skywire\.tezos_vault\.viewed/);
  assert.match(route, /officialWtfAtprotoActor/);
  assert.match(route, /"\/api\/skywire\/actors\/recommended"/);
  assert.match(route, /"\/api\/skywire\/actors\/follows"/);
  assert.match(route, /"\/api\/skywire\/actors\/suggestions"/);
  assert.match(route, /"\/api\/skywire\/follow"/);
  assert.match(route, /agent\.follow\(parsed\.data\.did\)/);
  assert.match(route, /eventType:\s*"atproto\.actor\.followed"/);
  assert.match(route, /source:\s*"app\.bsky\.graph\.getFollows"/);
  assert.match(route, /source:\s*"skywire\.peerFollowGraph"/);
  assert.match(route, /agent\.getFollows\(/);
  assert.match(route, /wtf\.atproto_accounts/);
  assert.match(route, /ne\(atprotoAccounts\.userId,\s*user\.id\)/);
  assert.match(route, /isAtprotoSessionUnavailableError/);
  assert.match(route, /sessionFallback/);
  assert.match(route, /action:\s*err\.action/);
  assert.match(oauth, /action = "reconnect_atproto"/);
  assert.match(oauth, /DEFAULT_ATPROTO_APPVIEW\s*=\s*"https:\/\/api\.bsky\.app"/);
  assert.match(oauth, /DEFAULT_ATPROTO_SEARCH_APPVIEW\s*=\s*"https:\/\/api\.bsky\.app"/);
  assert.match(oauth, /ATPROTO_SEARCH_APPVIEW/);
  assert.match(route, /normalizeFeedItem/);
  assert.match(route, /normalizePostView/);
  assert.match(route, /normalizeQuotedRecord/);
  assert.match(route, /normalizeRoomMessageRecord/);
  assert.match(route, /normalizeStageBroadcastRecord/);
  assert.match(route, /normalizeThreadNode/);
  assert.match(route, /normalizeChatConvo/);
  assert.match(route, /normalizeChatMessage/);
  assert.match(route, /chatMediaAttachmentSchema/);
  assert.match(route, /resolveSkywireChatMediaAttachments/);
  assert.match(route, /skywireChatMediaFileToken/);
  assert.match(route, /parseSkywireChatMessageText/);
  assert.match(route, /serveStoredMediaFile/);
  assert.match(route, /embedVideo/);
  assert.match(route, /"\/api\/skywire\/post\/thread"/);
  assert.match(route, /getPostThread/);
  assert.match(route, /eventType:\s*"atproto\.thread\.viewed"/);
  assert.match(route, /"\/api\/skywire\/quote"/);
  assert.match(route, /"\/api\/skywire\/chats"/);
  assert.match(route, /"\/api\/skywire\/chats\/resolve"/);
  assert.match(route, /"\/api\/skywire\/chats\/:convoId\/messages"/);
  assert.match(route, /"\/api\/skywire\/chat-media\/:mediaId\/file"/);
  assert.match(route, /"\/api\/skywire\/pipelines"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/history"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/dispatch"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/dispatch-batch"/);
  assert.match(route, /skywire\.systemEventPipelines/);
  assert.match(route, /challengeSystemEvents/);
  assert.match(route, /ingestSystemEvent/);
  assert.match(route, /skywire\.pipeline\.tv_queued/);
  assert.match(route, /skywire\.pipeline\.studio_queued/);
  assert.match(route, /skywire\.pipeline\.rat_race_queued/);
  assert.match(route, /\$type:\s*"app\.bsky\.embed\.record"/);
  assert.match(route, /eventType:\s*"atproto\.post\.quoted"/);
  assert.match(route, /eventType:\s*"atproto\.chat\.message_sent"/);
  assert.match(route, /mediaIds:\s*mediaAttachments\.map/);
  assert.match(route, /mediaCount:\s*mediaAttachments\.length/);
  assert.match(route, /SKYWIRE_ROOM_MESSAGE_COLLECTION/);
  assert.match(route, /SKYWIRE_STAGE_BROADCAST_COLLECTION/);
  assert.match(route, /timeline\.data\.cursor/);
  assert.match(route, /feed\.data\.cursor/);
  assert.match(route, /filter:\s*"posts_with_replies"/);
  assert.match(route, /author\?\.did\.toLowerCase\(\) === actorKey/);
  const wtfLiveRoute = readFileSync("server/routes/wtf-live.ts", "utf8");
  const wtfLiveApp = readFileSync("client/src/features/wtf-live/WtfLiveApp.tsx", "utf8");
  const nav = readFileSync("client/src/features/skywire/skywire-nav.ts", "utf8");
  const wtfLiveNav = readFileSync("client/src/features/wtf-live/wtf-live-nav.ts", "utf8");
  const shell = readFileSync("client/src/features/skywire/SkywireShell.tsx", "utf8");
  assert.match(wtfLiveRoute, /"\/api\/wtf-live\/status"/);
  assert.match(wtfLiveRoute, /"\/api\/wtf-live\/rooms"/);
  assert.match(wtfLiveRoute, /"\/api\/wtf-live\/rooms\/:roomId\/messages"/);
  assert.match(wtfLiveRoute, /"\/api\/wtf-live\/stages"/);
  assert.match(wtfLiveRoute, /"\/api\/wtf-live\/stages\/:stageId\/broadcasts"/);
  assert.match(wtfLiveRoute, /eventType:\s*"atproto\.room\.message_sent"/);
  assert.match(wtfLiveRoute, /eventType:\s*"atproto\.stage\.broadcast_sent"/);
  assert.match(wtfLiveRoute, /createWtfLiveRoom/);
  assert.match(wtfLiveRoute, /createWtfLiveStage/);
  assert.match(nav, /\|\s*"home"/);
  assert.match(nav, /\|\s*"actor"/);
  assert.match(nav, /\|\s*"vault"/);
  assert.match(page, /SkywireTokenMarketCard/);
  assert.match(page, /purchaseRatRaceListing/);
  assert.match(page, /SkywireTezosVaultPanel/);
  assert.match(page, /Owned Tokens/);
  assert.match(page, /Created Tokens by Collection/);
  assert.match(page, /groupSkywireCreatedTokens/);
  assert.match(page, /buildSkywireVaultShareText/);
  assert.match(page, /Date Minted/);
  assert.match(page, /Token URL/);
  assert.match(page, /data-skywire-vault-share/);
  assert.match(page, /data-skywire-actor-follow/);
  assert.match(page, /api\.post\("\/api\/skywire\/follow"/);
  assert.match(page, /Choose Be Social or higher to follow this creator from Skywire/);
  assert.match(page, /Post to Bluesky/);
  assert.doesNotMatch(page, /I created/);
  assert.doesNotMatch(page, /I own/);
  assert.match(wtfLiveNav, /overview/);
  assert.match(wtfLiveNav, /rooms/);
  assert.match(wtfLiveNav, /stages/);
  assert.match(shell, /SkywireSidebar/);
  assert.match(shell, /SkywireContextBar/);
  assert.match(page, /ThreadPanel/);
  assert.match(page, /Thread Contract/);
  assert.match(page, /PipelinePanel/);
  assert.match(page, /Pipeline Contract/);
  assert.match(page, /Recent Pipeline Events/);
  assert.match(page, /Send to All Pipelines/);
  assert.match(page, /onPipelineOpen/);
  assert.match(page, /Send to \$\{pipeline\.app\}/);
  assert.match(page, /handoffToWtfLive|wtf-live:pending-quote|WTF LIVE/);
  assert.match(page, /ChatPanel/);
  assert.match(page, /onThreadOpen/);
  assert.match(page, /Reply In Chat/);
  assert.match(page, /Create Group \+ Send|Send To Member/);
  assert.match(page, /ChatQuotePreview/);
  assert.match(page, /QuoteSupertext/);
  assert.match(page, /SkywireChatMedia/);
  assert.match(page, /data-skywire-chat-media/);
  assert.match(page, /Attach Media/);
  assert.match(page, /image\/\*,image\/gif,video\/\*,audio\/\*/);
  assert.match(page, /SkywireVideoEmbedView/);
  assert.match(page, /data-skywire-video-embed/);
  assert.match(page, /ExternalThumb/);
  assert.match(wtfLiveApp, /Send Room Message/);
  assert.match(wtfLiveApp, /Send Broadcast/);
  assert.match(wtfLiveApp, /data-wtf-live-stage-broadcast-send/);
  assert.match(wtfLiveApp, /Create Public Room|Create Private Room/);
  assert.match(wtfLiveApp, /Create Stage/);
  assert.match(page, /onChatQuote/);
  assert.match(page, /onRoomQuote/);
  assert.match(page, /onStageQuote/);
  assert.match(page, /pendingChatQuote/);
  assert.match(page, /pendingChatMembers/);
  assert.match(page, /chatMemberForActor/);
  assert.match(page, /feedType="home"[\s\S]*canUseSocialActions/);
  assert.match(page, /feedType="wtf"[\s\S]*canUseSocialActions/);
  assert.match(page, /feedType="market"[\s\S]*canUseSocialActions/);
  assert.match(page, /ActorFeedPanel/);
  assert.match(page, /onActorSelect/);
  assert.match(page, /Following on Bluesky/);
  assert.match(page, /Suggested by Skywire/);
  assert.match(page, /onActorOpen\(actorFromRecord\(actor\)\)/);
  assert.match(page, /useInfiniteQuery<FeedResponse>/);
  assert.match(page, /useInfiniteQuery<ActorSearchResponse>/);
  assert.match(page, /Load More/);
  assert.match(page, /Load More Follows/);
  assert.match(page, /FeedCard/);
  assert.match(page, /QuotePreview/);
  assert.match(page, /Post Quote/);
  assert.match(page, /"skywire",\s*"actors",\s*"recommended"/);
  assert.match(page, /"skywire",\s*"actors",\s*"follows"/);
  assert.match(page, /"skywire",\s*"actors",\s*"suggestions"/);
  assert.match(page, /No other Skywire users have connected Bluesky yet/);
  assert.match(page, /actor\.did === me\.account\.did/);
  assert.match(route, /"\/api\/skywire\/actors\/search"/);
  assert.match(route, /"\/api\/skywire\/actor\/:actor\/feed"/);
  assert.match(route, /"\/api\/skywire\/follow"/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"socialActions",\s*"be-social"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"compose",\s*"be-heard"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"signals",\s*"be-heard"\)/);
  assert.match(route, /"market\.sale"/);
  assert.match(route, /"broadcast\.live"/);
  assert.match(page, /Signal Starters/);
  assert.match(page, /recent-sale/);
  assert.match(wtfLiveRoute, /requireAtprotoCapability\(account,\s*"rooms",\s*"be-heard"\)/);
  assert.match(wtfLiveRoute, /requireAtprotoCapability\(account,\s*"stages",\s*"be-heard"\)/);
  assert.match(route, /requireSkywireChatCapability\(account\)/);
  assert.match(route, /withProxy\("bsky_chat",\s*"did:web:api\.bsky\.chat"\)/);
  assert.match(route, /atproto_scope_upgrade_required/);
  assert.match(route, /"\/api\/skywire\/profile"/);
  assert.match(permissions, /SKYWIRE_SIGNAL_COLLECTION = "app\.wtfgameshow\.skywire\.signal"/);
  assert.match(permissions, /SKYWIRE_ROOM_MESSAGE_COLLECTION = "app\.wtfgameshow\.skywire\.room\.message"/);
  assert.match(permissions, /SKYWIRE_STAGE_BROADCAST_COLLECTION = "app\.wtfgameshow\.skywire\.stage\.broadcast"/);
  assert.match(permissions, /`repo:\$\{SKYWIRE_ROOM_MESSAGE_COLLECTION\}`/);
  assert.match(permissions, /`repo:\$\{SKYWIRE_STAGE_BROADCAST_COLLECTION\}`/);
  assert.match(route, /com\.atproto\.repo\.createRecord/);
  assert.match(route, /validate:\s*false/);
  assert.match(events, /"atproto\.profile\.updated"/);
  assert.match(events, /"atproto\.actor\.searched"/);
  assert.match(events, /"atproto\.actor\.followed"/);
  assert.match(events, /"atproto\.signal\.published"/);
  assert.match(events, /"atproto\.chat\.message_sent"/);
  assert.match(events, /"atproto\.stage\.broadcast_sent"/);
  assert.match(events, /"atproto\.thread\.viewed"/);
});

test("Profile social surfaces expose Skywire identity links", () => {
  const atprotoRoute = readFileSync("server/routes/atproto.ts", "utf8");
  const route = readFileSync("server/routes/profile.ts", "utf8");
  const page = readFileSync("client/src/pages/Profile.tsx", "utf8");
  const publicPage = readFileSync("client/src/pages/PublicProfile.tsx", "utf8");
  assert.match(route, /atprotoAccounts/);
  assert.match(route, /atprotoHandle/);
  assert.match(atprotoRoute, /"\/api\/atproto\/unlink"/);
  assert.match(atprotoRoute, /eventType:\s*"atproto\.account\.unlinked"/);
  assert.match(page, /<strong style=\{\{ width: 70 \}\}>Skywire:<\/strong>/);
  assert.match(page, /Connect Skywire/);
  assert.match(page, /Open Skywire/);
  assert.match(page, /disconnectSkywireMutation/);
  assert.match(page, /api\.post<\{ ok: true \}>\("\/api\/atproto\/unlink"/);
  assert.match(page, /Disconnect this Skywire AT Protocol identity/);
  assert.match(page, /Failed to disconnect Skywire/);
  assert.match(publicPage, /profile\.atprotoHandle/);
  assert.match(publicPage, /https:\/\/bsky\.app\/profile\/\$\{profile\.atprotoHandle\}/);
});

test("Skywire adapter persists atproto events and calls challenge ingestion", () => {
  const adapter = readFileSync("server/features/atproto/events.ts", "utf8");
  assert.match(adapter, /insert\(atprotoEvents\)/);
  assert.match(adapter, /onConflictDoNothing/);
  assert.match(adapter, /ingestSystemEvent\(/);
});

test("Skywire page is registered as a desktop social app", () => {
  const routes = readFileSync("client/src/routes/page-defs.ts", "utf8");
  assert.match(routes, /pattern:\s*"\/skywire"/);
  assert.match(routes, /title:\s*"Skywire"/);
  assert.match(routes, /group:\s*"social"/);
  assert.match(routes, /desktopIcon:\s*true/);
});
