import test from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "fs";

test("Skywire routes strip OAuth secrets from account responses", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  assert.match(route, /export function safeAtprotoAccount/);
  assert.match(route, /hasEncryptedTokens/);
  assert.doesNotMatch(route, /encryptedAccessToken:\s*account\.encryptedAccessToken/);
  assert.doesNotMatch(route, /encryptedRefreshToken:\s*account\.encryptedRefreshToken/);
  assert.doesNotMatch(route, /encryptedDpopKey:\s*account\.encryptedDpopKey/);
});

test("well-known DID lookup only serves verified WTF-hosted handle claims", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  assert.match(route, /"\/\.well-known\/atproto-did"/);
  assert.match(route, /eq\(atprotoHandleClaims\.verificationStatus,\s*"verified"\)/);
  assert.match(route, /eq\(atprotoHandleClaims\.verificationMethod,\s*"wtf_hosted_subdomain"\)/);
  assert.match(route, /res\.type\("text\/plain"\)\.send\(claim\.did\)/);
});

test("Skywire post claims verify actor DID and emit idempotent challenge events", () => {
  const route = readFileSync("server/routes/skywire.ts", "utf8");
  assert.match(route, /post\.author\.did !== account\.did/);
  assert.match(route, /skywireEventId\("atproto\.post\.claimed"/);
  assert.match(route, /eventType:\s*"atproto\.post\.claimed"/);
});

test("Skywire can register new AT Protocol identities without leaking credentials", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  const oauth = readFileSync("server/features/atproto/oauth.ts", "utf8");
  assert.match(route, /"\/api\/atproto\/registration\/options"/);
  assert.match(route, /"\/api\/atproto\/permissions\/options"/);
  assert.match(route, /"\/api\/atproto\/register\/phone-verification"/);
  assert.match(route, /"\/api\/atproto\/register"/);
  assert.match(route, /"\/api\/atproto\/oauth\/start"/);
  assert.match(route, /popupCompletionPage/);
  assert.match(route, /issues:\s*parsed\.error\.issues\.map/);
  assert.match(route, /normalizeRegistrationHandle/);
  assert.match(route, /atproto_oauth_start/);
  assert.match(route, /requestPhoneVerification/);
  assert.match(route, /verificationPhone/);
  assert.match(route, /verificationCode/);
  assert.match(route, /externalSignupUrlForPds/);
  assert.match(route, /phoneVerificationModeForPds/);
  assert.match(route, /external_signup_required/);
  assert.match(route, /phone verification not enabled/);
  assert.match(route, /maskedPhone/);
  assert.match(route, /new AtpAgent\(\{ service: pdsUrl \}\)/);
  assert.match(route, /agent\.createAccount\(/);
  assert.match(route, /pdsRegistrationErrorResponse/);
  assert.match(route, /InvalidPhoneVerification/i);
  assert.match(route, /PDS registration failed/);
  assert.match(route, /\[skywire\] PDS registration rejected/);
  assert.match(route, /persistCredentialSessionForDid/);
  assert.match(route, /takePendingOAuthSessionForDid/);
  assert.match(route, /requestedScope/);
  assert.match(route, /eventType:\s*"atproto\.permission_tier\.selected"/);
  assert.match(route, /eventType:\s*"atproto\.chat_permission\.toggled"/);
  assert.match(route, /oauthRequestedScopes/);
  assert.match(route, /oauthPermissionTier/);
  assert.match(route, /oauthChatEnabled/);
  assert.match(route, /buildSkywireAtprotoScope/);
  assert.match(route, /normalizeSkywirePermissionTier/);
  assert.match(route, /new Agent\(session\)/);
  assert.match(route, /eventType:\s*"atproto\.account\.registered"/);
  assert.match(oauth, /persistCredentialSessionForDid/);
  assert.match(oauth, /ATPROTO_MAX_SCOPE/);
  assert.match(oauth, /buildSkywireAtprotoMaxScope/);
  assert.match(oauth, /atprotoAccountCapabilities/);
  assert.match(oauth, /accountHasAtprotoCapability/);
  assert.match(oauth, /pendingOAuthSessions/);
  assert.match(oauth, /pendingOAuthSessions\.get\(key\)/);
  assert.match(oauth, /takePendingOAuthSessionForDid/);
  assert.match(oauth, /iss:\s*oauthIssuerForRow\(row\)/);
  assert.match(oauth, /sub:\s*row\.did/);
  assert.match(oauth, /aud:\s*oauthResourceForRow\(row\)/);
  assert.match(oauth, /authMethod:\s*\{\s*method:\s*"none"\s*\}/);
  assert.match(oauth, /tokenSet\.expires_at\s*=\s*new Date\(row\.tokenExpiresAt\)\.toISOString\(\)/);
  assert.match(oauth, /atprotoAccountSessionSummary/);
  assert.match(oauth, /AtprotoSessionUnavailableError/);
  assert.match(oauth, /oauthAudience/);
  assert.match(oauth, /\.\.\.\(fields\.oauthAudience \? \{ pdsUrl:\s*fields\.oauthAudience \} : \{\}\)/);
  assert.match(oauth, /keeping DB tokens until explicit unlink/);
  assert.doesNotMatch(oauth, /encryptedAccessToken:\s*null,[\s\S]*encryptedRefreshToken:\s*null,[\s\S]*encryptedDpopKey:\s*null/);
  assert.match(oauth, /credentialAgent\.resumeSession/);
  assert.match(oauth, /return new Agent\(session\)/);
  assert.doesNotMatch(oauth, /session\.fetchHandler\.bind\(session\)/);
  assert.doesNotMatch(route, /sessionGetter\.getStored/);
});

test("Skywire registration UI only offers official signup handoff", () => {
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  assert.match(page, /Create the Bluesky account in the official flow/);
  assert.match(page, /Choose Skywire Permissions/);
  assert.match(page, /Be Safe/);
  assert.match(page, /Be Social/);
  assert.match(page, /Be Heard/);
  assert.match(page, /Be Bold/);
  assert.match(page, /Bluesky Chat \/ DMs/);
  assert.match(page, /skywire-permission-tier/);
  assert.match(page, /skywire-chat-permission/);
  assert.match(page, /buildSkywireAtprotoScope/);
  assert.match(page, /Change Skywire Permissions/);
  assert.match(page, /connectHandle/);
  assert.match(page, /skywire-atproto-oauth/);
  assert.match(page, /skywire:atproto-linked/);
  assert.match(page, /skywire:atproto-error/);
  assert.match(page, /atproto_oauth_start/);
  assert.match(page, /Open Bluesky Signup/);
  assert.match(page, /window\.open\(externalSignupUrl/);
  assert.doesNotMatch(page, /Register New AT Identity/);
  assert.doesNotMatch(page, /Register AT Identity/);
  assert.doesNotMatch(page, /skywire-registration-email/);
  assert.doesNotMatch(page, /skywire-registration-password/);
  assert.doesNotMatch(page, /skywire-registration-phone/);
  assert.doesNotMatch(page, /Send Phone Code/);
});

test("Skywire bridge exposes preferred Tezos identity and detected .tez domains", () => {
  const route = readFileSync("server/routes/atproto.ts", "utf8");
  const helper = readFileSync("server/lib/user-tezos-identity.ts", "utf8");
  const wallets = readFileSync("server/routes/wallets.ts", "utf8");
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  assert.match(route, /resolveUserTezosIdentity/);
  assert.match(route, /tezosIdentity/);
  assert.match(helper, /reverseTezosDomain/);
  assert.match(helper, /ownedTezosDomains/);
  assert.match(helper, /preferredTezosDomain/);
  assert.match(wallets, /"\/api\/wallets\/:id\/tezos-domain"/);
  assert.match(wallets, /resolveTezosDomainsIdentity/);
  assert.match(wallets, /ownedTezosDomains/);
  assert.match(page, /Preferred Tezos identity/);
  assert.match(page, /Use Preferred \.tez/);
});

test("Skywire exposes app-grade actor discovery and WTF-native AT repo signals", () => {
  const route = readFileSync("server/routes/skywire.ts", "utf8");
  const oauth = readFileSync("server/features/atproto/oauth.ts", "utf8");
  const events = readFileSync("server/features/atproto/events.ts", "utf8");
  const permissions = readFileSync("shared/atproto-permissions.ts", "utf8");
  const page = readFileSync("client/src/pages/Skywire.tsx", "utf8");
  assert.match(route, /feedType:\s*z\.enum\(\["home",\s*"following"/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.getTimeline"/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.searchPosts"/);
  assert.match(route, /source:\s*"app\.bsky\.feed\.getAuthorFeed"/);
  assert.match(route, /officialTezosAtprotoActors/);
  assert.match(route, /source:\s*"skywire\.curatedTezosAuthorFeeds"/);
  assert.match(route, /"tezos\.com"/);
  assert.match(route, /"objkt\.com"/);
  assert.match(route, /"tezoscommons\.org"/);
  assert.match(route, /"thetezoscommunity\.bsky\.social"/);
  assert.match(route, /officialWtfAtprotoActor/);
  assert.match(route, /"\/api\/skywire\/actors\/recommended"/);
  assert.match(route, /"\/api\/skywire\/actors\/follows"/);
  assert.match(route, /"\/api\/skywire\/actors\/suggestions"/);
  assert.match(route, /source:\s*"app\.bsky\.graph\.getFollows"/);
  assert.match(route, /source:\s*"skywire\.peerFollowGraph"/);
  assert.match(route, /agent\.getFollows\(/);
  assert.match(route, /wtf\.atproto_accounts/);
  assert.match(route, /ne\(atprotoAccounts\.userId,\s*user\.id\)/);
  assert.match(route, /isAtprotoSessionUnavailableError/);
  assert.match(route, /sessionFallback/);
  assert.match(route, /action:\s*err\.action/);
  assert.match(oauth, /action = "reconnect_atproto"/);
  assert.match(route, /normalizeFeedItem/);
  assert.match(route, /normalizePostView/);
  assert.match(route, /normalizeQuotedRecord/);
  assert.match(route, /normalizeRoomMessageRecord/);
  assert.match(route, /normalizeStageBroadcastRecord/);
  assert.match(route, /normalizeThreadNode/);
  assert.match(route, /normalizeChatConvo/);
  assert.match(route, /normalizeChatMessage/);
  assert.match(route, /"\/api\/skywire\/post\/thread"/);
  assert.match(route, /getPostThread/);
  assert.match(route, /eventType:\s*"atproto\.thread\.viewed"/);
  assert.match(route, /"\/api\/skywire\/quote"/);
  assert.match(route, /"\/api\/skywire\/chats"/);
  assert.match(route, /"\/api\/skywire\/chats\/resolve"/);
  assert.match(route, /"\/api\/skywire\/chats\/:convoId\/messages"/);
  assert.match(route, /"\/api\/skywire\/rooms"/);
  assert.match(route, /"\/api\/skywire\/rooms\/:roomId\/messages"/);
  assert.match(route, /"\/api\/skywire\/stages"/);
  assert.match(route, /"\/api\/skywire\/stages\/:stageId\/broadcasts"/);
  assert.match(route, /"\/api\/skywire\/pipelines"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/history"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/dispatch"/);
  assert.match(route, /"\/api\/skywire\/pipelines\/dispatch-batch"/);
  assert.match(route, /skywire\.systemEventPipelines/);
  assert.match(route, /challengeSystemEvents/);
  assert.match(route, /ingestSystemEvent/);
  assert.match(route, /skywire\.pipeline\.tv_queued/);
  assert.match(route, /skywire\.pipeline\.studio_queued/);
  assert.match(route, /skywire\.pipeline\.rat_race_queued/);
  assert.match(route, /\$type:\s*"app\.bsky\.embed\.record"/);
  assert.match(route, /eventType:\s*"atproto\.post\.quoted"/);
  assert.match(route, /eventType:\s*"atproto\.chat\.message_sent"/);
  assert.match(route, /eventType:\s*"atproto\.room\.message_sent"/);
  assert.match(route, /eventType:\s*"atproto\.stage\.broadcast_sent"/);
  assert.match(route, /SKYWIRE_ROOM_MESSAGE_COLLECTION/);
  assert.match(route, /SKYWIRE_STAGE_BROADCAST_COLLECTION/);
  assert.match(route, /timeline\.data\.cursor/);
  assert.match(route, /feed\.data\.cursor/);
  assert.match(route, /filter:\s*"posts_with_replies"/);
  assert.match(route, /author\?\.did\.toLowerCase\(\) === actorKey/);
  assert.match(page, /\|\s*"home"/);
  assert.match(page, /\|\s*"actor"/);
  assert.match(page, /<Tab value="home">Home<\/Tab>/);
  assert.match(page, /<Tab value="actor">Actor Feed<\/Tab>/);
  assert.match(page, /<Tab value="pipelines">Pipelines<\/Tab>/);
  assert.match(page, /<Tab value="rooms">Rooms<\/Tab>/);
  assert.match(page, /<Tab value="stages">Stages<\/Tab>/);
  assert.match(page, /<Tab value="chat">Chat<\/Tab>/);
  assert.match(page, /<Tab value="thread">Thread<\/Tab>/);
  assert.match(page, /ThreadPanel/);
  assert.match(page, /Thread Contract/);
  assert.match(page, /PipelinePanel/);
  assert.match(page, /Pipeline Contract/);
  assert.match(page, /Recent Pipeline Events/);
  assert.match(page, /Send to All Pipelines/);
  assert.match(page, /onPipelineOpen/);
  assert.match(page, /Send to \$\{pipeline\.app\}/);
  assert.match(page, /LivePanel/);
  assert.match(page, /ChatPanel/);
  assert.match(page, /onThreadOpen/);
  assert.match(page, /Reply In Chat/);
  assert.match(page, /Send To Members/);
  assert.match(page, /Send Room Message/);
  assert.match(page, /Send Stage Broadcast/);
  assert.match(page, /onChatQuote/);
  assert.match(page, /onRoomQuote/);
  assert.match(page, /onStageQuote/);
  assert.match(page, /pendingChatQuote/);
  assert.match(page, /pendingChatMembers/);
  assert.match(page, /chatMemberForActor/);
  assert.match(page, /pendingRoomQuote/);
  assert.match(page, /pendingStageQuote/);
  assert.match(page, /feedType="home"[\s\S]*canUseSocialActions/);
  assert.match(page, /feedType="wtf"[\s\S]*canUseSocialActions/);
  assert.match(page, /ActorFeedPanel/);
  assert.match(page, /onActorSelect/);
  assert.match(page, /Following on Bluesky/);
  assert.match(page, /Suggested by Skywire/);
  assert.match(page, /onActorOpen\(actorFromRecord\(actor\)\)/);
  assert.match(page, /useInfiniteQuery<FeedResponse>/);
  assert.match(page, /useInfiniteQuery<ActorSearchResponse>/);
  assert.match(page, /Load More/);
  assert.match(page, /Load More Follows/);
  assert.match(page, /FeedCard/);
  assert.match(page, /QuotePreview/);
  assert.match(page, /Post Quote/);
  assert.match(page, /"skywire",\s*"actors",\s*"recommended"/);
  assert.match(page, /"skywire",\s*"actors",\s*"follows"/);
  assert.match(page, /"skywire",\s*"actors",\s*"suggestions"/);
  assert.match(page, /No other Skywire users have connected Bluesky yet/);
  assert.match(page, /actor\.did === me\.account\.did/);
  assert.match(route, /"\/api\/skywire\/actors\/search"/);
  assert.match(route, /"\/api\/skywire\/actor\/:actor\/feed"/);
  assert.match(route, /"\/api\/skywire\/follow"/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"socialActions",\s*"be-social"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"compose",\s*"be-heard"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"signals",\s*"be-heard"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"rooms",\s*"be-heard"\)/);
  assert.match(route, /requireAtprotoCapability\(account,\s*"stages",\s*"be-heard"\)/);
  assert.match(route, /requireSkywireChatCapability\(account\)/);
  assert.match(route, /withProxy\("bsky_chat",\s*"did:web:api\.bsky\.chat"\)/);
  assert.match(route, /atproto_scope_upgrade_required/);
  assert.match(route, /"\/api\/skywire\/profile"/);
  assert.match(permissions, /SKYWIRE_SIGNAL_COLLECTION = "app\.wtfgameshow\.skywire\.signal"/);
  assert.match(permissions, /SKYWIRE_ROOM_MESSAGE_COLLECTION = "app\.wtfgameshow\.skywire\.room\.message"/);
  assert.match(permissions, /SKYWIRE_STAGE_BROADCAST_COLLECTION = "app\.wtfgameshow\.skywire\.stage\.broadcast"/);
  assert.match(permissions, /`repo:\$\{SKYWIRE_ROOM_MESSAGE_COLLECTION\}`/);
  assert.match(permissions, /`repo:\$\{SKYWIRE_STAGE_BROADCAST_COLLECTION\}`/);
  assert.match(route, /com\.atproto\.repo\.createRecord/);
  assert.match(route, /validate:\s*false/);
  assert.match(events, /"atproto\.profile\.updated"/);
  assert.match(events, /"atproto\.actor\.searched"/);
  assert.match(events, /"atproto\.actor\.followed"/);
  assert.match(events, /"atproto\.signal\.published"/);
  assert.match(events, /"atproto\.chat\.message_sent"/);
  assert.match(events, /"atproto\.stage\.broadcast_sent"/);
  assert.match(events, /"atproto\.thread\.viewed"/);
});

test("Profile social surfaces expose Skywire identity links", () => {
  const atprotoRoute = readFileSync("server/routes/atproto.ts", "utf8");
  const route = readFileSync("server/routes/profile.ts", "utf8");
  const page = readFileSync("client/src/pages/Profile.tsx", "utf8");
  const publicPage = readFileSync("client/src/pages/PublicProfile.tsx", "utf8");
  assert.match(route, /atprotoAccounts/);
  assert.match(route, /atprotoHandle/);
  assert.match(atprotoRoute, /"\/api\/atproto\/unlink"/);
  assert.match(atprotoRoute, /eventType:\s*"atproto\.account\.unlinked"/);
  assert.match(page, /<strong style=\{\{ width: 70 \}\}>Skywire:<\/strong>/);
  assert.match(page, /Connect Skywire/);
  assert.match(page, /Open Skywire/);
  assert.match(page, /disconnectSkywireMutation/);
  assert.match(page, /api\.post<\{ ok: true \}>\("\/api\/atproto\/unlink"/);
  assert.match(page, /Disconnect this Skywire AT Protocol identity/);
  assert.match(page, /Failed to disconnect Skywire/);
  assert.match(publicPage, /profile\.atprotoHandle/);
  assert.match(publicPage, /https:\/\/bsky\.app\/profile\/\$\{profile\.atprotoHandle\}/);
});

test("Skywire adapter persists atproto events and calls challenge ingestion", () => {
  const adapter = readFileSync("server/features/atproto/events.ts", "utf8");
  assert.match(adapter, /insert\(atprotoEvents\)/);
  assert.match(adapter, /onConflictDoNothing/);
  assert.match(adapter, /ingestSystemEvent\(/);
});

test("Skywire page is registered as a desktop social app", () => {
  const routes = readFileSync("client/src/routes/page-defs.ts", "utf8");
  assert.match(routes, /pattern:\s*"\/skywire"/);
  assert.match(routes, /title:\s*"Skywire"/);
  assert.match(routes, /group:\s*"social"/);
  assert.match(routes, /desktopIcon:\s*true/);
});
