/**
 * Layer Settings Export/Import Utilities
 * 
 * Provides functionality to export layer settings as JSON files
 * and import layer settings from JSON files.
 */

import type { LayerConfig } from "../state/types";

// Version for tracking schema changes
const LAYER_SETTINGS_VERSION = "1.0.0";

export type LayerSettingsFile = {
  version: string;
  exportedAt: string;
  layerName: string;
  settings: Omit<LayerConfig, "id">;
};

/**
 * Export a layer's settings to a JSON file
 */
export function exportLayerSettings(layer: LayerConfig): void {
  // Create a copy without the id (will be regenerated on import)
  const { id, ...settings } = layer;
  
  const exportData: LayerSettingsFile = {
    version: LAYER_SETTINGS_VERSION,
    exportedAt: new Date().toISOString(),
    layerName: layer.name,
    settings: settings as Omit<LayerConfig, "id">,
  };
  
  const json = JSON.stringify(exportData, null, 2);
  const blob = new Blob([json], { type: "application/json" });
  const url = URL.createObjectURL(blob);
  
  const a = document.createElement("a");
  a.href = url;
  a.download = `${sanitizeFilename(layer.name)}-layer-settings.json`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

/**
 * Import layer settings from a JSON file
 * Returns the parsed settings or throws an error if invalid
 */
export async function importLayerSettings(file: File): Promise<Omit<LayerConfig, "id">> {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const data = JSON.parse(content) as LayerSettingsFile;
        
        // Validate the file format
        if (!data.version || !data.settings) {
          throw new Error("Invalid layer settings file format");
        }
        
        // Validate required settings fields using the validation function
        const settings = data.settings;
        if (!validateLayerSettings(settings)) {
          throw new Error("Layer settings file is missing required fields or has invalid values");
        }
        
        // Return the settings (id will be generated by the store)
        resolve(settings);
      } catch (err) {
        reject(new Error(`Failed to parse layer settings: ${err instanceof Error ? err.message : String(err)}`));
      }
    };
    
    reader.onerror = () => {
      reject(new Error("Failed to read file"));
    };
    
    reader.readAsText(file);
  });
}

/**
 * Sanitize a filename to remove invalid characters
 */
function sanitizeFilename(name: string): string {
  return name
    .replace(/[^a-zA-Z0-9-_]/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .toLowerCase() || "layer";
}

/**
 * Validate that a settings object has all required fields
 */
export function validateLayerSettings(settings: unknown): settings is Omit<LayerConfig, "id"> {
  if (!settings || typeof settings !== "object") return false;
  
  const s = settings as Record<string, unknown>;
  
  // Check required string fields
  const requiredStrings = ["name", "kind", "type", "shape", "colorMode", "color", "boundaryMode"];
  for (const field of requiredStrings) {
    if (typeof s[field] !== "string") return false;
  }
  
  // Check required number fields
  const requiredNumbers = [
    "particleCount", "spawnRate", "spawnSpeed", "gravity", "drag", "jitter", 
    "curl", "attract", "windAngle", "windStrength", "speed", "boundaryBounce",
    "pointSize", "brightness", "dither"
  ];
  for (const field of requiredNumbers) {
    if (typeof s[field] !== "number") return false;
  }
  
  // Check required boolean field
  if (typeof s.enabled !== "boolean") return false;
  
  return true;
}
