import type { BrowserRouteMeta } from "./wtf-browser-route-access";
import { COBWEBSAINTS_FULL_USER_ROLE } from "./types";

/**
 * Browser route metadata shared by the web router and CLI access checks.
 * Keep in sync with `client/src/routes/page-defs.ts` patterns/auth/roles.
 */
export const BROWSER_ROUTE_META: readonly BrowserRouteMeta[] = [
  { pattern: "/gamma", auth: false, title: "WTFOS Gamma" },
  { pattern: "/beta", auth: false, title: "WTFOS Beta" },
  { pattern: "/mission-control", auth: true, title: "Mission Control" },
  { pattern: "/command-palette", auth: true, title: "Command Palette" },
  { pattern: "/recovery-mode", auth: true, title: "Recovery Mode" },
  { pattern: "/file-manager", auth: true, title: "File Manager" },
  { pattern: "/settings", auth: true, title: "Settings" },
  { pattern: "/browser-boundaries", auth: true, title: "Browser Boundaries" },
  { pattern: "/applications/:appId/play", auth: true, title: "Remote Application" },
  { pattern: "/applications", auth: true, title: "Applications" },
  { pattern: "/agent", auth: true, title: "Agent" },
  { pattern: "/terminal", auth: true, title: "Terminal" },
  { pattern: "/cli", auth: true, title: "CLI" },
  { pattern: "/backup-manager", auth: true, roles: ["admin"], title: "Backup Manager" },
  { pattern: "/dashboard", auth: true, title: "Dashboard" },
  { pattern: "/rounds/:id", auth: true, title: "Round Detail" },
  { pattern: "/rounds", auth: true, title: "Rounds" },
  { pattern: "/challenges", auth: true, title: "Challenges" },
  { pattern: "/side-quests", auth: true, title: "Side Quests" },
  { pattern: "/messages", auth: true, title: "Messages" },
  { pattern: "/messages/dms/:id", auth: true, title: "Messages" },
  { pattern: "/notification-center", auth: true, title: "Notification Center" },
  { pattern: "/notifications", auth: true, title: "Notifications" },
  { pattern: "/dear-diary", auth: true, title: "Dear Diary" },
  { pattern: "/wtfiam", auth: true, title: "WTF I AM" },
  { pattern: "/marketplace", auth: true, title: "On Chain Market" },
  { pattern: "/rat-race", auth: true, title: "Rat Race" },
  { pattern: "/map-lab", auth: false, title: "WTF Map Lab" },
  { pattern: "/trade-boards", auth: true, title: "Trade Boards" },
  { pattern: "/w", auth: true, title: "W Feed" },
  { pattern: "/w/post/:id", auth: true, title: "W Post" },
  { pattern: "/w/chat", auth: true, title: "W Chat" },
  { pattern: "/w/groupchat/:id", auth: true, title: "W Chat" },
  { pattern: "/chat", auth: true, title: "W Chat" },
  { pattern: "/chat/:id", auth: true, title: "W Chat" },
  { pattern: "/tv", auth: true, title: "WTF TV" },
  { pattern: "/dicksword", auth: true, title: "Dicksword" },
  { pattern: "/i-hate-telegram", auth: true, title: "I Hate Telegram" },
  { pattern: "/arcade", auth: false, title: "WTF Arcade" },
  { pattern: "/casino", auth: true, title: "WTF Casino" },
  { pattern: "/casino/wtf-button", auth: true, title: "WTF Button" },
  { pattern: "/casino/rug-pull", auth: true, title: "Rug Pull" },
  { pattern: "/casino/guinea-pig-raceway", auth: true, title: "Guinea Pig Raceway" },
  { pattern: "/dues", auth: false, title: "Club Dues Manager" },
  { pattern: "/console", auth: true, title: "WTF Console" },
  { pattern: "/game-studio", auth: true, title: "Game Studio" },
  { pattern: "/dedrooms", auth: true, title: "DedRooms" },
  { pattern: "/tools/ch-ease", auth: true, roles: ["admin", "host", "cohost", "trusted_creator", COBWEBSAINTS_FULL_USER_ROLE], title: "CH-EASE" },
  { pattern: "/tools/macaroni-packager", auth: true, roles: ["admin", "host", "cohost", "trusted_creator", COBWEBSAINTS_FULL_USER_ROLE], title: "CH-EASE" },
  { pattern: "/tools/colander", auth: true, title: "Colander" },
  { pattern: "/tools/broot", auth: true, title: "Broot" },
  { pattern: "/tools/particle-painter", auth: true, title: "Particle Painter" },
  { pattern: "/tools/pixalerce", auth: true, title: "PixAlerce" },
  { pattern: "/tools/industrializer", auth: true, title: "Industrializer" },
  { pattern: "/tools/pauls-particles-v1", auth: true, title: "Paul's Particles" },
  { pattern: "/tools/nikshumika-paint", auth: true, title: "Nikshumika Paint" },
  { pattern: "/tools/kandinsky-composer", auth: true, title: "Kandinsky Composer" },
  { pattern: "/tools/pixel-patterns", auth: true, title: "PixelPatterns" },
  { pattern: "/tools/penrose-backgrounds", auth: true, title: "PenRose Backgrounds" },
  { pattern: "/tools/macaroni", auth: true, roles: ["admin", "host", "cohost", "trusted_creator", COBWEBSAINTS_FULL_USER_ROLE], title: "Macaroni" },
  { pattern: "/tools/spaghetti", auth: true, title: "Spaghetti" },
  { pattern: "/tools/gnocchi", auth: true, title: "Gnocchi" },
  { pattern: "/tools/ravioli", auth: true, title: "Ravioli" },
  { pattern: "/tools/rotini", auth: true, title: "Rotini" },
  { pattern: "/tools/penne", auth: true, title: "Penne" },
  { pattern: "/tools/lasagna", auth: true, title: "Lasagna" },
  { pattern: "/swap", auth: true, title: "Swap" },
  { pattern: "/profile", auth: true, title: "Profile" },
  { pattern: "/theme-builder", auth: true, title: "Theme Builder" },
  { pattern: "/desktop-settings", auth: true, title: "System Appearance" },
  { pattern: "/admin", auth: true, roles: ["admin"], title: "Admin Panel" },
  { pattern: "/my-videos", auth: true, title: "My Videos" },
  { pattern: "/my-photos", auth: true, title: "My Photos" },
  { pattern: "/my-music", auth: true, title: "My Music" },
  { pattern: "/tezamp", auth: true, title: "Tezamp" },
  { pattern: "/ipfs-pinning", auth: true, title: "IPFS Pinning Manager" },
  { pattern: "/apps/porcupin-setup", auth: true, title: "Porcupin Setup" },
  { pattern: "/apps/porcupin-dashboard", auth: true, title: "Porcupin Dashboard" },
  { pattern: "/studio/:id", auth: true, title: "Studio" },
  { pattern: "/studio", auth: true, title: "Studio" },
  { pattern: "/leaderboard", auth: false, title: "Leaderboard" },
  { pattern: "/gallery", auth: false, title: "Gallery" },
  { pattern: "/gallery/token/:contract/:tokenId", auth: false, title: "Gallery Token" },
  { pattern: "/token/:contract/:tokenId", auth: false, title: "Gallery Token" },
  { pattern: "/my-gallery", auth: true, title: "My Gallery" },
  { pattern: "/collekt", auth: true, title: "colleKT" },
  { pattern: "/tezos-intel", auth: true, title: "Tezos Intel" },
  { pattern: "/wtf-subdomains/setup", auth: true, title: "Subdomain Setup" },
  { pattern: "/wtf-subdomains", auth: true, title: "WTF Domains" },
  { pattern: "/links", auth: false, title: "Links" },
  { pattern: "/faq", auth: false, title: "FAQ" },
  { pattern: "/discord/terms", auth: false, title: "Discord Terms" },
  { pattern: "/discord/privacy", auth: false, title: "Discord Privacy" },
  { pattern: "/discord/linked-roles", auth: false, title: "Discord Linked Roles" },
  { pattern: "/user/:username", auth: false, title: "User Profile" },
  { pattern: "/messageboard", auth: false, title: "Message Board" },
  { pattern: "/wtf-recapture", auth: false, title: "WTF Recapture" },
  { pattern: "/calendar", auth: false, title: "Calendar" },
  { pattern: "/mint-portal", auth: true, title: "Mint Portal" },
  { pattern: "/contract-factory", auth: true, roles: ["admin"], title: "Contract Factory" },
  { pattern: "/operator-wallet", auth: true, roles: ["admin"], title: "Operator Wallet" },
  { pattern: "/payroll", auth: true, roles: ["admin"], title: "Payroll" },
  { pattern: "/objkt-operator", auth: true, roles: ["admin"], title: "Objkt Operator" },
  { pattern: "/control-board", auth: true, roles: ["admin"], title: "Control Board" },
  { pattern: "/skywire", auth: false, title: "Skywire" },
  { pattern: "/live/r/:roomId", auth: false, title: "WTF LIVE Room" },
  { pattern: "/live", auth: true, title: "WTF LIVE" },
  { pattern: "/tz2at", auth: true, title: "tz2at" },
  { pattern: "/crp-nominate", auth: true, title: "CRP Nominations" },
  { pattern: "/wim", auth: true, title: "WIM" },
  { pattern: "/mail", auth: true, title: "Inbox" },
  { pattern: "/admin-inbox", auth: true, title: "Contact Admin" },
  { pattern: "/digest", auth: true, title: "Digest" },
  { pattern: "/browser", auth: true, title: "Browser" },
  { pattern: "/music", auth: true, title: "TezosBeats" },
  { pattern: "/task-manager", auth: true, title: "Task Manager" },
  {
    pattern: "/dev/ux-lab",
    auth: true,
    roles: ["admin"],
    surfaceGrantMaySatisfyRoles: true,
    title: "UX Lab",
  },
] as const;
