import assert from "node:assert/strict";
import { existsSync, readFileSync } from "node:fs";
import test from "node:test";

const desktopPackage = JSON.parse(readFileSync("apps/ravioli-desktop/package.json", "utf8"));
const mainSource = readFileSync("apps/ravioli-desktop/src/main.cjs", "utf8");
const preloadSource = readFileSync("apps/ravioli-desktop/src/preload.cjs", "utf8");
const prepareSource = readFileSync("apps/ravioli-desktop/scripts/prepare-assets.mjs", "utf8");
const workflowSource = readFileSync(".github/workflows/ravioli-desktop-installers.yml", "utf8");
const routeSource = readFileSync("server/routes/ravioli-installers.ts", "utf8");
const routesSource = readFileSync("server/routes.ts", "utf8");
const studioSource = readFileSync("public/creation-tools/ravioli/js/studio.js", "utf8");
const siteSource = readFileSync("public/creation-tools/ravioli/js/site.js", "utf8");
const routerArtifactSource = readFileSync("public/creation-tools/ravioli/contract/pasta-bundle.contract.json", "utf8");
const commonSource = readFileSync("public/creation-tools/ravioli/js/common.js", "utf8");
const rootPackage = JSON.parse(readFileSync("package.json", "utf8"));
const gitignoreSource = readFileSync(".gitignore", "utf8");
const liveCheckSource = readFileSync("scripts/check-ravioli-installers-live.mjs", "utf8");
const envExampleSource = readFileSync(".env.example", "utf8");
const inventorySource = readFileSync("tests/e2e/inventory/domain-workflows.mjs", "utf8");

test("Ravioli desktop package bundles the atomic pack publisher in an Electron shell", () => {
  assert.equal(desktopPackage.name, "@wtf/ravioli-desktop");
  assert.equal(desktopPackage.version, "1.0.0");
  assert.equal(desktopPackage.main, "src/main.cjs");
  assert.equal(desktopPackage.devDependencies.electron, "42.4.0");
  assert.equal(desktopPackage.devDependencies["electron-builder"], "26.15.3");
  assert.equal(desktopPackage.homepage, "https://wtfos.app/creation-tools/ravioli/index.html");
  assert.equal(desktopPackage.desktopName, "ravioli-studio");
  assert.equal(desktopPackage.author.name, "wtfOS");
  assert.equal(desktopPackage.author.email, "support@wtfos.app");
  assert.match(desktopPackage.scripts.prepare, /prepare-assets\.mjs/);
  assert.match(desktopPackage.scripts["dist:mac"], /--mac dmg zip --universal/);
  assert.match(desktopPackage.scripts["dist:windows"], /--win nsis --x64/);
  assert.match(desktopPackage.scripts["dist:raspberry-pi"], /--linux deb --arm64/);
  assert.deepEqual(desktopPackage.build.files, ["package.json", "src/**/*", "ravioli/**/*"]);
  assert.equal(desktopPackage.build.artifactName, "Ravioli-Studio-${version}-${os}-${arch}.${ext}");
  assert.equal(desktopPackage.build.executableName, "ravioli-studio");
  assert.equal(desktopPackage.build.linux.maintainer, "wtfOS <support@wtfos.app>");
  assert.equal(desktopPackage.build.linux.syncDesktopName, true);
  assert.equal(desktopPackage.build.deb.packageName, "ravioli-studio");
  assert.equal(desktopPackage.build.deb.packageCategory, "devel");
  assert.equal(desktopPackage.build.deb.maintainer, "wtfOS <support@wtfos.app>");
  assert.match(gitignoreSource, /apps\/ravioli-desktop\/ravioli\//);
  assert.match(gitignoreSource, /apps\/ravioli-desktop\/release\//);
});

test("Ravioli desktop asset preparation preserves the router and typed helper contracts", () => {
  assert.match(prepareSource, /public\/creation-tools\/ravioli/);
  assert.match(prepareSource, /contract\/pasta-bundle\.contract\.json/);
  assert.match(prepareSource, /contract\/pasta-gnocchi-pack-adapter\.contract\.json/);
  assert.match(prepareSource, /contract\/pasta-rotini-pack-adapter\.contract\.json/);
  assert.match(prepareSource, /js\/pasta-foundation\.js/);
  assert.match(prepareSource, /vendor\/tezos\.js/);
  assert.match(prepareSource, /vendor\/octez-connect\.js/);
  assert.ok(existsSync("public/creation-tools/ravioli/index.html"), "Ravioli source page should exist");
  assert.ok(existsSync("public/creation-tools/ravioli/contract/pasta-bundle.contract.json"), "Ravioli contract artifact should exist");
  assert.ok(existsSync("public/creation-tools/ravioli/contract/pasta-gnocchi-pack-adapter.contract.json"), "Gnocchi pack adapter artifact should exist");
  assert.ok(existsSync("public/creation-tools/ravioli/contract/pasta-rotini-pack-adapter.contract.json"), "Rotini pack adapter artifact should exist");
  assert.match(studioSource, /atomic pack publisher/i);
  assert.match(studioSource, /methodsObject\.commit_recipe/);
  assert.match(studioSource, /methodsObject\.finalize_pack/);
  assert.match(studioSource, /methodsObject\.open_pack/);
  assert.match(studioSource, /ravioli\.bundle_published/);
  assert.match(commonSource, /window\.MD/);
});

test("Ravioli v3 makes adapter payload commitment policy explicit end to end", () => {
  assert.match(routerArtifactSource, /%payload_commitment/);
  assert.match(studioSource, /pasta-ravioli-open-kit@3/);
  assert.match(studioSource, /payload_commitment: action\.kind === "allocated" \? payloadCommitment\(""\) : null/);
  assert.match(studioSource, /payload_commitment: action\.payloadCommitment \|\| payloadCommitment\(""\)/);
  assert.match(studioSource, /payload_commitment: action\.payloadCommitment \|\| null/);
  assert.match(siteSource, /pasta-ravioli-open-kit@3/);
  assert.match(siteSource, /payload_commitment: action\.payloadCommitment/);
});

test("Ravioli desktop runtime serves local assets and blocks hosted wtfOS APIs", () => {
  assert.match(mainSource, /http\.createServer/);
  assert.match(mainSource, /baseUrl = `http:\/\/127\.0\.0\.1:\$\{address\.port\}`/);
  assert.match(mainSource, /mainWindow\.loadURL\(`\$\{baseUrl\}\/`\)/);
  assert.match(mainSource, /path\.join\(appRoot\(\), "ravioli"\)/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/auth\/user"/);
  assert.match(mainSource, /Ravioli Desktop does not include wtfOS hosted resources/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/auth\/csrf-token"/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/ravioli\/installers"/);
  assert.match(mainSource, /product: "ravioli"/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/system\/logs\/client"/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/macaroni\/ipfs\/pin"/);
  assert.match(mainSource, /parsed\.pathname === "\/api\/macaroni\/publish"/);
  assert.match(mainSource, /Use Pinata or your own IPFS node/);
  assert.match(mainSource, /nodeIntegration: false/);
  assert.match(mainSource, /contextIsolation: true/);
  assert.match(mainSource, /sandbox: true/);
  assert.match(mainSource, /setWindowOpenHandler/);
  assert.match(preloadSource, /RAVIOLI_DESKTOP/);
  assert.match(preloadSource, /PASTA_TOOL_DESKTOP/);
  assert.match(preloadSource, /native: true/);
});

test("Ravioli desktop installer workflow builds all target packages", () => {
  assert.match(workflowSource, /name: Ravioli Desktop Installers/);
  assert.match(workflowSource, /workflow_dispatch/);
  assert.match(workflowSource, /ravioli-desktop-v\*/);
  assert.match(workflowSource, /node-version: 22/);
  assert.match(workflowSource, /macos-latest/);
  assert.match(workflowSource, /windows-latest/);
  assert.match(workflowSource, /ubuntu-latest/);
  assert.match(workflowSource, /npm ci --prefix apps\/ravioli-desktop/);
  assert.match(workflowSource, /npm run ravioli:desktop:check/);
  assert.match(workflowSource, /npm run dist:mac --prefix apps\/ravioli-desktop/);
  assert.match(workflowSource, /npm run dist:windows --prefix apps\/ravioli-desktop/);
  assert.match(workflowSource, /npm run dist:raspberry-pi --prefix apps\/ravioli-desktop/);
  assert.match(workflowSource, /actions\/upload-artifact@v4/);
  assert.match(workflowSource, /softprops\/action-gh-release@v2/);
});

test("Ravioli production installer manifest keeps release download hardening rules", () => {
  assert.match(routesSource, /import ravioliInstallerRoutes from "\.\/routes\/ravioli-installers"/);
  assert.match(routesSource, /app\.use\(ravioliInstallerRoutes\)/);
  assert.match(routeSource, /router\.get\("\/api\/ravioli\/installers", isAuthenticated/);
  assert.match(routeSource, /product: "ravioli"/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_VERSION/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_MACOS_URL/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_MACOS_SHA256/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_WINDOWS_URL/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_WINDOWS_SHA256/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_RASPBERRY_PI_URL/);
  assert.match(routeSource, /RAVIOLI_INSTALLER_RASPBERRY_PI_SHA256/);
  assert.match(routeSource, /fileName: "Ravioli-Studio\.exe"/);
  assert.doesNotMatch(routeSource, /fileName: "Ravioli-Studio\.msi"/);
  assert.match(routeSource, /function isLoopbackInstallerHost\(hostname: string\): boolean/);
  assert.match(routeSource, /url\.protocol === "https:"/);
  assert.match(routeSource, /process\.env\.NODE_ENV !== "production" && url\.protocol === "http:" && isLoopbackInstallerHost\(url\.hostname\)/);
  assert.doesNotMatch(routeSource, /url\.protocol === "https:" \|\| url\.protocol === "http:"/);
  assert.match(routeSource, /safeInstallerSha256/);
  assert.match(routeSource, /available: Boolean\(url && sha256\)/);
  assert.match(routeSource, /url: url && sha256 \? url : null/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_VERSION=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_MACOS_URL=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_MACOS_SHA256=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_WINDOWS_URL=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_WINDOWS_SHA256=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_RASPBERRY_PI_URL=/);
  assert.match(envExampleSource, /RAVIOLI_INSTALLER_RASPBERRY_PI_SHA256=/);
  assert.match(liveCheckSource, /ravioli-desktop-v\$\{EXPECTED_VERSION\}/);
  assert.match(liveCheckSource, /\/api\/ravioli\/installers/);
  assert.match(liveCheckSource, /Ravioli-Studio-\$\{EXPECTED_VERSION\}-mac-universal\.dmg/);
  assert.match(liveCheckSource, /Ravioli-Studio-\$\{EXPECTED_VERSION\}-win-x64\.exe/);
  assert.match(liveCheckSource, /Ravioli-Studio-\$\{EXPECTED_VERSION\}-linux-arm64\.deb/);
  assert.match(liveCheckSource, /asset\.digest/);
  assert.match(inventorySource, /ravioli\.installer_manifest\.viewed/);
  assert.match(inventorySource, /\/api\/ravioli\/installers/);
});

test("Ravioli desktop root scripts expose package preparation, policy, and dist", () => {
  assert.equal(rootPackage.scripts["ravioli:desktop:prepare"], "npm run prepare --prefix apps/ravioli-desktop");
  assert.equal(rootPackage.scripts["ravioli:desktop:check"], "node --test scripts/ravioli-desktop-package-policy.test.mjs");
  assert.equal(rootPackage.scripts["ravioli:installers:live-check"], "node scripts/check-ravioli-installers-live.mjs");
  assert.equal(rootPackage.scripts["ravioli:desktop:dist"], "npm run dist --prefix apps/ravioli-desktop");
});
