import type { DesktopAppKey } from "@shared/types";

export type AdminSurfaceKind =
  | "app"
  | "tool"
  | "desktop-item"
  | "admin-tool"
  | "public-surface";

export type AdminSurface = {
  id: string;
  label: string;
  domain: string;
  subdomain: string;
  kind: AdminSurfaceKind;
  routePatterns: string[];
  desktopAppKey?: DesktopAppKey;
  adminPanelTabs: string[];
  nativeSettings: string[];
  automationHandles: string[];
  adminRoutes?: string[];
  behaviorAssertionIds?: string[];
};

export type DoctrineDomainGuide = {
  label: string;
  guide: string;
};

export const DOCTRINE_DOMAIN_GUIDES = {
  wtfOs: { label: "WTF OS", guide: "docs/domains/wtf-os.md" },
  identityAndSocial: { label: "Identity And Social", guide: "docs/domains/identity-and-social.md" },
  arcadeConsoleGameStudio: {
    label: "Arcade, Console, And Game Studio",
    guide: "docs/domains/arcade-console-game-studio.md",
  },
  commerceAndWallets: { label: "Commerce And Wallets", guide: "docs/domains/commerce-and-wallets.md" },
  mediaTvStudio: { label: "Media, TV, And Studio", guide: "docs/domains/media-tv-studio.md" },
  pastaProtocol: { label: "Pasta Protocol", guide: "docs/domains/pasta-protocol.md" },
  tezosPlatform: { label: "Tezos Platform", guide: "docs/domains/tezos-platform.md" },
  operations: { label: "Operations", guide: "docs/domains/operations.md" },
} as const satisfies Record<string, DoctrineDomainGuide>;

const doctrineDomainBySurfaceDomain: Record<string, DoctrineDomainGuide> = {
  Admin: DOCTRINE_DOMAIN_GUIDES.operations,
  Arcade: DOCTRINE_DOMAIN_GUIDES.arcadeConsoleGameStudio,
  Casino: DOCTRINE_DOMAIN_GUIDES.commerceAndWallets,
  "Club Dues": DOCTRINE_DOMAIN_GUIDES.commerceAndWallets,
  Commerce: DOCTRINE_DOMAIN_GUIDES.commerceAndWallets,
  Console: DOCTRINE_DOMAIN_GUIDES.arcadeConsoleGameStudio,
  Creation: DOCTRINE_DOMAIN_GUIDES.mediaTvStudio,
  "Desktop OS": DOCTRINE_DOMAIN_GUIDES.wtfOs,
  Gameshow: DOCTRINE_DOMAIN_GUIDES.wtfOs,
  Media: DOCTRINE_DOMAIN_GUIDES.mediaTvStudio,
  "Pasta Protocol": DOCTRINE_DOMAIN_GUIDES.pastaProtocol,
  Public: DOCTRINE_DOMAIN_GUIDES.wtfOs,
  Social: DOCTRINE_DOMAIN_GUIDES.identityAndSocial,
  Wallet: DOCTRINE_DOMAIN_GUIDES.tezosPlatform,
};

const doctrineDomainBySurfaceId: Record<string, DoctrineDomainGuide> = {
  "ch-ease": DOCTRINE_DOMAIN_GUIDES.mediaTvStudio,
  "game-studio": DOCTRINE_DOMAIN_GUIDES.arcadeConsoleGameStudio,
  "ipfs-pinning": DOCTRINE_DOMAIN_GUIDES.mediaTvStudio,
  marketplace: DOCTRINE_DOMAIN_GUIDES.commerceAndWallets,
  "pasta-protocol": DOCTRINE_DOMAIN_GUIDES.pastaProtocol,
};

const gameshowAdminTabs = [
  "Seasons",
  "Rounds",
  "Challenges",
  "Side Quests",
  "Automation",
];

export const ADMIN_SURFACES: AdminSurface[] = [
  {
    id: "dashboard",
    label: "Dashboard",
    domain: "Gameshow",
    subdomain: "Player cockpit",
    kind: "app",
    routePatterns: ["/dashboard"],
    adminPanelTabs: ["Users", "XP Log", "Rewards", "Automation"],
    nativeSettings: ["XP visibility", "profile widgets", "reward ledger hooks", "cockpit event triggers"],
    automationHandles: ["dashboard.viewed", "xp.awarded", "app.interaction.tracked"],
  },
  {
    id: "rounds",
    label: "Rounds",
    domain: "Gameshow",
    subdomain: "Rounds",
    kind: "app",
    routePatterns: ["/rounds", "/rounds/:id"],
    adminPanelTabs: gameshowAdminTabs,
    nativeSettings: ["round status", "calendar windows", "contestant lists", "automation triggers"],
    automationHandles: ["gameshow.round.joined", "app.interaction.tracked"],
  },
  {
    id: "challenges",
    label: "Challenges",
    domain: "Gameshow",
    subdomain: "Challenge rules",
    kind: "app",
    routePatterns: ["/challenges"],
    adminPanelTabs: ["Challenges", "Automation", "Rewards", "XP Log"],
    nativeSettings: ["legacy challenge records", "automation definitions", "reward actions", "completion audit"],
    automationHandles: ["gameshow.challenge.completed", "xp.awarded", "wtf.awarded"],
    behaviorAssertionIds: [
      "gameshow.automation-completion-reward-proof",
      "gameshow.challenge-submit-grade-claim-leaderboard",
      "gameshow.launch-surfaces-active-challenge-ui",
    ],
  },
  {
    id: "side-quests",
    label: "Side Quests",
    domain: "Gameshow",
    subdomain: "Side quests",
    kind: "app",
    routePatterns: ["/side-quests"],
    adminPanelTabs: ["Side Quests", "Automation", "Rewards", "XP Log"],
    nativeSettings: ["quest definitions", "auto-verify handles", "reward actions", "completion review"],
    automationHandles: ["side_quest.auto_verify.checked", "gameshow.challenge.completed", "xp.awarded"],
    behaviorAssertionIds: [
      "gameshow.automation-completion-reward-proof",
      "gameshow.launch-surfaces-active-challenge-ui",
      "gameshow.side-quests-messageboard-check-in",
    ],
  },
  {
    id: "dedrooms",
    label: "DedRooms",
    domain: "Gameshow",
    subdomain: "DedRooms MUD and intro campaign",
    kind: "app",
    routePatterns: ["/dedrooms"],
    desktopAppKey: "dedrooms",
    adminPanelTabs: ["Seasons", "Automation", "Users", "System Logs"],
    nativeSettings: [
      "campaign target count",
      "active/myth campaign mode",
      "room and exit content validation",
      "NPC dialogue branches",
      "resource drop schedules",
      "world and player flag audit",
    ],
    automationHandles: [
      "ded_rooms.command.look",
      "ded_rooms.command.talk",
      "ded_rooms.resource.gathered",
      "ded_rooms.shared_milestone",
      "ded_rooms.player.departed",
      "app.interaction.tracked",
    ],
    adminRoutes: [
      "/api/dedrooms/admin/content",
      "/api/dedrooms/admin/campaign",
    ],
    behaviorAssertionIds: ["dedrooms.mud-core-flow"],
  },
  {
    id: "mint-portal",
    label: "Mint Portal",
    domain: "Gameshow",
    subdomain: "Minting",
    kind: "app",
    routePatterns: ["/mint-portal"],
    adminPanelTabs: ["Challenges", "Automation", "Contract Ledger"],
    nativeSettings: ["mint-bound challenge routing", "token ownership predicates", "reward queue triggers"],
    automationHandles: ["mint_submission.created", "token.id.owned", "nft.ownership.verified"],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "calendar",
    label: "Calendar",
    domain: "Gameshow",
    subdomain: "Events",
    kind: "public-surface",
    routePatterns: ["/calendar"],
    adminPanelTabs: ["Automation", "Control Board"],
    nativeSettings: ["event publishing", "attendance triggers", "ticket review"],
    automationHandles: ["calendar.ticket_submitted", "attendance.claimed", "app.interaction.tracked"],
  },
  {
    id: "recapture",
    label: "WTF Recapture",
    domain: "Gameshow",
    subdomain: "Recapture and auctions",
    kind: "public-surface",
    routePatterns: ["/wtf-recapture"],
    adminPanelTabs: ["Contract Ledger", "Rewards", "Automation"],
    nativeSettings: ["buyback windows", "auction state", "manual-op audit"],
    automationHandles: ["buyback.intent_submitted", "wtf_auction.bid_submitted", "wtf.awarded"],
  },
  {
    id: "messageboard",
    label: "Message Board",
    domain: "Social",
    subdomain: "Board",
    kind: "public-surface",
    routePatterns: ["/messageboard"],
    adminPanelTabs: ["Board", "Automation", "XP Log"],
    nativeSettings: ["channels", "permissions", "pins", "slow mode", "post reward triggers"],
    automationHandles: ["messageboard.post.created", "messageboard.channel.post.created", "app.interaction.tracked"],
    behaviorAssertionIds: ["gameshow.side-quests-messageboard-check-in"],
  },
  {
    id: "messages",
    label: "Messages",
    domain: "Social",
    subdomain: "DMs",
    kind: "app",
    routePatterns: ["/messages", "/messages/dms/:id"],
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: ["DM monitoring", "notification templates", "abuse review handles"],
    automationHandles: ["dm.message.sent", "notification.viewed", "app.interaction.tracked"],
    behaviorAssertionIds: ["inbox.compose-reply-send-actions"],
  },
  {
    id: "comms-kernel",
    label: "Comms Kernel",
    domain: "Social",
    subdomain: "Universal communications index",
    kind: "tool",
    routePatterns: [],
    adminRoutes: ["/api/comms/sources", "/api/comms/items", "/api/comms/unread-count", "/api/comms/route-target"],
    adminPanelTabs: ["System Logs", "Automation", "Users"],
    nativeSettings: ["source registry", "identity resolution", "read-state indexing", "route target policy"],
    automationHandles: ["comms.item.indexed", "comms.item.read", "comms.route.opened"],
  },
  {
    id: "mail",
    label: "Inbox",
    domain: "Social",
    subdomain: "Central messaging hub",
    kind: "app",
    routePatterns: ["/mail"],
    desktopAppKey: "mail",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "staff-alpha rollout",
      "mailbox provisioning",
      "Resend domain status",
      "delivery failures",
      "unread badge",
      "read-state sync",
      "message marks",
      "new message composer",
      "inline WIM/Studio replies",
      "saved drafts/templates",
    ],
    automationHandles: [
      "inbox.viewed",
      "inbox.message.read",
      "inbox.message.flagged",
      "inbox.message.starred",
      "inbox.message.bookmarked",
      "inbox.message.reacted",
      "inbox.message.replied",
      "inbox.message.forwarded",
      "inbox.draft.saved",
      "dm.message.sent",
      "mail.message.received",
      "mail.message.sent",
      "mail.delivery.failed",
      "comms.item.indexed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: ["inbox.compose-reply-send-actions"],
  },
  {
    id: "digest",
    label: "Digest",
    domain: "Social",
    subdomain: "Unified timeline",
    kind: "app",
    routePatterns: ["/digest"],
    adminPanelTabs: ["Content", "System Logs", "Automation"],
    nativeSettings: ["source filters", "origin labels", "route targets", "external read-only adapters"],
    automationHandles: ["digest.viewed", "digest.source_filtered", "comms.item.read", "comms.route.opened"],
  },
  {
    id: "skywire",
    label: "Skywire",
    domain: "Social",
    subdomain: "AT Protocol identity bridge",
    kind: "app",
    routePatterns: ["/skywire"],
    desktopAppKey: "skywire",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "SKYWIRE rollout mode (SKYWIRE_ROLLOUT_MODE)",
      "WTF LIVE rooms and stages (SKYWIRE_WTF_LIVE_ENABLED)",
      "desktop app launcher gate",
      "Bluesky OAuth status",
      "Market/Search AppView (ATPROTO_SEARCH_APPVIEW)",
      "AT Protocol account links",
      "official signup handoff",
      "Tezos identity bridge",
    ],
    automationHandles: [
      "atproto.account.connected",
      "atproto.permission_tier.selected",
      "atproto.chat_permission.toggled",
      "atproto.oauth.completed",
      "atproto.account.linked",
      "wallet.tezos_domain_selected",
      "atproto.chat.message_sent",
      "atproto.chat.group_created",
      "atproto.room.message_sent",
      "atproto.stage.broadcast_sent",
      "atproto.live_status.updated",
      "atproto.live_status.cleared",
      "skywire.trending_topics.viewed",
      "skywire.pipeline.live_queued",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "skywire.standalone-at-login",
      "skywire.market-feed-search-source",
      "skywire.trending-topics-hot-lane",
      "skywire.live-status-visible-indicator",
      "skywire.signals-hidden-from-navigation",
      "skywire.oauth-original-window-permission-sync",
      "skywire.oauth-canonical-domain-alias",
    ],
  },
  {
    id: "wtf-live",
    label: "WTF LIVE",
    domain: "Social",
    subdomain: "Public AT room and stage lanes",
    kind: "app",
    routePatterns: ["/live", "/live/r/:roomId"],
    desktopAppKey: "wtf-live",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "WTF LIVE rollout (SKYWIRE_WTF_LIVE_ENABLED)",
      "desktop app launcher gate",
      "room and stage registry",
      "Show Kit soundboard presets",
      "Skywire-linked AT publish permissions",
    ],
    automationHandles: [
      "wtf_live.app.viewed",
      "wtf_live.room.created",
      "wtf_live.room.closed",
      "wtf_live.room.reopened",
      "wtf_live.room.deleted",
      "wtf_live.public_room.opened_external",
      "wtf_live.public_room.joined",
      "wtf_live.public_room.mic_test_completed",
      "wtf_live.public_room.left",
      "wtf_live.public_room.close_window_requested",
      "wtf_live.public_room.chat_emoji_inserted",
      "wtf_live.public_room.room_reaction_sent",
      "wtf_live.room.realtime_joined",
      "wtf_live.room.media_state_changed",
      "wtf_live.room.chat_style_changed",
      "wtf_live.room.chat_message_sent",
      "wtf_live.room.chat_media_sent",
      "wtf_live.soundboard.configured",
      "wtf_live.soundboard.clip_triggered",
      "wtf_live.tip.sent",
      "wim.friend.added",
      "wtf_live.private_room.created",
      "wtf_live.private_room.access_updated",
      "wtf_live.private_room.joined",
      "wtf_live.stage.created",
      "wtf_live.stage.roles_updated",
      "wtf_live.stage.closed",
      "wtf_live.stage.reopened",
      "wtf_live.stage.deleted",
      "wtf_live.stage_room.joined",
      "wtf_live.stage_room.share_blocked",
      "atproto.room.message_sent",
      "atproto.stage.broadcast_sent",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "wtf-live.owner-room-lifecycle-controls",
      "wtf-live.lobby-room-presence",
      "wtf-live.public-room-window-exit-controls",
      "wtf-live.public-room-mic-test",
      "wtf-live.public-room-realtime-media-chat",
      "wtf-live.show-kit-soundboard",
      "wtf-live.smart-room-owner-controls",
      "wtf-live.wim-attendance-identity",
      "wtf-live.tip-items-transfer-redeem",
      "wtf-live.private-room-access-list",
      "wtf-live.mobile-and-panel-popout-controls",
      "wtf-live.stage-owner-lifecycle-controls",
      "wtf-live.stage-room-role-controls",
    ],
  },
  {
    id: "tz2at",
    label: "tz2at",
    domain: "Social",
    subdomain: "AT Protocol Tezos identity proof",
    kind: "app",
    routePatterns: ["/tz2at"],
    desktopAppKey: "tz2at",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "tz2at relay status",
      "tz2at firehose consumer status",
      "tz2at firehose replay search filters",
      "tz2at ecosystem analytics suite",
      "tz2at ecosystem analytics scope presets",
      "tz2at ecosystem operator intelligence",
      "tz2at explanation-led ecosystem readout",
      "tz2at network liquidity charts",
      "tz2at ecosystem liquidity route analytics",
      "tz2at ecosystem entity drilldown",
      "tz2at PDS repo inventory",
      "tz2at seeded CEX custody address book",
      "tz2at unclassified custody candidate surfacing",
      "tz2at CEX address classification",
      "WTFOS PDS spine status",
      "WTFOS AT outbox publisher",
      "tzbsky import status",
      "wallet-link proof records",
      "AT Protocol OAuth scopes",
    ],
    automationHandles: [
      "tz2at.identity.viewed",
      "tz2at.tzbsky.imported",
      "tz2at.wallet_link.published",
      "tz2at.wtfos_pds.requested",
      "tz2at.wtfos_pds.provisioned",
      "blockchain.tezos.token_transfer_in",
      "blockchain.tezos.token_transfer_out",
      "blockchain.tezos.token_mint",
      "blockchain.tezos.contract_call",
      "wtfos.atproto_outbox.enqueued",
      "wtfos.atproto_outbox.published",
      "tz2at.firehose.previewed",
      "tz2at.firehose.searched",
      "tz2at.ecosystem.analytics_viewed",
      "tz2at.ecosystem.analytics_refreshed",
      "tz2at.ecosystem.scope_changed",
      "tz2at.ecosystem.entity_selected",
      "tz2at.ecosystem.entity_scoped",
      "tz2at.firehose.entity_opened",
      "app.interaction.tracked",
    ],
  },
  {
    id: "crp-nominations",
    label: "CRP Nominations",
    domain: "Social",
    subdomain: "Tezos Community Recognition Program nomination AppView",
    kind: "app",
    routePatterns: ["/crp-nominate"],
    desktopAppKey: "crp-nominations",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "CRP nominations repo status",
      "CRP repo DID and handle",
      "WTFOS AT outbox publisher",
      "AppView indexer outbox cursor",
      "anonymous nomination credit counts",
      "Tezos identity resolver sources",
    ],
    automationHandles: [
      "crp.nomination.viewed",
      "crp.nomination.resolve",
      "crp.nomination.submitted",
      "crp.nomination.submitted.anonymous",
      "crp.nomination.share_x",
      "crp.nomination.share_bsky",
      "crp.nomination.user_echo",
      "crp.nomination.bsky_post",
      "crp.nomination.mcp.read",
      "crp.nomination.mcp.nomination_submitted",
      "crp.nomination.mcp.rate_limited",
      "mcp.crp.read",
      "mcp.crp.nomination_submitted",
      "wtfos.atproto_outbox.enqueued",
      "wtfos.atproto_outbox.published",
      "app.interaction.tracked",
    ],
  },
  {
    id: "rat-race",
    label: "Rat Race",
    domain: "Commerce",
    subdomain: "Tezos urgency shopping channel",
    kind: "app",
    routePatterns: ["/rat-race"],
    desktopAppKey: "rat-race",
    adminPanelTabs: ["System Logs", "Automation"],
    nativeSettings: [
      "tz2at sale firehose status",
      "hot edition urgency filter",
      "external marketplace purchase allowlist",
      "parent market handoff links",
    ],
    automationHandles: [
      "rat_race.viewed",
      "rat_race.scan_requested",
      "rat_race.card.opened",
      "rat_race.purchase_intent.created",
      "blockchain.tezos.token_sale",
      "app.interaction.tracked",
    ],
  },
  {
    id: "map-lab",
    label: "WTF Map Lab",
    domain: "Desktop OS",
    subdomain: "System maps and roadmaps",
    kind: "app",
    routePatterns: ["/map-lab"],
    desktopAppKey: "map-lab",
    adminPanelTabs: ["Desktop Apps", "System Logs", "Automation"],
    nativeSettings: [
      "shape key/index policy",
      "locked-node layout resolver",
      "typed node palette and port routing",
      "workflow run/pipeline activity preview",
      "AT repo import permissions",
      "AT firehose read-only import permissions",
      "MCP create-only map policy",
      "WTFOS repo save/restore boundary",
      "read-only wtfOS demo map",
    ],
    automationHandles: [
      "map_lab.viewed",
      "map_lab.demo.opened",
      "map_lab.node.created",
      "map_lab.node.moved",
      "map_lab.wire.created",
      "map_lab.route.created",
      "map_lab.pipeline.ran",
      "map_lab.ingest.previewed",
      "map_lab.repo.saved",
      "map_lab.repo.restored",
      "map_lab.viewport.changed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: ["map-lab.workspace-navigation-and-node-drag"],
  },
  {
    id: "agent",
    label: "Agent",
    domain: "Desktop OS",
    subdomain: "Native AI workspace",
    kind: "app",
    routePatterns: ["/agent"],
    desktopAppKey: "agent",
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs", "Automation"],
    nativeSettings: [
      "provider adapters",
      "provider capability profiles",
      "client-owned credentials",
      "MCP token pairing",
      "MCP access preview",
      "permission grants",
      "project memory",
      "wtfOS filesystem workspace",
      "code outline navigation",
      "native git worktree",
      "companion knowledge pack",
      "extension manifest registry",
    ],
    automationHandles: [
      "agent.viewed",
      "agent.provider.updated",
      "agent.chat.sent",
      "agent.plan.updated",
      "agent.action.proposed",
      "agent.action.applied",
      "agent.action.dismissed",
      "agent.file.edited",
      "agent.file.created",
      "agent.file.renamed",
      "agent.file.deleted",
      "agent.diagnostics.ran",
      "agent.code_navigation.opened",
      "agent.filesystem.saved",
      "agent.filesystem.restored",
      "agent.filesystem.imported",
      "agent.filesystem.exported",
      "agent.git.staged",
      "agent.git.unstaged",
      "agent.git.committed",
      "agent.git.branch.created",
      "agent.git.branch.switched",
      "agent.terminal.command",
      "agent.permission.updated",
      "agent.memory.updated",
      "agent.extension.installed",
      "agent.extension.updated",
      "agent.extension.removed",
      "mcp.token.created",
      "mcp.token.revoked",
      "app.interaction.tracked",
    ],
  },
  {
    id: "wim",
    label: "WIM",
    domain: "Social",
    subdomain: "Instant messenger",
    kind: "app",
    routePatterns: ["/wim"],
    desktopAppKey: "wim",
    adminPanelTabs: ["Users", "System Logs", "Automation"],
    nativeSettings: [
      "DM-backed buddy list",
      "presence surface",
      "notification templates",
      "browser-local custom lists",
      "desktop-level buddy and conversation widgets",
      "system appearance-owned widget controls",
      "shared OS taskbar minimize/restore",
      "classic IM-style rich text composer",
      "GIPHY/Tenor GIF insert handoff",
      "My Media and owned token inserts",
    ],
    automationHandles: [
      "wim.chat.opened",
      "wim.friend.added",
      "wim.message.sent",
      "wim.offline_popup.opened",
      "wim.offline_popup.dismissed",
      "dm.message.sent",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "wtf-live.wim-attendance-identity",
      "wim.modular-window-roster-tabs",
      "inbox.compose-reply-send-actions",
    ],
  },
  {
    id: "browser",
    label: "Browser",
    domain: "Desktop OS",
    subdomain: "Controlled link chamber",
    kind: "app",
    routePatterns: ["/browser"],
    adminPanelTabs: ["OS Admin", "System Logs", "Automation"],
    nativeSettings: ["approved host allowlist", "external-open fallback", "blocked navigation audit"],
    automationHandles: ["browser.link.opened", "browser.navigation.blocked", "comms.route.opened"],
  },
  {
    id: "dear-diary",
    label: "Dear Diary",
    domain: "Social",
    subdomain: "Private diary and notes",
    kind: "app",
    routePatterns: ["/dear-diary"],
    desktopAppKey: "dear-diary",
    adminPanelTabs: ["Desktop Apps", "System Logs", "Automation"],
    nativeSettings: [
      "private entry ownership",
      "tag and classification filters",
      "entry mutation audit",
      "delete ownership boundary",
    ],
    automationHandles: [
      "diary.index.viewed",
      "diary.entry.created",
      "diary.entry.updated",
      "diary.entry.deleted",
      "app.interaction.tracked",
    ],
  },
  {
    id: "w",
    label: "W",
    domain: "Social",
    subdomain: "Feed and chat",
    kind: "app",
    routePatterns: ["/w", "/w/post/:id", "/w/chat", "/w/groupchat/:id", "/chat", "/chat/:id"],
    desktopAppKey: "w",
    adminPanelTabs: ["Content", "System Logs", "Automation"],
    nativeSettings: ["stream rules", "official groupchat", "timeline action rewards"],
    automationHandles: [
      "w.timeline.viewed",
      "w.media_cache.viewed",
      "w.reply.created",
      "w.like.created",
      "w.repost.created",
      "w.quote.created",
      "w.groupchat.viewed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: ["w.groupchat-readonly-config-source"],
  },
  {
    id: "dicksword",
    label: "Dicksword",
    domain: "Social",
    subdomain: "Discord",
    kind: "app",
    routePatterns: ["/dicksword", "/discord/terms", "/discord/privacy", "/discord/linked-roles"],
    desktopAppKey: "dicksword",
    adminPanelTabs: ["Roles", "Automation", "System Logs"],
    nativeSettings: ["Discord role mappings", "avatar layers", "activity ingestion"],
    automationHandles: ["discord.claim.created", "discord.activity.ingested", "attendance.voice_state_ingested"],
  },
  {
    id: "i-hate-telegram",
    label: "I Hate Telegram",
    domain: "Social",
    subdomain: "Telegram digest",
    kind: "app",
    routePatterns: ["/i-hate-telegram"],
    desktopAppKey: "i-hate-telegram",
    adminPanelTabs: ["Content", "Board", "Automation", "System Logs"],
    nativeSettings: [
      "approved Telegram sources",
      "read-only digest visibility",
      "announcement queue",
      "FART NOISES bridge status",
    ],
    automationHandles: [
      "telegram.digest.message_ingested",
      "telegram.announcement.queued",
      "telegram.fart.mirrored",
      "fart_noises.track.requested",
      "app.interaction.tracked",
    ],
  },
  {
    id: "mission-control",
    label: "Mission Control",
    domain: "Desktop OS",
    subdomain: "Mission Control",
    kind: "app",
    routePatterns: ["/mission-control"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs", "Rewards", "Automation"],
    nativeSettings: [
      "user-first status",
      "active wallet state",
      "claimable rewards",
      "failed jobs",
      "next actions",
    ],
    automationHandles: [
      "mission_control.viewed",
      "mission_control.action_opened",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: ["gameshow.launch-surfaces-active-challenge-ui"],
  },
  {
    id: "notifications",
    label: "Notification Center",
    domain: "Desktop OS",
    subdomain: "Notification Center",
    kind: "app",
    routePatterns: ["/notification-center", "/notifications"],
    adminPanelTabs: ["Desktop Apps", "Users", "Automation", "System Logs"],
    nativeSettings: [
      "notification templates",
      "preference defaults",
      "unread filters",
      "linked targets",
      "reward notifications",
    ],
    automationHandles: [
      "notification_center.viewed",
      "notification_center.mark_read",
      "notification_center.mark_all_read",
      "notification_center.preferences_saved",
      "notification_center.notification_opened",
      "notification_center.filter_changed",
      "notification.viewed",
      "notification.opened",
      "notification.read",
      "notification.read_all",
      "notification.preference.updated",
      "app.interaction.tracked",
    ],
  },
  {
    id: "public-profile",
    label: "Public Profile",
    domain: "Social",
    subdomain: "Public identity",
    kind: "public-surface",
    routePatterns: ["/user/:username"],
    adminPanelTabs: ["Users", "XP Log", "Automation"],
    nativeSettings: ["identity fields", "public social visibility", "profile abuse review"],
    automationHandles: ["profile.public.viewed", "profile.updated", "app.interaction.tracked"],
  },
  {
    id: "wtfiam",
    label: "WTF In-App Marketplace",
    domain: "Commerce",
    subdomain: "In-app market",
    kind: "app",
    routePatterns: ["/wtfiam"],
    desktopAppKey: "wtfiam",
    adminPanelTabs: ["In-App Market", "Rewards", "Automation"],
    nativeSettings: ["catalog item status", "stock", "rarity tiers", "price scores", "sales", "desktop item unlock rewards"],
    automationHandles: [
      "wtfiam.checkout.completed",
      "wtfiam.admin.price_rebalanced",
      "wtfiam.admin.sale_updated",
      "inventory.item.granted",
      "inventory.item.transferred",
      "wtf_live.tip.redeemed",
      "wtf.awarded",
      "reward.ledger.created",
    ],
    behaviorAssertionIds: [
      "wallet.checkout-intent-bound-to-signed-session",
      "inventory.temporary-grants-unlock-apps",
      "wtf-live.tip-items-transfer-redeem",
    ],
  },
  {
    id: "marketplace",
    label: "On Chain Market",
    domain: "Commerce",
    subdomain: "Marketplace",
    kind: "app",
    routePatterns: ["/marketplace", "/trade-boards", "/swap"],
    adminPanelTabs: ["Contract Ledger", "Rewards", "Automation"],
    nativeSettings: ["listing policy", "auction moderation", "trade-board reward triggers"],
    automationHandles: ["marketplace.listing_created", "trade_board.updated", "wallet.provider.preflight.failed"],
    behaviorAssertionIds: ["marketplace.offer-accept-explicit-terms"],
  },
  {
    id: "club-dues",
    label: "Club Dues Manager",
    domain: "Club Dues",
    subdomain: "Memberships and subscription access",
    kind: "app",
    routePatterns: ["/dues"],
    desktopAppKey: "dues-manager",
    adminPanelTabs: ["Contract Ledger", "Automation", "Rewards", "OS Admin"],
    nativeSettings: [
      "contract templates",
      "manager wallet deployment",
      "dues terms",
      "membership access",
      "arrears warnings",
    ],
    automationHandles: [
      "club_dues.contract.customized",
      "club_dues.contract.deployed",
      "club_dues.payment.intent_created",
      "club_dues.payment.verified",
      "club_dues.member.arrears_warned",
      "club_dues.external_wallet.deployed",
    ],
    behaviorAssertionIds: ["club-dues.compile-membership-preflight"],
  },
  {
    id: "hoard",
    label: "Hoard",
    domain: "Wallet",
    subdomain: "Portfolio",
    kind: "app",
    routePatterns: ["/hoard", "/tezos-intel", "/collekt"],
    desktopAppKey: "hoard",
    adminPanelTabs: ["WTF Tez", "Contract Ledger", "Automation"],
    nativeSettings: ["wallet sync", "token ownership predicates"],
    automationHandles: ["user.wallet.connected", "token.contract.owned", "token.id.owned"],
    behaviorAssertionIds: [
      "auth.wallet-challenge-login",
      "auth.wallet-provider-login-lifecycle",
      "wallet.checkout-intent-bound-to-signed-session",
      "wallet.passive-refresh-no-signature",
    ],
  },
  {
    id: "wtf-domains",
    label: "WTF Domains",
    domain: "Wallet",
    subdomain: "Subdomains and user sites",
    kind: "app",
    routePatterns: ["/wtf-subdomains", "/wtf-subdomains/setup"],
    desktopAppKey: "wtf-subdomains",
    adminPanelTabs: ["WTF Tez", "OS Admin", "Automation"],
    nativeSettings: [
      "domain grants",
      "subdomain setup",
      "registrar config",
      "user-site publishing hosts",
      "Macaroni drop-page readiness",
    ],
    automationHandles: [
      "wtf_domain.grants.viewed",
      "wtf_domain.registration.prepared",
      "ipfs_pinning.subdomain_registry.linked",
      "wtf_site.claimed",
      "wtf_site.public.viewed",
      "macaroni.drop_published",
    ],
    behaviorAssertionIds: [
      "ipfs-pinning.pds-backed-wallet-backup",
      "settings.subdomain-setup-applet",
      "account.cobwebsaints-domain-advanced-readiness",
      "macaroni.shadownet-rpc-wallet-setup",
      "pasta-protocol.wtfme-hosted-pages",
      "pasta-protocol.pinning-recovery",
    ],
  },
  {
    id: "tv",
    label: "WTF TV",
    domain: "Media",
    subdomain: "TV",
    kind: "app",
    routePatterns: ["/tv"],
    desktopAppKey: "tv",
    adminPanelTabs: ["WTF TV", "Content", "Automation"],
    nativeSettings: ["source mode", "playlist size", "bumpers", "refresh cadence", "cache policy"],
    automationHandles: ["tv.telemetry.ingested", "media.tv_added", "app.interaction.tracked"],
    behaviorAssertionIds: ["tv.public-channel-stream-embed"],
  },
  {
    id: "media-library",
    label: "Media Libraries",
    domain: "Media",
    subdomain: "Owned media",
    kind: "app",
    routePatterns: ["/my-gallery", "/gallery", "/gallery/token/:contract/:tokenId", "/token/:contract/:tokenId", "/my-videos", "/my-photos", "/my-music"],
    desktopAppKey: "gallery",
    adminPanelTabs: ["Content", "Automation", "System Logs"],
    nativeSettings: ["media storage", "public gallery curation", "token import rules", "TV attachment"],
    automationHandles: ["media.imported", "media.uploaded", "token_archive.requested"],
    behaviorAssertionIds: ["media.creation-gallery-preservation-proof"],
  },
  {
    id: "tezosbeats",
    label: "TezosBeats",
    domain: "Media",
    subdomain: "FAFOlab music player",
    kind: "app",
    routePatterns: ["/music", "/tezamp"],
    adminPanelTabs: ["Content", "Media Storage", "Automation"],
    nativeSettings: [
      "music NFT source filters",
      "playlist mutation audit",
      "now-playing telemetry",
      "skllzrmy creator attribution",
    ],
    automationHandles: [
      "music.opened",
      "music.first_play",
      "music.track_played",
      "music.playlist_create",
    ],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "studio",
    label: "Studio",
    domain: "Creation",
    subdomain: "Project studio",
    kind: "app",
    routePatterns: ["/studio", "/studio/:id"],
    desktopAppKey: "studio",
    adminPanelTabs: ["Studio", "Content", "Automation"],
    nativeSettings: ["Drive root", "storage quota", "member permissions", "publish handoff"],
    automationHandles: ["studio.project.created", "studio.project.updated", "game_studio.project_mutated"],
    behaviorAssertionIds: ["media.creation-gallery-preservation-proof"],
  },
  {
    id: "game-studio",
    label: "Game Studio",
    domain: "Creation",
    subdomain: "Arcade publishing",
    kind: "app",
    routePatterns: ["/game-studio"],
    desktopAppKey: "game-studio",
    adminPanelTabs: ["Arcade", "Studio", "Automation"],
    nativeSettings: ["templates", "trusted creator publish", "bundle validation", "score caps"],
    automationHandles: ["arcade.game.submitted", "arcade.game.approved", "game_sdk.score_updated"],
    behaviorAssertionIds: [
      "arcade-console.sessions-and-scores",
      "media.creation-gallery-preservation-proof",
    ],
  },
  {
    id: "ch-ease",
    label: "CH-EASE",
    domain: "Creation",
    subdomain: "Macaroni package staging",
    kind: "app",
    routePatterns: ["/tools/ch-ease", "/tools/macaroni-packager"],
    desktopAppKey: "ch-ease",
    adminPanelTabs: ["Content", "Media Storage", "Automation", "System Logs"],
    nativeSettings: [
      "desktop app launcher gate",
      "wtfOS package storage",
      "original filename metadata preservation",
      "numbered artifact filename policy",
      "Macaroni package source handoff",
      "platform export target selection",
      "drop page config packaging",
      "Studio collaboration handoff",
      "WTF Domains and IPFS storage handoffs",
    ],
    automationHandles: [
      "macaroni.package_created",
      "macaroni.package_item_uploaded",
      "macaroni.package_metadata_updated",
      "macaroni.package_drop_config_updated",
      "macaroni.package_finalized",
      "macaroni.package_csv_downloaded",
      "macaroni.package_export_downloaded",
      "macaroni.package_source_loaded",
      "macaroni.package_handoff_opened",
      "ipfs_pinning.storage.staged",
      "ipfs_pinning.pin.completed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "macaroni.wtfos-package-source",
    ],
  },
  {
    id: "pasta-protocol",
    label: "Pasta Protocol",
    domain: "Pasta Protocol",
    subdomain: "Contract publishers and ownership console",
    kind: "app",
    routePatterns: [
      "/tools/colander",
      "/tools/spaghetti",
      "/tools/gnocchi",
      "/tools/ravioli",
      "/tools/rotini",
      "/tools/penne",
      "/tools/lasagna",
    ],
    desktopAppKey: "pasta-protocol",
    adminPanelTabs: ["Content", "Media Storage", "Automation", "System Logs"],
    nativeSettings: [
      "desktop app launcher gate",
      "signed-in publisher access",
      "trusted-market-creator wtfOS pinner capability",
      "CH-EASE package handoffs",
      "Colander contract action handoffs",
      "Tezos Mainnet and Shadownet RPC doctrine",
    ],
    automationHandles: [
      "chease.package_handoff_opened",
      "spaghetti.collection_deployed",
      "spaghetti.token_published",
      "spaghetti.exported",
      "gnocchi.collection_deployed",
      "gnocchi.edition_published",
      "gnocchi.edition_minted",
      "ravioli.collection_deployed",
      "ravioli.bundle_published",
      "ravioli.redeemed",
      "ravioli.contents_revealed",
      "rotini.collection_deployed",
      "rotini.generated",
      "rotini.tokens_published",
      "rotini.package_exported",
      "penne.collection_deployed",
      "penne.distribution_configured",
      "lasagna.exhibition_published",
      "lasagna.registry_updated",
      "colander.contract_opened",
      "colander.handoff_opened",
      "colander.transfer_submitted",
      "colander.role_updated",
      "colander.graph_viewed",
      "wtf_site.public.viewed",
    ],
    behaviorAssertionIds: [
      "pasta-protocol.sandbox-safe-feedback",
      "pasta-protocol.chease-handoff",
      "pasta-protocol.colander-context-handoff",
      "pasta-protocol.wtfme-hosted-pages",
      "pasta-protocol.pinning-recovery",
    ],
  },
  {
    id: "creation-tools",
    label: "Creation Tools",
    domain: "Creation",
    subdomain: "Particle, art, and drop tools",
    kind: "tool",
    routePatterns: [
      "/tools/broot",
      "/tools/particle-painter",
      "/tools/industrializer",
      "/tools/pauls-particles-v1",
      "/tools/nikshumika-paint",
      "/tools/kandinsky-composer",
      "/tools/pixel-patterns",
      "/tools/penrose-backgrounds",
      "/tools/macaroni",
    ],
    adminPanelTabs: ["Content", "Automation"],
    nativeSettings: ["tool availability", "export rules", "Broot local draft and file export policy", "contract origination roles", "IPFS pinning", "drop page publishing", "wtfOS package sources", "mint challenge triggers"],
    automationHandles: ["creation_tool.opened", "macaroni.package_finalized", "macaroni.drop_published", "mint_submission.created", "app.interaction.tracked"],
    behaviorAssertionIds: [
      "broot.media-open-import",
      "broot.project-file-vanity-extension",
      "broot.ffmpeg-glfx-layer-ops",
      "broot.wallet-hen-mint",
      "ipfs-pinning.pds-backed-wallet-backup",
      "account.cobwebsaints-domain-advanced-readiness",
      "skullzarmy.fafolab-integration-contracts",
      "macaroni.shadownet-rpc-wallet-setup",
      "macaroni.wtfos-package-source",
    ],
  },
  {
    id: "mastodon",
    label: "Mastodon (Tusk)",
    domain: "Social",
    subdomain: "Fediverse integration",
    kind: "tool",
    routePatterns: ["/w"],
    adminRoutes: ["/api/mastodon/account", "/api/mastodon/timeline"],
    adminPanelTabs: ["Social", "System Logs"],
    nativeSettings: ["linked accounts", "timeline refresh", "feed preferences"],
    automationHandles: ["mastodon.link", "mastodon.timeline", "mastodon.preferences.updated"],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "ipfs-pinning",
    label: "IPFS Pinning Manager",
    domain: "Storage",
    subdomain: "PDS-backed IPFS pinning",
    kind: "app",
    desktopAppKey: "ipfs-pinning",
    routePatterns: ["/ipfs-pinning", "/apps/porcupin-setup", "/apps/porcupin-dashboard"],
    adminRoutes: [
      "/api/ipfs-pinning/overview",
      "/api/ipfs-pinning/policies",
      "/api/ipfs-pinning/pasta-protocol/publish",
      "/api/ipfs-pinning/upload",
      "/api/wtf-subdomains/pins/summary",
      "/api/macaroni/ipfs/pin",
    ],
    adminPanelTabs: ["System Logs", "Automation"],
    nativeSettings: [
      "pin collector access",
      "wallet backup policy",
      "PDS publish state",
      "provider health",
      "Hetzner S3 staging",
      "Storage Box manifest mirror",
      "quota limits",
      "restore proofs",
    ],
    automationHandles: [
      "ipfs_pinning.policy.saved",
      "ipfs_pinning.wallet_backup.enabled",
      "ipfs_pinning.storage.staged",
      "ipfs_pinning.pin.completed",
      "ipfs_pinning.pds_record.queued",
      "ipfs_pinning.pds_record.published",
      "ipfs_pinning.subdomain_registry.linked",
      "ipfs_pinning.restore_proof.created",
      "wtf_site.public.viewed",
      "porcupin.connect",
      "porcupin.premium.check",
    ],
    behaviorAssertionIds: [
      "ipfs-pinning.pds-backed-wallet-backup",
      "account.cobwebsaints-domain-advanced-readiness",
      "macaroni.wtfos-package-source",
      "skullzarmy.fafolab-integration-contracts",
      "pasta-protocol.wtfme-hosted-pages",
      "pasta-protocol.pinning-recovery",
    ],
  },
  {
    id: "discovery-engine",
    label: "NFT Discovery",
    domain: "Commerce",
    subdomain: "Discovery and spotlight",
    kind: "tool",
    routePatterns: ["/dashboard"],
    adminRoutes: ["/api/discovery/random-artist", "/api/discovery/random-nft", "/api/discovery/spotlight"],
    adminPanelTabs: ["Commerce", "System Logs"],
    nativeSettings: ["spotlight rotation", "TzKT source contracts"],
    automationHandles: ["discovery.random_artist", "discovery.random_nft", "discovery.spotlight"],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "social-automation",
    label: "Social Automation",
    domain: "Social",
    subdomain: "Marketplace promotion",
    kind: "tool",
    routePatterns: ["/admin"],
    adminRoutes: ["/api/social-automation/promoter/status", "/api/social-automation/weekly"],
    adminPanelTabs: ["Social", "Automation", "System Logs"],
    nativeSettings: ["promoter toggle", "tweet approval queue", "weekly thread schedule", "opt-in policy"],
    automationHandles: ["social.auto_promote", "social.weekly_thread"],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "arcade",
    label: "WTF Arcade",
    domain: "Arcade",
    subdomain: "Public play",
    kind: "app",
    routePatterns: ["/arcade"],
    desktopAppKey: "arcade",
    adminPanelTabs: ["Arcade", "Rewards", "Automation"],
    nativeSettings: ["game moderation", "play tickets", "score caps", "creator reward triggers"],
    automationHandles: ["arcade.session.created", "arcade.score.accepted", "xp.awarded"],
    behaviorAssertionIds: [
      "inventory.temporary-grants-unlock-apps",
      "arcade-console.sessions-and-scores",
      "skullzarmy.fafolab-integration-contracts",
    ],
  },
  {
    id: "casino",
    label: "WTF Casino",
    domain: "Casino",
    subdomain: "Wagered games",
    kind: "app",
    routePatterns: [
      "/casino",
      "/casino/wtf-button",
      "/casino/rug-pull",
      "/casino/guinea-pig-raceway",
    ],
    desktopAppKey: "casino",
    adminPanelTabs: ["In-App Market", "Contract Ledger", "Automation"],
    nativeSettings: [
      "app pass SKU",
      "XTZ membership contract",
      "house take policy",
      "casino audit chain",
      "game table registry",
      "WTF Button mocked escrow adapter",
      "WTF Button price protection policy",
      "WTF Button Rug Clash randomness audit",
      "Rug Pull mocked round adapter",
      "Rug Pull panic settlement policy",
      "Raceway mocked tote board",
      "Raceway 3D asset manifest",
      "Raceway effect caps and replay archive",
    ],
    automationHandles: [
      "casino.access.viewed",
      "casino.membership.intent_created",
      "casino.membership.verified",
      "casino.games.viewed",
      "casino.entry.granted",
      "casino.entry.rejected",
      "casino.wager_session.rejected",
      "casino.audit.event_recorded",
      "wtf_button.lobby.viewed",
      "wtf_button.table.viewed",
      "wtf_button.quote.created",
      "wtf_button.press.succeeded",
      "wtf_button.press.rejected",
      "wtf_button.price_protection.rejected",
      "wtf_button.danger_zone.entered",
      "wtf_button.rug_clash.started",
      "wtf_button.rug_clash.entered",
      "wtf_button.rug_clash.resolved",
      "wtf_button.round.settled",
      "wtf_button.round.refunded",
      "wtf_button.audit.event_recorded",
      "wtf_button.simulation.run",
      "rug_pull.rules.viewed",
      "rug_pull.round.join_intent_created",
      "rug_pull.button.delay_intent_created",
      "rug_pull.button.press_intent_created",
      "rug_pull.witness.join_intent_created",
      "rug_pull.witness.vote_cast",
      "rug_pull.round.settled",
      "rug_pull.audit.event_recorded",
      "rug_pull.wager.rejected",
      "guinea_pig_raceway.rules.viewed",
      "guinea_pig_raceway.race_card.viewed",
      "guinea_pig_raceway.tote.viewed",
      "guinea_pig_raceway.ticket.accepted",
      "guinea_pig_raceway.ticket.refunded",
      "guinea_pig_raceway.official_result.recorded",
      "guinea_pig_raceway.bet_intent_created",
      "guinea_pig_raceway.bet_locked",
      "guinea_pig_raceway.bet_rejected",
      "guinea_pig_raceway.intro.started",
      "guinea_pig_raceway.race.started",
      "guinea_pig_raceway.effect_intent_created",
      "guinea_pig_raceway.effect_rejected",
      "guinea_pig_raceway.race.settled",
      "guinea_pig_raceway.replay.viewed",
      "guinea_pig_raceway.audit.event_recorded",
      "guinea_pig_raceway.wager.rejected",
    ],
    behaviorAssertionIds: [
      "inventory.temporary-grants-unlock-apps",
      "casino.access-game-apis",
    ],
  },
  {
    id: "console",
    label: "WTF Console",
    domain: "Console",
    subdomain: "Owned games",
    kind: "app",
    routePatterns: ["/console"],
    desktopAppKey: "console",
    adminPanelTabs: ["Arcade", "System Logs", "Automation"],
    nativeSettings: ["stock cartridges", "reports", "score anti-cheat", "cache dependencies"],
    automationHandles: ["console.session.created", "console.score.accepted", "console.audit.score_rejected"],
    behaviorAssertionIds: ["arcade-console.sessions-and-scores"],
  },
  {
    id: "leaderboard",
    label: "Leaderboard",
    domain: "Public",
    subdomain: "Rankings",
    kind: "public-surface",
    routePatterns: ["/leaderboard"],
    adminPanelTabs: ["Users", "XP Log", "Rewards", "Automation"],
    nativeSettings: ["XP ranking visibility", "holder ranking visibility", "abuse review"],
    automationHandles: ["leaderboard.viewed", "leaderboard.xp.viewed"],
  },
  {
    id: "content-pages",
    label: "Links and FAQ",
    domain: "Public",
    subdomain: "Static content",
    kind: "public-surface",
    routePatterns: ["/links", "/faq"],
    adminPanelTabs: ["Content", "Automation"],
    nativeSettings: ["links", "FAQ categories", "display order"],
    automationHandles: ["public.link.opened", "faq.viewed"],
    behaviorAssertionIds: ["public-data-mcp-agent-token-proof"],
  },
  {
    id: "admin-panel",
    label: "Admin Panel",
    domain: "Admin",
    subdomain: "Control center",
    kind: "admin-tool",
    routePatterns: ["/admin"],
    adminPanelTabs: ["OS Admin", "Automation", "Users", "Roles", "Rewards"],
    nativeSettings: [
      "surface registry",
      "permissions",
      "user curses",
      "reward automation",
      "audit coverage",
    ],
    automationHandles: [
      "admin.challenge_automation.updated",
      "admin.permissions.updated",
      "admin.user.curse_assigned",
      "admin.user.curse_lifted",
    ],
    behaviorAssertionIds: [
      "auth.additive-role-surface-access",
      "desktop.app-gates-runtime-policy",
      "auth.time-out-app-lockdown",
      "public-data-mcp-agent-token-proof",
    ],
  },
  {
    id: "control-board",
    label: "Control Board",
    domain: "Admin",
    subdomain: "Gameshow operations",
    kind: "admin-tool",
    routePatterns: ["/control-board"],
    adminPanelTabs: ["Control Board", "Automation"],
    adminRoutes: ["/control-board"],
    nativeSettings: ["round operations", "contestant state", "host actions"],
    automationHandles: ["control_board.action_applied", "gameshow.round.joined"],
  },
  {
    id: "operator-tools",
    label: "Operator and Contract Tools",
    domain: "Admin",
    subdomain: "Contracts",
    kind: "admin-tool",
    routePatterns: ["/operator-wallet", "/contract-factory"],
    adminPanelTabs: ["Contract Ledger", "Rewards", "Automation"],
    adminRoutes: ["/operator-wallet", "/contract-factory"],
    nativeSettings: ["operator balances", "payout runs", "contract deploy parameters"],
    automationHandles: ["operator.disbursement.run", "contract_activity.submitted"],
    behaviorAssertionIds: ["skullzarmy.fafolab-integration-contracts"],
  },
  {
    id: "ux-lab",
    label: "UX Lab",
    domain: "Admin",
    subdomain: "UX testing",
    kind: "admin-tool",
    routePatterns: ["/dev/ux-lab"],
    adminPanelTabs: ["OS Admin"],
    nativeSettings: ["design smoke routes", "portfolio workspace links"],
    automationHandles: ["ux_lab.opened"],
  },
  {
    id: "recovery-mode",
    label: "Recovery Mode",
    domain: "Desktop OS",
    subdomain: "Recovery Mode",
    kind: "app",
    routePatterns: ["/recovery-mode"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs", "Media Storage"],
    nativeSettings: [
      "local repair actions",
      "wallet disconnect",
      "network reset",
      "filesystem probes",
      "operator repair routing",
    ],
    automationHandles: [
      "recovery_mode.viewed",
      "recovery_mode.wallets_disconnected",
      "recovery_mode.network_reset",
      "recovery_mode.window_session_cleared",
      "recovery_mode.filesystem_checked",
      "recovery_mode.report_exported",
      "recovery_mode.action_opened",
      "app.interaction.tracked",
    ],
  },
  {
    id: "backup-manager",
    label: "Backup Manager",
    domain: "Admin",
    subdomain: "Backup and restore proof",
    kind: "admin-tool",
    routePatterns: ["/backup-manager"],
    adminPanelTabs: ["System Logs", "Media Storage", "OS Admin"],
    adminRoutes: ["/backup-manager"],
    nativeSettings: ["backup artifacts", "restore drills", "target checksums", "safety claims"],
    automationHandles: ["backup_manager.viewed", "backup_manager.opened", "system.health.checked"],
  },
  {
    id: "command-palette",
    label: "Command Palette",
    domain: "Desktop OS",
    subdomain: "Command palette",
    kind: "app",
    routePatterns: ["/command-palette"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "route commands",
      "workflow commands",
      "role gates",
      "admin command visibility",
    ],
    automationHandles: [
      "command_palette.opened",
      "command_palette.executed",
      "desktop.window.opened",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "desktop.app-gates-runtime-policy",
      "auth.time-out-app-lockdown",
    ],
  },
  {
    id: "desktop-appearance",
    label: "Theme Builder",
    domain: "Desktop OS",
    subdomain: "Theme Builder",
    kind: "app",
    routePatterns: ["/theme-builder", "/desktop-settings"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "OS appearance grammar",
      "font pack",
      "chat typography defaults",
      "localized OS shell labels",
      "theme colors",
      "wallpaper policy",
      "token wallpaper",
      "cursor style",
      "physics mode",
      "weather tray control",
      "MCP pairing",
    ],
    automationHandles: [
      "desktop.settings.viewed",
      "desktop.appearance.updated",
      "desktop.wallpaper.uploaded",
      "desktop.wallpaper.token_set",
      "desktop.physics.updated",
      "desktop.weather.updated",
      "desktop.font_pack.updated",
      "desktop.chat_typography.updated",
      "system_settings.language_changed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "desktop.settings-events-pet",
      "desktop.font-pack.updated",
      "desktop.localization-language-region",
    ],
  },
  {
    id: "system-settings",
    label: "System Settings",
    domain: "Desktop OS",
    subdomain: "Settings hub",
    kind: "app",
    routePatterns: ["/settings"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "settings routes",
      "language and region preference",
      "account settings links",
      "subdomain setup window handoff",
      "admin route gates",
      "owner app boundaries",
    ],
    automationHandles: [
      "system_settings.viewed",
      "system_settings.opened",
      "system_settings.language_changed",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "settings.subdomain-setup-applet",
      "account.cobwebsaints-domain-advanced-readiness",
      "desktop.localization-language-region",
    ],
  },
  {
    id: "browser-boundaries",
    label: "Browser Boundaries",
    domain: "Desktop OS",
    subdomain: "Browser access boundaries",
    kind: "app",
    routePatterns: ["/browser-boundaries"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "standard access manifest",
      "browser route gates",
      "MCP bearer boundary",
      "CSP frame boundary",
      "browser mode separation",
    ],
    automationHandles: [
      "browser_boundaries.viewed",
      "browser_boundaries.action_opened",
      "app.interaction.tracked",
    ],
  },
  {
    id: "terminal",
    label: "Terminal",
    domain: "Desktop OS",
    subdomain: "Safe terminal",
    kind: "app",
    routePatterns: ["/terminal"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "allowlisted commands",
      "read-only diagnostics",
      "route launch commands",
      "shell execution disabled",
      "shared wtfos-cli kernel",
    ],
    automationHandles: [
      "terminal.viewed",
      "terminal.command_executed",
      "app.interaction.tracked",
    ],
  },
  {
    id: "cli",
    label: "CLI",
    domain: "Desktop OS",
    subdomain: "CLI shell",
    kind: "app",
    routePatterns: ["/cli"],
    adminPanelTabs: ["Desktop Apps", "OS Admin", "System Logs"],
    nativeSettings: [
      "full-screen cli/tui",
      "shared wtfos-cli kernel",
      "interface mode preference",
      "allowlisted commands only",
      "shell execution disabled",
    ],
    automationHandles: [
      "cli.viewed",
      "cli.command_executed",
      "app.interaction.tracked",
    ],
  },
  {
    id: "file-manager",
    label: "File Manager",
    domain: "Desktop OS",
    subdomain: "Dwellings",
    kind: "app",
    routePatterns: ["/file-manager"],
    adminPanelTabs: ["Desktop Apps", "Media Storage", "Studio", "System Logs"],
    nativeSettings: ["dwelling routes", "media counts", "project counts", "archive proof links"],
    automationHandles: ["file_manager.viewed", "file_manager.opened", "app.interaction.tracked"],
  },
];

export const DESKTOP_ITEM_ADMIN_SURFACES: AdminSurface[] = [
  {
    id: "desktop-pet",
    label: "Desktop Pet",
    domain: "Desktop OS",
    subdomain: "Pet",
    kind: "desktop-item",
    routePatterns: ["desktop://pet"],
    adminPanelTabs: ["In-App Market", "XP Log", "Automation"],
    nativeSettings: ["care XP", "starter food", "pet events", "safe MCP pet actions"],
    automationHandles: ["desktop.pet.interacted", "xp.awarded", "app.interaction.tracked"],
    behaviorAssertionIds: ["desktop.settings-events-pet"],
  },
  {
    id: "desktop-artifacts",
    label: "Desktop Artifacts",
    domain: "Desktop OS",
    subdomain: "Inventory-backed items",
    kind: "desktop-item",
    routePatterns: ["desktop://artifacts"],
    adminPanelTabs: ["In-App Market", "Automation"],
    nativeSettings: [
      "fan",
      "lights",
      "sticky notes",
      "mop",
      "vacuum",
      "cursor tray",
      "train kit",
      "portal gun",
      "jukebox",
      "paper shredder",
      "generic artifacts",
    ],
    automationHandles: [
      "desktop.object.clicked",
      "desktop.artifact.spawned",
      "desktop.tool.selected",
      "desktop.item.effect_triggered",
      "inventory.item.granted",
      "app.interaction.tracked",
    ],
  },
  {
    id: "desktop-reggie",
    label: "Reggie Assistant",
    domain: "Desktop OS",
    subdomain: "Onboarding assistant",
    kind: "desktop-item",
    routePatterns: ["desktop://reggie"],
    adminPanelTabs: ["Automation", "XP Log", "System Logs"],
    nativeSettings: [
      "onboarding questline seeding",
      "step prerequisite graph",
      "checkpoint event allowlist",
      "dialogue and knowledge base (non-AI)",
      "nag cadence and snooze",
    ],
    automationHandles: [
      "reggie.assistant.opened",
      "reggie.hint.shown",
      "reggie.question.asked",
      "reggie.checkpoint.reached",
      "reggie.progress.checked",
      "reggie.quest.completed",
      "xp.awarded",
      "wtf.awarded",
      "app.interaction.tracked",
    ],
  },
  {
    id: "desktop-icons",
    label: "Desktop Icons",
    domain: "Desktop OS",
    subdomain: "Launch icons",
    kind: "desktop-item",
    routePatterns: ["desktop://icons"],
    adminPanelTabs: ["Desktop Apps", "OS Admin"],
    nativeSettings: ["icon visibility", "per-user desktop layout", "experimental icon outline", "launch routes"],
    automationHandles: [
      "desktop.icon.opened",
      "desktop.icon.moved",
      "desktop.icon_layout.reset",
      "desktop.object.clicked",
      "app.interaction.tracked",
    ],
    behaviorAssertionIds: [
      "desktop.app-gates-runtime-policy",
      "auth.time-out-app-lockdown",
    ],
  },
];

export const ALL_ADMIN_SURFACES = [
  ...ADMIN_SURFACES,
  ...DESKTOP_ITEM_ADMIN_SURFACES,
];

function patternToRegex(pattern: string) {
  const escaped = pattern
    .replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
    .replace(/:(\w+)/g, "[^/]+");
  return new RegExp(`^${escaped}$`);
}

export function findAdminSurfaceForPath(path: string | null | undefined) {
  if (!path) return null;
  const cleanPath = path.split("?")[0] || path;
  return (
    ADMIN_SURFACES.find((surface) =>
      surface.routePatterns.some((pattern) => patternToRegex(pattern).test(cleanPath))
    ) ?? null
  );
}

export function surfacesByDomain() {
  return ALL_ADMIN_SURFACES.reduce<Record<string, AdminSurface[]>>((acc, surface) => {
    acc[surface.domain] = [...(acc[surface.domain] ?? []), surface];
    return acc;
  }, {});
}

export function getAdminSurfaceDoctrineDomain(surface: AdminSurface): DoctrineDomainGuide {
  return (
    doctrineDomainBySurfaceId[surface.id] ??
    doctrineDomainBySurfaceDomain[surface.domain] ??
    DOCTRINE_DOMAIN_GUIDES.wtfOs
  );
}
